from __future__ import annotations
import json, csv, datetime as dt, importlib.util, warnings
from pathlib import Path
import numpy as np, pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
warnings.filterwarnings('ignore')
ROOT=Path(__file__).resolve().parent; DATA=ROOT/'data'
HIST=DATA/'vn100_history_2025_06_2026_05_cache.json'
D1SRC=DATA/'d1a_full_research_features_is_oos.json'
STEP1=DATA/'core12_step1_select12_from40_rs_d1a_d1s_precision_first.json'
IND40=ROOT/'build_indicator40_ml_outputs.py'
OUT=DATA/'core12_step2_tune_params_precision_first_rs_d1a_d1s.json'
CSV=DATA/'core12_step2_tune_params_precision_first_rs_d1a_d1s.csv'
SPLITS=['2025-10-01','2026-01-01']
MIN_PRED={'RS':10,'D1A':10,'D1S':5}; MIN_RECALL={'RS':3.0,'D1A':3.0,'D1S':3.0}
spec=importlib.util.spec_from_file_location('ind40',IND40); ind40=importlib.util.module_from_spec(spec); spec.loader.exec_module(ind40)
# Parameter/feature variant groups generated by existing indicator40 library. Step2 chooses best variants inside selected indicator families.
FAMILY_PREFIX={
 'SMA':['sma'], 'EMA':['ema'], 'WMA':['wma'], 'MACD':['macd'], 'ICHIMOKU':['ichi'], 'ADX':['adx'], 'PSAR':['psar'], 'SUPERTREND':['supertrend'], 'DMI':['plusDI','minusDI','diSpread'], 'AROON':['aroon'], 'ZIGZAG':['zigzag'], 'TRIX':['trix'],
 'RSI':['rsi'], 'STOCHASTIC':['stoch'], 'CCI':['cci'], 'WILLIAMS_R':['williams'], 'MOMENTUM':['mom'], 'ROC':['roc'], 'AO':['ao'], 'ULTIMATE_OSC':['ultimate'], 'TSI':['tsi'], 'KDJ':['kdj'],
 'BOLLINGER':['bb'], 'ATR':['atr'], 'KELTNER':['keltner'], 'DONCHIAN':['donchian'], 'STDDEV':['std'], 'HIST_VOL':['hist_vol'], 'CHOPPINESS':['choppiness'], 'CHAIKIN_VOL':['chaikin_vol'], 'RVI':['rvi'], 'MASS_INDEX':['mass_index'],
 'VWAP':['vwap'], 'OBV':['obv'], 'CMF':['cmf'], 'AD_LINE':['ad_slope'], 'MFI':['mfi'], 'VWMA':['vwma'], 'PVI_NVI':['pvi','nvi'], 'VOSC_KLINGER':['vosc','klinger']
}
def load_rows():
    hist=json.load(open(HIST,encoding='utf-8'))['symbols']; src=json.load(open(D1SRC,encoding='utf-8'))['items']
    need={(x['symbol'],x['date']) for x in src}; smap={(x['symbol'],x['date']):x for x in src}; rows=[]
    for sym,p in hist.items():
        if not any(s==sym for s,_ in need): continue
        df=pd.DataFrame(p['rows']).sort_values('time').reset_index(drop=True)
        feat=ind40.add_indicator40(df).fillna(0)
        for _,r in feat.iterrows():
            key=(sym,str(r['date']))
            if key not in smap: continue
            base=smap[key]
            feats={k:float(v) for k,v in r.items() if k!='date' and isinstance(v,(int,float,np.integer,np.floating)) and np.isfinite(v)}
            rows.append({'symbol':sym,'date':key[1],'sector':base.get('sector'),'features40':feats,'rs':base.get('rs') or {},'lc':base.get('lc') or {},'full':base.get('fullResearchFeatures') or {},'mtf':base.get('mtfAsOfDate') or {}})
    rows.sort(key=lambda x:(x['date'],x['symbol'])); return rows
def label(task,r):
    lc,rs,f,mtf=r['lc'],r['rs'],r['full'],r['mtf']
    if task=='RS':
        near=bool(rs.get('nearSupport') or abs(rs.get('distSupportPct') or 99)<4)
        survive=(lc.get('futureMin20') or 0)>-7; rebound=(lc.get('futureMax20') or 0)>5
        return int(near and survive and rebound)
    if task=='D1A':
        future_survive=(lc.get('futureMin20') or 0)>-8 and (lc.get('futureClose20') or 0)>-5
        absorption=(f.get('dryUp20_norm',0)>0 or f.get('greenAbsorb10_norm',0)>0 or f.get('baseQualityScore_norm',0)>0)
        base_ok=(f.get('range40Pct_inv',0)>0 or f.get('tightClose20_norm',0)>0 or rs.get('nearSupport'))
        return int(future_survive and (absorption or base_ok))
    if task=='D1S':
        future_bad=(lc.get('futureMin20') or 0)<-10 or ((lc.get('futureClose20') or 0)<-6 and (lc.get('futureMin20') or 0)<-7)
        structural=rs.get('supportBroken') or rs.get('weekSupportBroken') or f.get('support_break',0)>0 or f.get('break_ma_cluster',0)>0
        distro=f.get('distribution_cluster',0)>0 or (f.get('two_red_high_vol_5d',0)>0 and f.get('close_low_cluster',0)>0)
        mtf_bad=((mtf.get('W_rsi14') or 50)<42 and not mtf.get('W_macdImproving')) or (not mtf.get('W_aboveMa20') and not mtf.get('W_maTrendUp'))
        return int(future_bad and (structural or distro or mtf_bad))
    raise ValueError(task)
def stats(y,p):
    pr,rc,f1,_=precision_recall_fscore_support(y,p,average='binary',zero_division=0)
    return {'n':int(len(y)),'tp':int(((p==1)&(y==1)).sum()),'fp':int(((p==1)&(y==0)).sum()),'tn':int(((p==0)&(y==0)).sum()),'fn':int(((p==0)&(y==1)).sum()),'precision':round(pr*100,2),'recall':round(rc*100,2),'accuracy':round(accuracy_score(y,p)*100,2),'f1':round(f1*100,2),'predN':int((p==1).sum()),'oracleN':int((y==1).sum())}
def clf(name,seed):
    if name=='ET': return ExtraTreesClassifier(n_estimators=360,max_depth=3,min_samples_leaf=8,class_weight='balanced',random_state=seed,n_jobs=1)
    if name=='RF': return RandomForestClassifier(n_estimators=360,max_depth=3,min_samples_leaf=8,class_weight='balanced',random_state=seed,n_jobs=1)
    return Pipeline([('s',StandardScaler()),('l',LogisticRegression(max_iter=1200,C=.25,class_weight='balanced',random_state=seed))])
def tune(y,prob,task):
    cand=[]
    for th in np.linspace(.10,.98,89):
        st=stats(y,(prob>=th).astype(int))
        if st['predN']<max(MIN_PRED[task],int(len(y)*.004)): continue
        if st['recall']<MIN_RECALL[task]: continue
        cand.append((st['precision'],st['recall'],st['f1'],st['predN'],float(th),st))
    if not cand: return None
    cand.sort(key=lambda x:(x[0],x[1],x[3],x[2]),reverse=True)
    return cand[0]
def candidate_feature_sets(all_feats,family):
    prefs=FAMILY_PREFIX[family]
    feats=sorted([f for f in all_feats if any(f.startswith(p) or p in f for p in prefs)])
    if not feats: return []
    sets=[]
    # each feature variant alone
    for f in feats: sets.append((f,[f]))
    # numeric-period buckets where applicable
    for token in ['7','10','14','20','21','40','50','60','100','200','slope','dist','width','pos','pct','hist','signal','spread']:
        fs=[f for f in feats if token in f]
        if fs: sets.append((family+'_'+token,fs))
    sets.append((family+'_ALL',feats))
    # de-dup
    out=[]; seen=set()
    for name,fs in sets:
        key=tuple(fs)
        if key not in seen:
            out.append((name,fs)); seen.add(key)
    return out
def eval_set(rows,task,family,setName,features,model):
    splits=[]
    for sp in SPLITS:
        tr=[r for r in rows if r['date']<sp]; te=[r for r in rows if r['date']>=sp]
        ytr=np.array([label(task,r) for r in tr]); yte=np.array([label(task,r) for r in te])
        if len(set(ytr))<2 or yte.sum()<2: return None
        Xtr=np.array([[r['features40'].get(f,0.0) for f in features] for r in tr],float); Xte=np.array([[r['features40'].get(f,0.0) for f in features] for r in te],float)
        keep=[i for i,s in enumerate(Xtr.std(axis=0)) if s>1e-9]
        if not keep: return None
        f2=[features[i] for i in keep]; Xtr=Xtr[:,keep]; Xte=Xte[:,keep]
        m=clf(model,abs(hash((task,family,setName,model,sp)))%100000); m.fit(Xtr,ytr)
        tuned=tune(ytr,m.predict_proba(Xtr)[:,1],task)
        if tuned is None: return None
        _,_,_,_,th,isst=tuned; oos=stats(yte,(m.predict_proba(Xte)[:,1]>=th).astype(int))
        splits.append({'split':sp,'threshold':round(th,3),'isStats':isst,'oosStats':oos,'features':f2})
    avgP=float(np.mean([s['oosStats']['precision'] for s in splits])); minP=min(s['oosStats']['precision'] for s in splits); avgR=float(np.mean([s['oosStats']['recall'] for s in splits])); pred=sum(s['oosStats']['predN'] for s in splits); avgF=float(np.mean([s['oosStats']['f1'] for s in splits]))
    pass70=avgP>=70 and minP>=50 and pred>=MIN_PRED[task]
    score=round(avgP*10+minP*4+avgR*.4+min(pred,80)*.06+avgF*.2,3)
    return {'task':task,'family':family,'setName':setName,'model':model,'features':features,'featureCount':len(features),'avgPrecision':round(avgP,2),'minPrecision':round(minP,2),'avgRecall':round(avgR,2),'avgF1':round(avgF,2),'totalPredN':int(pred),'passP70':pass70,'score':score,'splits':splits}
def main():
    rows=load_rows(); step1=json.load(open(STEP1,encoding='utf-8'))
    all_feats=sorted({k for r in rows for k in r['features40']})
    runs=[]
    for task,arr in step1['selected12ByTask'].items():
        # use top precision families, excluding obvious tiny-sample artifacts only if totalPredN < 2; Step2 can still prove/disprove variants.
        families=[x['indicator'] for x in arr]
        for fam in families:
            for name,fs in candidate_feature_sets(all_feats,fam):
                best=None
                for mn in ['LOG','ET','RF']:
                    r=eval_set(rows,task,fam,name,fs,mn)
                    if r and (best is None or (r['avgPrecision'],r['minPrecision'],r['avgRecall'],r['totalPredN'])>(best['avgPrecision'],best['minPrecision'],best['avgRecall'],best['totalPredN'])): best=r
                if best:
                    runs.append(best); print(json.dumps({k:best[k] for k in ['task','family','setName','model','avgPrecision','minPrecision','avgRecall','totalPredN','passP70']},ensure_ascii=False),flush=True)
    selected={}
    for task in ['RS','D1A','D1S']:
        arr=[r for r in runs if r['task']==task]
        arr.sort(key=lambda x:(x['avgPrecision'],x['minPrecision'],x['avgRecall'],x['totalPredN'],x['avgF1']),reverse=True)
        selected[task]=arr[:20]
    payload={'createdAt':dt.datetime.now().isoformat(timespec='seconds'),'method':'STEP2 precision-first parameter/feature variant tuning inside Step1-selected indicator families. Still no multi-indicator grouping/combo. Output is candidate tuned variants for Step3.','splits':SPLITS,'sourceStep1':str(STEP1),'selectedByTask':selected,'allRuns':runs}
    OUT.write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
    with CSV.open('w',encoding='utf-8-sig',newline='') as f:
        fields=['task','rank','family','setName','model','featureCount','avgPrecision','minPrecision','avgRecall','avgF1','totalPredN','passP70','score']
        w=csv.DictWriter(f,fieldnames=fields); w.writeheader()
        for task,arr in selected.items():
            for i,r in enumerate(arr,1): w.writerow({k:(i if k=='rank' else r.get(k)) for k in fields})
    print(json.dumps({'out':str(OUT),'csv':str(CSV),'selected':{t:[{k:r[k] for k in ['family','setName','model','avgPrecision','minPrecision','avgRecall','totalPredN','passP70']} for r in a[:12]] for t,a in selected.items()}},ensure_ascii=False,indent=2))
if __name__=='__main__': main()
