from pathlib import Path
import json, re
from playwright.sync_api import sync_playwright

summary=json.loads(Path('mit_18_642_transcripts_summary.json').read_text(encoding='utf-8'))
OUT_HTML=Path('reports/MIT_18_642_50_Trang_ChatGPT_Original_Quality.html')
OUT_MD=Path('reports/MIT_18_642_50_Trang_ChatGPT_Original_Quality.md')
OUT_PDF=Path('reports/MIT_18_642_50_Trang_ChatGPT_Original_Quality.pdf')

# Original lecture notes written from MIT transcript topics + local transcript audit, not copied from Claude file.
notes=[
{'n':'01','cluster':'Course frame','title':'Lecture 1 Part I — Introduction of the Class','core':'Video mở đầu đặt khung cho toàn khóa: toán học được dùng như ngôn ngữ để mô tả sản phẩm tài chính, rủi ro, xác suất và quyết định đầu tư. Người học được chuẩn bị cho một khóa vừa có phần lý thuyết toán, vừa có phần ứng dụng từ các chuyên gia thị trường.','learn':['Tài chính định lượng không phải là đoán giá, mà là mô hình hóa quyết định dưới bất định.','Một mô hình tốt phải nói rõ giả định, dữ liệu đầu vào, giới hạn và cách kiểm định.','Các chủ đề của khóa liên kết với nhau: linear algebra → probability → regression/PCA/time series → portfolio/derivatives/ML.'],'details':['Giảng viên nhấn mạnh đây là khóa ứng dụng, không chỉ thuần lý thuyết. Toán được học vì nó giúp định nghĩa vấn đề rõ hơn.','Người học phải quen với việc một vấn đề tài chính có nhiều lớp: sản phẩm, payoff, dữ liệu, rủi ro, mô hình và thị trường thực tế.','Điểm quan trọng là không thần thánh hóa công thức. Công thức là bản đồ; thị trường thực tế luôn có nhiễu, chi phí và ràng buộc.'],'formula':'Decision quality = model clarity + data quality + validation + risk control','investor':'Nhà đầu tư nên học cách đặt câu hỏi đúng: xác suất thắng bao nhiêu, payoff thế nào, sai khi nào, và có kiểm chứng bằng dữ liệu chưa.','wrong':'Không nên hiểu khóa học như bộ công thức tạo tín hiệu mua bán chắc thắng.'},
{'n':'02','cluster':'Markets','title':'Lecture 1 Part II — Financial Markets, Terms and Concepts','core':'Video này giới thiệu cấu trúc thị trường tài chính và các loại sản phẩm chính: cổ phiếu, trái phiếu, phái sinh, quỹ/alternative assets. Mỗi loại tài sản có payoff, rủi ro và cơ chế định giá riêng.','learn':['Cổ phiếu là quyền sở hữu; trái phiếu là dòng tiền nợ; phái sinh là hợp đồng phụ thuộc tài sản cơ sở.','Risk-return phải đi cùng liquidity, cost và market structure.','Nhà đầu tư cần hiểu sản phẩm trước khi dùng mô hình định lượng.'],'details':['Thị trường tài chính là cơ chế chuyển vốn và phân bổ rủi ro giữa các bên.','Sản phẩm khác nhau sinh lời từ nguồn khác nhau: business growth, coupon, leverage, volatility, liquidity premium.','Các thuật ngữ như alpha, beta, hedge, leverage, arbitrage, liquidity không phải trang trí; chúng mô tả bản chất payoff và rủi ro.'],'formula':'Net return = gross return - fees - spread - slippage - financing cost','investor':'Trước khi mua cổ phiếu/CW/trái phiếu, phải biết mình đang mua loại rủi ro nào và dòng payoff đến từ đâu.','wrong':'Không dùng cùng một checklist cho cổ phiếu cơ sở và chứng quyền/phái sinh.'},
{'n':'03','cluster':'Bond math','title':'Lecture 1 Part III — Bond Mathematics','core':'Video giảng nền tảng định giá dòng tiền: present value, lãi kép, lãi liên tục, yield, bond pricing, duration và convexity. Đây là phần nền cho mọi định giá tài chính.','learn':['Tiền trong tương lai cần được chiết khấu về hiện tại.','Khi yield tăng, giá trái phiếu giảm.','Duration và DV01 đo độ nhạy giá với lãi suất; convexity xử lý độ cong của quan hệ giá-yield.'],'details':['Bond price là tổng hiện giá của coupon và principal. Yield to maturity là tỷ suất chiết khấu làm giá trị hiện tại bằng giá thị trường.','Duration cho xấp xỉ tuyến tính khi yield đổi nhỏ; convexity cải thiện khi yield đổi lớn.','Yield curve chứa thông tin kỳ hạn: ngắn, trung, dài hạn có lãi suất khác nhau và phản ánh kỳ vọng/ưu tiên thanh khoản/rủi ro.'],'formula':'PV = CF/(1+r)^t\nBond Price = Σ Coupon_t/(1+y)^t + Face/(1+y)^T\nΔP/P ≈ -Duration × Δy + 0.5 × Convexity × (Δy)^2','investor':'Lãi suất là trọng lực định giá. Cổ phiếu tăng trưởng/P/E cao thường nhạy hơn với lãi suất vì dòng tiền kỳ vọng nằm xa tương lai.','wrong':'Đừng nghĩ bond math chỉ dùng cho trái phiếu; nó là nền tư duy chiết khấu của mọi tài sản.'},
{'n':'04','cluster':'Linear algebra','title':'Lecture 2 — Linear Algebra','core':'Video xây nền đại số tuyến tính: vector, matrix, basis, rank, linear transformation, eigenvalues/eigenvectors. Trong tài chính, dữ liệu nhiều tài sản/nhiều đặc trưng được biểu diễn bằng ma trận.','learn':['Một tài sản hoặc một ngày giao dịch có thể xem như vector feature.','Danh mục là tổ hợp tuyến tính của nhiều tài sản.','Eigenvectors/eigenvalues là nền cho PCA và phân tích covariance.'],'details':['Vector giúp mô tả một đối tượng bằng nhiều chiều: return, volatility, liquidity, sector, beta.','Matrix giúp mô tả toàn bộ universe: nhiều mã, nhiều ngày, nhiều biến.','Covariance matrix cho biết tài sản cùng biến động ra sao; đây là nguyên liệu của portfolio optimization.'],'formula':'x_stock = [return, volatility, beta, liquidity, sector_score]\nPortfolio return = wᵀr','investor':'Nếu muốn xây model cổ phiếu, bước đầu không phải ML mà là ma trận dữ liệu sạch: hàng là stock-date, cột là feature.','wrong':'Không nên nhồi nhiều indicator trùng ý nghĩa rồi tưởng là có nhiều bằng chứng độc lập.'},
{'n':'05','cluster':'Probability','title':'Lecture 4 — Linear Algebra continued; Probability Theory','core':'Video chuyển từ biểu diễn dữ liệu sang xác suất. Return, default, volatility và payoff là random variables có distribution, expectation, variance và correlation.','learn':['Expectation là trung bình có trọng số xác suất, không phải kết quả chắc chắn.','Variance/covariance đo rủi ro và liên hệ giữa biến.','Correlation giúp hiểu diversification nhưng không chứng minh nhân quả.'],'details':['Xác suất cho phép nói về tập hợp kết quả có thể xảy ra thay vì một dự báo duy nhất.','Trong nhiều tài sản, covariance matrix trở thành cầu nối giữa probability và linear algebra.','Distribution shape quan trọng: skewness và kurtosis/tail risk ảnh hưởng lớn đến đầu tư.'],'formula':'E[X] = Σ p_i x_i\nVar(X)=E[(X-E[X])²]\nCov(X,Y)=E[(X-E[X])(Y-E[Y])]','investor':'Một chiến lược tốt không chỉ có return trung bình cao, mà phải có phân phối lỗ/lãi chịu được.','wrong':'Không được đánh giá chiến lược chỉ bằng vài ví dụ thắng hoặc win rate đơn giản.'},
{'n':'06','cluster':'Stochastic process','title':'Lecture 5 — Probability continued; Stochastic Processes I','core':'Video giới thiệu quá trình ngẫu nhiên: giá tài sản là chuỗi biến ngẫu nhiên theo thời gian. Các ý như random walk, martingale, Markov chain và gambler’s ruin rất quan trọng.','learn':['Time order là bản chất của dữ liệu tài chính.','Path risk quan trọng: drawdown giữa đường có thể phá chiến lược.','Gambler’s ruin cho thấy quản trị vốn sai có thể làm cháy tài khoản dù xác suất không quá xấu.'],'details':['Random walk mô tả chuyển động không dễ dự đoán bằng quá khứ đơn giản.','Martingale là khái niệm kỳ vọng tương lai bằng hiện tại dưới thông tin sẵn có.','Markov chain mô tả xác suất chuyển trạng thái, hữu ích cho credit rating hoặc market regime.'],'formula':'P(X_{t+1}=j | X_t=i, history) = P(X_{t+1}=j | X_t=i)','investor':'Backtest phải tôn trọng thứ tự thời gian. Một lệnh không chỉ có kết quả cuối, mà còn có max drawdown và thời gian chịu lỗ.','wrong':'Không random shuffle dữ liệu time series rồi tin kết quả OOS.'},
{'n':'07','cluster':'Regression','title':'Lecture 6 — Stochastic Processes continued; Regression Analysis','core':'Video bắt đầu hồi quy: dùng biến giải thích để mô hình hóa biến mục tiêu. Trong tài chính, regression giúp kiểm định feature/factor có liên hệ với return hay không.','learn':['Hồi quy tuyến tính có dạng y = Xβ + ε.','Coefficient cho biết hướng/độ mạnh quan hệ, nhưng chỉ đáng tin nếu giả định và validation ổn.','Error/residual chứa phần model chưa giải thích.'],'details':['Regression là công cụ phân tích, không phải lời cam kết dự báo.','Feature có thể bị nhiễu, outlier hoặc liên hệ giả do cùng chịu một factor.','Trong dữ liệu tài chính, cần kiểm stability và out-of-sample, không chỉ fit in-sample.'],'formula':'future_return = α + β₁x₁ + β₂x₂ + ... + ε','investor':'Dùng regression để hỏi: indicator này có giúp phân biệt nhóm future return tốt hơn không?','wrong':'Không nên thấy coefficient đẹp trong quá khứ rồi đưa ngay vào chiến lược live.'},
{'n':'08','cluster':'Rates','title':'Lecture 7 — Linear Rates, Products, and Models','core':'Video đi sâu vào thị trường lãi suất: benchmark rates, yield curve, forward rates, swaps, discount curve và hedging. Đây là lecture ứng dụng fixed income/rates.','learn':['Lãi suất là một đường cong theo kỳ hạn, không phải một con số duy nhất.','Interest rate swaps trao đổi dòng tiền fixed/floating.','Curve construction và discounting quyết định định giá sản phẩm rates.'],'details':['LIBOR/SOFR và benchmark rates là nền của nhiều hợp đồng tài chính.','Forward rate phản ánh điều kiện lãi suất hàm ý trong tương lai.','DV01/hedging giúp đo và kiểm soát exposure khi lãi suất dịch chuyển.'],'formula':'Discount factor D(t)=1/(1+r_t)^t\nSwap value ≈ PV(fixed leg) - PV(floating leg)','investor':'Rate regime ảnh hưởng cổ phiếu qua cost of capital, thanh khoản, tín dụng, định giá sector ngân hàng/BĐS/growth.','wrong':'Không xem lãi suất như biến nền khi phân tích định giá thị trường.'},
{'n':'09','cluster':'Regression diagnostics','title':'Lecture 8 — Regression Analysis continued','core':'Video đào sâu OLS diagnostics, goodness-of-fit, residuals, statistical significance và practical pitfalls. Nó nhấn mạnh rằng fit đẹp không đồng nghĩa dự báo tốt.','learn':['R² cao không đảm bảo có trading edge.','Residual analysis giúp phát hiện model sai cấu trúc.','Ý nghĩa thống kê phải đi cùng ý nghĩa kinh tế.'],'details':['Một coefficient có thể statistically significant nhưng lợi nhuận kỳ vọng quá nhỏ sau phí giao dịch.','Outlier có thể làm méo regression; multicollinearity làm hệ số khó diễn giải.','Cần kiểm mô hình trên dữ liệu ngoài mẫu và qua nhiều regime.'],'formula':'R² = 1 - SS_res/SS_tot\nt-stat = estimate / standard_error','investor':'Khi đọc một model, hãy hỏi: hiệu ứng có đủ lớn để kiếm tiền sau phí không, và có sống sót ngoài mẫu không?','wrong':'Không đánh đồng p-value đẹp với chiến lược kiếm tiền.'},
{'n':'10','cluster':'PCA','title':'Lecture 9 — Principal Component Analysis in Finance','core':'Video giảng PCA trong finance: dùng eigen decomposition để tìm các hướng biến động chính. PCA giúp giảm chiều, phát hiện factor và xử lý dữ liệu nhiều biến.','learn':['Principal components là các hướng giải thích variance lớn nhất.','Trong yield curve, PCA thường ra level/slope/curvature.','Trong cổ phiếu, PCA giúp tách market factor/sector factor/idiosyncratic risk.'],'details':['PCA sắp xếp thông tin theo mức độ giải thích variance.','Nó không tự tạo alpha, nhưng giúp hiểu cấu trúc dữ liệu và tránh trùng lặp indicator.','PCA cần diễn giải kinh tế; component toán học không phải lúc nào cũng có ý nghĩa đầu tư rõ.'],'formula':'Covariance matrix Σ → eigenvectors v_i, eigenvalues λ_i\nPC_i = X v_i','investor':'Nếu nhiều mã/indicator cùng một factor, anh đang có rủi ro tập trung ẩn.','wrong':'Không dùng PCA như hộp đen; phải hiểu factor đại diện cho điều gì.'},
{'n':'11','cluster':'Counterparty risk','title':'Lecture 10 — Counterparty Risk Optimization','core':'Video nói về exposure, default, collateral, netting, wrong-way risk và optimization. Đây là rủi ro đối tác trong finance tổ chức, nhưng tư duy áp dụng rộng cho risk concentration.','learn':['Risk không chỉ là giá đi ngược, mà còn là cấu trúc exposure.','Wrong-way risk xảy ra khi exposure tăng đúng lúc đối tác/rủi ro xấu đi.','Optimization phải có constraints thực tế.'],'details':['Collateral và netting giúp giảm exposure.','Quantile/tail risk quan trọng hơn chỉ nhìn trung bình.','Trong danh mục, rủi ro tương tự là tập trung sector, margin, thanh khoản hoặc cùng macro factor.'],'formula':'Expected loss ≈ Exposure × Probability of Default × Loss Given Default','investor':'Hãy xem danh mục như mạng exposure: ngành, beta, thanh khoản, margin, broker, macro sensitivity.','wrong':'Không nghĩ mua nhiều mã là đủ an toàn nếu tất cả cùng một nguồn rủi ro.'},
{'n':'12','cluster':'Advanced regression','title':'Lecture 11 — Regression Analysis continued','core':'Video tiếp tục các vấn đề thực hành của regression: feature selection, interactions, nonlinearities, outliers và regime dependency.','learn':['Feature có thể chỉ hoạt động trong một điều kiện thị trường.','Interaction terms giúp mô hình hóa tác động phụ thuộc regime.','Regularization/selection cần đi kèm validation.'],'details':['Ví dụ: volatility cao có thể tốt cho breakout nhưng xấu cho mean reversion.','Một biến có thể đổi dấu tác động khi market regime đổi.','Mô hình nên được kiểm theo thời gian, theo sector và theo volatility regime.'],'formula':'return ~ feature + regime + feature×regime + ε','investor':'Không hỏi feature có tốt không chung chung; hỏi nó tốt trong regime nào, horizon nào, sample size bao nhiêu.','wrong':'Không lấy kết quả toàn mẫu rồi áp cho mọi thị trường.'},
{'n':'13','cluster':'Portfolio','title':'Lecture 13 — Portfolio Management','core':'Video giảng expected return, covariance matrix, efficient frontier, diversification, constraints và quản lý danh mục thực tế.','learn':['Danh mục tối ưu phụ thuộc return kỳ vọng và covariance.','Diversification thật là giảm nguồn rủi ro chung, không chỉ tăng số mã.','Constraints thực tế như thanh khoản, tỷ trọng, mandate, drawdown rất quan trọng.'],'details':['Markowitz mean-variance là khung kinh điển: tối ưu return cho một mức risk hoặc giảm risk cho một mức return.','Efficient frontier mô tả tập danh mục không bị thống trị.','Trong thực tế, estimation error của expected return rất lớn nên risk controls thường quan trọng hơn tối ưu quá mức.'],'formula':'Portfolio return = wᵀμ\nPortfolio variance = wᵀΣw','investor':'Chọn mã chỉ là một phần. Position size và correlation quyết định danh mục sống được hay không.','wrong':'Không all-in nhiều mã cùng ngành rồi gọi là đa dạng hóa.'},
{'n':'14','cluster':'Stochastic process II','title':'Lecture 14 — Stochastic Processes II','core':'Video mở rộng quá trình ngẫu nhiên, continuous-time intuition, Brownian motion/path thinking và vai trò của đường đi trong finance.','learn':['Terminal return không đủ; path quyết định drawdown và khả năng nắm giữ.','Hitting time/time under water là metric quan trọng.','Continuous-time models là nền cho derivative pricing.'],'details':['Stochastic process II chuẩn bị cho stochastic calculus và option pricing.','Path-dependent thinking giúp hiểu vì sao cùng return cuối kỳ nhưng trải nghiệm đầu tư rất khác.','Risk phải đo trong quá trình, không chỉ tại cuối horizon.'],'formula':'Path metrics: max drawdown, max runup, time-to-target, time-under-water','investor':'Một chiến lược lãi 10% nhưng drawdown 25% giữa đường có thể không phù hợp.','wrong':'Không chỉ nhìn return cuối kỳ rồi bỏ qua đường đi.'},
{'n':'15','cluster':'Time series','title':'Lecture 12 — Time Series Analysis','core':'Video giảng stationarity, unit root, AR/MA/ARMA/ARIMA, ACF/PACF, fitting và forecast. Dữ liệu tài chính cần xử lý theo thời gian.','learn':['Price thường không stationarity; return có thể gần stationarity hơn.','AR/MA mô hình hóa phụ thuộc quá khứ và shock quá khứ.','Horizon và regime shift quyết định độ tin cậy forecast.'],'details':['ACF/PACF giúp chọn lag structure.','ARIMA thêm differencing để xử lý non-stationary series.','Cointegration/pairs trading dựa trên quan hệ cân bằng dài hạn giữa chuỗi.'],'formula':'AR(1): X_t = c + φX_{t-1}+ε_t\nMA(1): X_t = μ + ε_t + θε_{t-1}','investor':'Mọi tín hiệu phải ghi rõ horizon 5d/10d/20d/60d.','wrong':'Không validate time series bằng random split.'},
{'n':'16','cluster':'AI portfolio','title':'Lecture 18 — Data Science and AI for Portfolio Decisions','core':'Video dùng bối cảnh biomedical portfolios để nói về quyết định đầu tư với dữ liệu phức tạp, nhiều bất định và cần AI/data science hỗ trợ.','learn':['Data quality và domain knowledge quan trọng hơn model phức tạp.','AI hỗ trợ sàng lọc và xác suất, không thay thế judgment.','Portfolio decision cần kết hợp model với risk management.'],'details':['Biomedical investing có nhiều biến cố bất định, tương tự event-driven investing.','AI có thể giúp tổng hợp tín hiệu nhưng cần validation và explainability.','Adaptive thinking quan trọng vì môi trường và edge thay đổi.'],'formula':'Model usefulness = data quality × validation quality × domain relevance','investor':'Dùng AI như trợ lý phân tích xác suất/rủi ro, không như máy phán chắc chắn.','wrong':'Không train ML từ dữ liệu bẩn rồi tin kết quả vì model nghe hiện đại.'},
{'n':'17','cluster':'Volatility','title':'Lecture 19 — Volatility Modeling','core':'Video giảng realized volatility, implied volatility, volatility clustering và ARCH/GARCH intuition. Volatility là biến trung tâm của risk và option pricing.','learn':['Volatility thay đổi theo thời gian và có clustering.','Vol cao vừa tăng cơ hội hit target vừa tăng drawdown.','Volatility phải ảnh hưởng stop-loss và position sizing.'],'details':['Realized vol đo biến động thực tế từ returns.','GARCH-style models cho variance phụ thuộc shock/variance quá khứ.','Implied vol phản ánh kỳ vọng/giá thị trường option.'],'formula':'RealizedVol = std(returns)×√252\nATR% = ATR/Close\nGARCH: σ_t² = ω + αε_{t-1}² + βσ_{t-1}²','investor':'Không đặt cùng stop/size cho mã ATR 1.5% và mã ATR 5%.','wrong':'Không xem volatility cao đơn giản là tín hiệu mua hoặc bán.'},
{'n':'18','cluster':'Black-Scholes','title':'Lecture 21 — Black-Scholes Formula, Risk Neutral Valuation','core':'Video giảng option pricing, Black-Scholes PDE/formula, risk-neutral valuation và Greeks. Đây là nền cho hiểu option và chứng quyền.','learn':['Option price phụ thuộc S, K, T, r, σ.','Risk-neutral valuation là kỹ thuật pricing no-arbitrage.','Greeks đo các độ nhạy chính của option.'],'details':['Delta hedging dẫn tới Black-Scholes PDE trong khung giả định.','Theta/time decay làm option mất giá theo thời gian nếu yếu tố khác không đổi.','Volatility ảnh hưởng mạnh đến option value qua Vega.'],'formula':'C = S N(d1) - K e^{-rT} N(d2)\nInputs: S,K,T,r,σ\nGreeks: Delta, Gamma, Vega, Theta','investor':'Với CW, đúng underlying chưa đủ; cần maturity, spread, break-even, liquidity, theta, implied vol.','wrong':'Không chọn CW chỉ vì leverage cao.'},
{'n':'19','cluster':'Event markets','title':'Lecture 20 — Regulated Exchange for Event Contracts','core':'Video nói về event contracts và prediction markets: sản phẩm có payoff phụ thuộc sự kiện xảy ra hay không.','learn':['Event contracts biến xác suất sự kiện thành giá giao dịch.','Regulation/settlement rule quyết định sản phẩm có giao dịch được không.','Event risk khác với risk biến động liên tục.'],'details':['Kalshi/event exchange là ví dụ thị trường giao dịch xác suất của biến cố.','Trong cổ phiếu, event gồm KQKD, chính sách, pháp lý, nâng hạng, cổ tức, M&A.','Technical pattern có thể bị phá bởi event lớn.'],'formula':'Event price ≈ market-implied probability (sau điều chỉnh margin/cost)','investor':'Cần đánh dấu event risk riêng thay vì chỉ dùng chart/indicator.','wrong':'Không dùng backtest bình thường để bỏ qua rủi ro sự kiện.'},
{'n':'20','cluster':'Machine learning','title':'Lecture 23 — Introduction to Machine Learning','core':'Video giới thiệu supervised learning, feature, label, train/test, classification/regression, overfitting, evaluation và ML trong finance.','learn':['Label phải rõ: dự báo gì, horizon nào.','Train/test phải tách theo thời gian trong finance.','Model cần calibration và explainability.'],'details':['Classification có thể dự báo hit target; regression dự báo return.','Overfitting là rủi ro lớn vì financial data nhiễu và non-stationary.','Baseline đơn giản phải được so sánh trước khi tin model phức tạp.'],'formula':'features X → model f(X) → probability/return estimate\nCalibration: predicted 60% ≈ realized 60%','investor':'ML nên tạo xác suất/ranking, không thay thế quyết định risk.','wrong':'Không random split hoặc tối ưu toàn mẫu rồi gọi là AI thông minh.'},
{'n':'21','cluster':'Stochastic calculus','title':'Lecture 24 — Stochastic Calculus','core':'Video giới thiệu Brownian motion/Wiener process, Itô integral và Itô’s Lemma. Đây là nền toán cho derivatives và continuous-time finance.','learn':['Stochastic calculus khác calculus thường do quadratic variation.','Itô’s Lemma là chain rule cho quá trình ngẫu nhiên.','Nền này dẫn tới option pricing và SDE.'],'details':['Brownian motion mô tả nhiễu liên tục với increments normal độc lập.','Itô integral định nghĩa tích phân với process ngẫu nhiên.','Itô’s Lemma có thêm second-order term, rất quan trọng trong Black-Scholes.'],'formula':'dX = μdt + σdW\ndf = f_t dt + f_x dX + 0.5 f_xx (dX)^2','investor':'Không cần tính Itô hàng ngày, nhưng cần hiểu vì sao option/volatility models không đơn giản như đường thẳng.','wrong':'Không áp stochastic calculus vào stock picking cơ bản nếu chưa cần.'},
{'n':'22','cluster':'SDE','title':'Lecture 25 — Stochastic Calculus continued; SDE','core':'Video tiếp tục stochastic calculus với stochastic differential equations, đặc biệt mô hình dạng drift + diffusion như geometric Brownian motion.','learn':['SDE mô hình biến tài chính bằng drift và shock ngẫu nhiên.','GBM là nền Black-Scholes nhưng không hoàn hảo.','Mô phỏng scenario hữu ích hơn dự báo một đường duy nhất.'],'details':['dS = μSdt + σSdW mô tả giá có tăng trưởng kỳ vọng và nhiễu tỷ lệ với giá.','Thực tế có volatility stochastic, jumps, fat tails, regime shifts.','SDE giúp tư duy về phân phối kịch bản và path risk.'],'formula':'dS = μSdt + σSdW\nS_t = S_0 exp((μ-0.5σ²)t + σW_t)','investor':'Hãy nghĩ theo base/bull/bear/shock/gap scenario, đặc biệt khi đánh CW hoặc sản phẩm có thời gian.','wrong':'Không tin một forecast path duy nhất như tương lai chắc chắn.'},
]

css='''@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,Segoe UI,sans-serif;color:#111827}.page{width:210mm;height:297mm;padding:14mm 15mm;page-break-after:always;position:relative;overflow:hidden;background:#fff}.cover{background:radial-gradient(circle at 18% 12%,#60a5fa,transparent 25%),linear-gradient(135deg,#020617,#0f2d5c 50%,#111827);color:white;display:flex;flex-direction:column;justify-content:center}.badge{display:inline-block;width:max-content;border:1px solid rgba(255,255,255,.35);border-radius:999px;padding:7px 12px;font-size:11px;letter-spacing:.08em}.cover h1{font-size:42px;line-height:1.05;margin:18px 0}.cover h2{font-size:21px;font-weight:400;opacity:.92}.toc h1,.synth h1{font-size:28px;margin:0 0 10px;color:#0f172a}.tocgrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.tocitem{border:1px solid #e5e7eb;border-left:5px solid #2563eb;border-radius:11px;padding:7px;background:#f8fafc;font-size:10.8px}.tocitem b{display:block;color:#0f172a;margin-bottom:2px}.head{display:flex;gap:12px;align-items:center;border-bottom:2px solid #e5e7eb;padding-bottom:9px;margin-bottom:10px}.num{width:46px;height:46px;border-radius:14px;background:#1d4ed8;color:white;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:20px;flex-shrink:0}.kicker{font-size:10.5px;color:#2563eb;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.title{font-size:22px;font-weight:900;line-height:1.1;color:#0f172a}.box{border:1px solid #e5e7eb;border-radius:14px;padding:10px 11px;margin:8px 0;background:white;box-shadow:0 4px 14px rgba(15,23,42,.035)}.box h3{margin:0 0 6px;color:#1d4ed8;font-size:14px}.box p,.box li{font-size:12px;line-height:1.48}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.formula{white-space:pre-wrap;background:#0f172a;color:#bbf7d0;border-radius:12px;padding:10px;font-family:Consolas,monospace;font-size:11px;line-height:1.42}.take{background:#fffbeb;border:1px solid #fde68a;border-left:5px solid #f59e0b;border-radius:12px;padding:9px;color:#78350f;font-size:11.8px;line-height:1.45}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#0f172a;color:white;text-align:left;padding:7px}td{border:1px solid #e5e7eb;padding:7px;vertical-align:top}.footer{position:absolute;bottom:7mm;left:15mm;right:15mm;display:flex;justify-content:space-between;color:#64748b;font-size:9.5px}'''

def esc(s): return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
html=['<!doctype html><html><head><meta charset="utf-8"><title>MIT 18.642 Original Quality 50 pages</title><style>'+css+'</style></head><body>']
md=['# MIT 18.642 — PDF 50 trang chất lượng, bản gốc của Tiểu đệ\n']
html.append('<section class="page cover"><div class="badge">MIT 18.642 · 22 VIDEO TRANSCRIPTS · ORIGINAL QUALITY GUIDE</div><h1>Toán học Ứng dụng trong Tài chính</h1><h2>Tài liệu 50 trang dành cho nhà đầu tư chứng khoán — biên soạn độc lập từ transcript MIT, không lấy nội dung Claude.</h2><div class="footer"><span>Prepared by Tiểu đệ for Hòa Đại ka</span><span>50-page Original Edition</span></div></section>')
toc=''.join(f'<div class="tocitem"><b>{x["n"]}. {esc(x["title"])}</b>{esc(x["cluster"])}</div>' for x in notes)
html.append(f'<section class="page toc"><h1>Mục lục 22 video</h1><div class="tocgrid">{toc}</div><div class="footer"><span>Mục lục</span><span>22 videos</span></div></section>')
# two pages per video = 44 pages
for x in notes:
    learn=''.join(f'<li>{esc(v)}</li>' for v in x['learn'])
    details=''.join(f'<li>{esc(v)}</li>' for v in x['details'])
    html.append(f'''<section class="page"><div class="head"><div class="num">{x['n']}</div><div><div class="kicker">{esc(x['cluster'])}</div><div class="title">{esc(x['title'])}</div></div></div><div class="box"><h3>1. Video này dạy gì?</h3><p>{esc(x['core'])}</p></div><div class="box"><h3>2. Các ý phải nắm</h3><ul>{learn}</ul></div><div class="box"><h3>3. Diễn giải theo mạch bài giảng</h3><ul>{details}</ul></div><div class="footer"><span>MIT 18.642 · Video {x['n']}</span><span>Trang 1/2</span></div></section>''')
    html.append(f'''<section class="page"><div class="head"><div class="num">{x['n']}</div><div><div class="kicker">{esc(x['cluster'])} · phần học sâu</div><div class="title">{esc(x['title'])}</div></div></div><div class="grid2"><div class="box"><h3>4. Công thức / mô hình trung tâm</h3><div class="formula">{esc(x['formula'])}</div></div><div class="box"><h3>5. Nhà đầu tư cần hiểu</h3><p>{esc(x['investor'])}</p></div></div><div class="box"><h3>6. Không nên hiểu sai</h3><p>{esc(x['wrong'])}</p></div><div class="take"><b>Takeaway của video:</b> {esc(x['investor'])}</div><div class="footer"><span>MIT 18.642 · Video {x['n']}</span><span>Trang 2/2</span></div></section>''')
    md.append(f"\n## {x['n']}. {x['title']}\n\n### Video này dạy gì\n{x['core']}\n\n### Ý phải nắm\n"+'\n'.join(f"- {v}" for v in x['learn'])+"\n\n### Diễn giải\n"+'\n'.join(f"- {v}" for v in x['details'])+f"\n\n### Công thức\n```\n{x['formula']}\n```\n\n### Nhà đầu tư cần hiểu\n{x['investor']}\n\n### Không nên hiểu sai\n{x['wrong']}\n")
# 4 synthesis pages to make 50 total incl cover/toc+44+4=50
synth_pages=[
('Bảng công thức cốt lõi', [('PV / Discounting','PV=CF/(1+r)^t'),('Duration','ΔP/P≈-D×Δy'),('OLS','y=Xβ+ε'),('Portfolio variance','wᵀΣw'),('Black-Scholes inputs','S,K,T,r,σ'),('GBM','dS=μSdt+σSdW')]),
('Roadmap học 22 video', [('1','Market/Bond math'),('2','Linear algebra/Probability'),('3','Regression/PCA/Time series'),('4','Portfolio/Risk/Volatility'),('5','Options/Black-Scholes'),('6','ML/Stochastic calculus')]),
('Checklist đọc bài như nhà đầu tư', [('Horizon','Mọi nhận định phải có khung thời gian'),('Probability','Không dùng ngôn ngữ chắc chắn'),('Payoff','Biết lời/lỗ trung bình'),('Risk','Drawdown, tail risk, liquidity'),('Validation','OOS/walk-forward'),('Sizing','Tỷ trọng theo risk')]),
('Cách chuyển kiến thức thành hệ thống', [('Feature matrix','stock-date × features'),('Labels','futureReturn5d/10d/20d/60d'),('Backtest','EV, avgWin, avgLoss, profitFactor'),('Regime','bull/bear/sideway/high-vol'),('Portfolio','sector/correlation cap'),('CW','maturity, spread, break-even, theta')])]
for title, rows in synth_pages:
    tr=''.join(f'<tr><td>{esc(a)}</td><td>{esc(b)}</td></tr>' for a,b in rows)
    html.append(f'<section class="page synth"><h1>{esc(title)}</h1><div class="box"><table><thead><tr><th>Mục</th><th>Nội dung</th></tr></thead><tbody>{tr}</tbody></table></div><div class="take"><b>Ghi nhớ:</b> học MIT 18.642 là để tư duy xác suất, định giá, risk và kiểm định tốt hơn — không phải tìm một công thức thần kỳ.</div><div class="footer"><span>MIT 18.642 · Tổng hợp</span><span>50-page guide</span></div></section>')
html.append('</body></html>')
OUT_HTML.write_text('\n'.join(html),encoding='utf-8')
OUT_MD.write_text('\n'.join(md),encoding='utf-8')
with sync_playwright() as p:
    b=p.chromium.launch(headless=True)
    page=b.new_page(viewport={"width":1240,"height":1754})
    page.goto(OUT_HTML.resolve().as_uri(),wait_until='networkidle')
    page.pdf(path=str(OUT_PDF),format='A4',print_background=True,margin={"top":"0","right":"0","bottom":"0","left":"0"})
    b.close()
print(OUT_HTML, OUT_HTML.stat().st_size)
print(OUT_MD, OUT_MD.stat().st_size)
print(OUT_PDF, OUT_PDF.stat().st_size)
