from pathlib import Path
from playwright.sync_api import sync_playwright

OUT_HTML=Path('reports/MIT_18_642_Bai_Giang_Chuyen_Nghiep_Cho_Nha_Dau_Tu.html')
OUT_PDF=Path('reports/MIT_18_642_Bai_Giang_Chuyen_Nghiep_Cho_Nha_Dau_Tu.pdf')
OUT_MD=Path('reports/MIT_18_642_Bai_Giang_Chuyen_Nghiep_Cho_Nha_Dau_Tu.md')

lectures=[
('01','Mở khóa học: Tài chính định lượng là gì?','Lecture 1 Part I','Mục tiêu của video đầu tiên là đặt bối cảnh: tài chính hiện đại không chỉ dựa vào cảm giác thị trường, mà dựa vào khả năng mô hình hóa dữ liệu, rủi ro và quyết định. Giảng viên giới thiệu tinh thần của MIT 18.642: dùng toán để hiểu sản phẩm tài chính, xây mô hình, kiểm định và ứng dụng trong thực tế.','Sau bài này, anh cần hiểu: mô hình là công cụ, không phải lời tiên tri. Một nhà đầu tư giỏi không hỏi “chắc tăng không?”, mà hỏi “xác suất bao nhiêu, lời/lỗ kỳ vọng thế nào, sai khi nào?”.','Expected Value = P(thắng) × Lãi trung bình - P(thua) × Lỗ trung bình - Chi phí','Hãy xem mọi khuyến nghị đầu tư như một giả thuyết cần kiểm định.'),
('02','Bản đồ thị trường tài chính','Lecture 1 Part II','Video này giải thích các loại tài sản và thuật ngữ nền: cổ phiếu, trái phiếu, phái sinh, quỹ, hàng hóa, tiền tệ, rủi ro, lợi nhuận, thanh khoản và cấu trúc thị trường. Đây là phần giúp người học biết mình đang phân tích loại payoff nào.','Cổ phiếu là quyền sở hữu doanh nghiệp. Trái phiếu là công cụ nợ. Phái sinh là hợp đồng phụ thuộc tài sản cơ sở. Mỗi loại có cách sinh lời, rủi ro và cách định giá khác nhau.','Return phải luôn đi kèm Risk, Liquidity và Cost','Đừng dùng một cách phân tích duy nhất cho cổ phiếu, trái phiếu và chứng quyền.'),
('03','Bond Math: lãi suất là trọng lực của định giá','Lecture 1 Part III','Bài này giảng present value, discounting, yield, duration và convexity. Ý tưởng rất quan trọng: tiền trong tương lai phải được chiết khấu về hiện tại. Khi lãi suất tăng, giá trị hiện tại của dòng tiền giảm.','Dù ví dụ là trái phiếu, tư duy này áp dụng cho mọi tài sản. Cổ phiếu tăng trưởng có dòng tiền xa tương lai nên rất nhạy với lãi suất. Duration giúp đo độ nhạy đó.','PV = CF/(1+r)^t\n%ΔPrice ≈ -Duration × ΔYield','Khi lãi suất đổi, định giá thị trường đổi — kể cả doanh nghiệp chưa đổi.'),
('04','Linear Algebra: đưa thị trường về vector và ma trận','Lecture 2','Video này giảng vector, matrix, linear combination, eigenvalues/eigenvectors và vai trò của đại số tuyến tính trong tài chính. Dữ liệu thị trường nhiều chiều nên phải được biểu diễn thành ma trận.','Một cổ phiếu trong một ngày là một vector đặc trưng. Một danh mục là tổ hợp tuyến tính. Nhiều mã trong nhiều ngày tạo thành ma trận để hồi quy, PCA, tối ưu danh mục và ML.','x = [return, volatility, liquidity, factor exposure]\nX = observations × features','Muốn model tốt, trước tiên phải có ma trận dữ liệu sạch.'),
('05','Xác suất: đầu tư là trò chơi phân phối kết quả','Lecture 4','Video nối đại số tuyến tính với xác suất: random variable, distribution, expectation, variance, covariance và correlation. Đây là nền để hiểu return và risk.','Một quyết định đầu tư không tạo ra một kết quả chắc chắn; nó tạo ra một phân phối kết quả. Kỳ vọng cao nhưng tail risk lớn vẫn có thể nguy hiểm.','E[R] = Σ pᵢrᵢ\nVar(R) = E[(R-E[R])²]','Đừng chỉ nhìn lợi nhuận trung bình; hãy nhìn phân phối và rủi ro đuôi.'),
('06','Stochastic Process: giá là một đường đi ngẫu nhiên','Lecture 5','Video chuyển từ biến ngẫu nhiên sang quá trình ngẫu nhiên: random walk, martingale, Markov chain, gambler’s ruin. Giá tài sản là chuỗi biến động theo thời gian.','Điểm cuối không đủ. Đường đi quyết định drawdown, khả năng chịu đựng và nguy cơ cháy vốn. Gambler’s ruin nhắc rằng quản trị vốn sai có thể phá hủy cả chiến lược có edge.','P₀, P₁, P₂, ... Pₜ','Trong trading, path risk quan trọng không kém target.'),
('07','Regression I: kiểm định quan hệ giữa feature và return','Lecture 6','Video bắt đầu hồi quy: y = a + bx + error. Regression giúp kiểm tra biến giải thích có liên quan biến mục tiêu không.','Trong tài chính, hồi quy hữu ích để kiểm feature, nhưng không phải công thức chắc thắng. Error lớn, noise lớn, outlier và regime change làm mô hình dễ sai.','futureReturn = a + b₁feature₁ + b₂feature₂ + error','Regression trả lời “feature có thông tin không?”, không trả lời “chắc mua được không?”.'),
('08','Rates Products: đường cong lãi suất và sản phẩm rates','Lecture 7','Video đi vào SOFR/LIBOR, yield curve, forwards, swaps và discount curve. Đây là phần fixed income/rates chuyên sâu.','Đường cong lãi suất thể hiện giá vốn theo từng kỳ hạn. Các sản phẩm rates dùng curve để định giá và hedge. Với cổ phiếu, rate regime ảnh hưởng thanh khoản, định giá và sector rotation.','Discount Factor = 1/(1+rₜ)^t','Thị trường cổ phiếu không tách rời môi trường lãi suất.'),
('09','Regression II: diagnostics, residuals và overfit','Lecture 8','Video đào sâu OLS, goodness of fit, residuals, statistical significance và practical pitfalls. Một mô hình fit quá khứ tốt chưa chắc dự báo tốt.','Cần phân biệt ý nghĩa thống kê và ý nghĩa kinh tế. Một coefficient có p-value đẹp nhưng payoff quá nhỏ sau phí thì không đáng dùng.','R² cao ≠ trading edge cao','Out-of-sample quan trọng hơn vẻ đẹp in-sample.'),
('10','PCA: tìm factor chính và bớt ảo giác indicator','Lecture 9','Video giảng Principal Component Analysis trong finance. PCA tìm các hướng biến động chính trong dữ liệu bằng eigenvectors/eigenvalues.','Trong yield curve, PCA có thể cho level/slope/curvature. Trong cổ phiếu, PCA giúp thấy market factor, sector factor và loại trùng lặp indicator.','X ≈ PC1 + PC2 + ... + noise','Nhiều tín hiệu cùng một factor không phải nhiều bằng chứng độc lập.'),
('11','Counterparty Risk: rủi ro nằm trong exposure','Lecture 10','Video nói về counterparty risk, exposure, collateral, netting, wrong-way risk và optimization. Đây là tư duy risk ở cấp tổ chức.','Với nhà đầu tư cá nhân, bài học là concentration risk: quá tập trung một ngành, một broker, margin hoặc một macro factor. Risk không chỉ nằm ở từng mã riêng lẻ.','Risk = exposure × probability × loss severity','Hãy quản lý cấu trúc rủi ro, không chỉ từng lệnh.'),
('12','Regression III: feature interaction và regime','Lecture 11','Video tiếp tục hồi quy với lựa chọn biến, outlier, interaction, phi tuyến và ổn định hệ số. Một feature có thể chỉ hoạt động trong một regime.','Ví dụ volatility cao có thể tốt cho breakout nhưng xấu cho mean reversion. Vì vậy phải kiểm feature theo bull/bear/sideway/high-vol.','return ~ feature + regime + feature×regime','Feature tốt phải ổn định theo thời gian và có ý nghĩa kinh tế.'),
('13','Portfolio Management: chọn mã chỉ là nửa đầu','Lecture 13','Video giảng expected return, covariance matrix, diversification, efficient frontier và constraints thực tế.','Một danh mục nhiều mã vẫn có thể rủi ro nếu các mã cùng sector/factor. Phân bổ vốn, correlation và volatility quyết định risk thật.','Portfolio Variance = wᵀΣw','Không chỉ hỏi mua mã nào; hãy hỏi mua bao nhiêu và rủi ro danh mục là gì.'),
('14','Stochastic Processes II: path, hitting time và drawdown','Lecture 14','Video mở rộng quá trình ngẫu nhiên, nhấn mạnh continuous-time intuition và path dependence.','Một chiến lược có thể lời cuối kỳ nhưng drawdown giữa đường quá sâu. Vì thế phải đo max drawdown, time under water, time to target.','Path matters, not only terminal value','Đường đi của lệnh quyết định khả năng nắm giữ thực tế.'),
('15','Time Series: horizon và regime shift','Lecture 12','Video giảng AR, MA, ARMA, stationarity, autocorrelation và forecast. Dữ liệu tài chính là chuỗi thời gian nhiễu và dễ đổi regime.','Một tín hiệu có thể hiệu quả trong 5 ngày nhưng không hiệu quả trong 60 ngày. Không được random split khi validate time series.','Rₜ = a + bRₜ₋₁ + error','Mọi khuyến nghị phải gắn horizon rõ ràng.'),
('16','AI/Data Science cho quyết định portfolio','Lecture 18','Video dùng ví dụ biomedical portfolio để nói về AI/data science trong quyết định nhiều bất định.','Bài học chung: model tốt cần data tốt, label rõ, domain knowledge và risk management. AI không thay thế tư duy đầu tư.','Data quality > model complexity','AI là công cụ hỗ trợ xác suất, không phải máy phán chắc chắn.'),
('17','Volatility Modeling: biến động là biến sống','Lecture 19','Video giảng realized volatility, volatility clustering, ARCH/GARCH intuition và vai trò volatility trong risk/pricing.','Volatility không cố định. Sau cú sốc, vol thường duy trì cao. Vol cao vừa tạo cơ hội hit target vừa tăng drawdown.','RealizedVol = std(returns) × √252\nATR% = ATR/Close','Stop-loss và position size phải theo volatility.'),
('18','Black-Scholes: hiểu option và chứng quyền','Lecture 21','Video giảng Black-Scholes, risk-neutral valuation và option pricing. Option phụ thuộc S, K, T, r, σ.','Cổ phiếu cơ sở tăng chưa chắc CW lời nếu time decay, spread, break-even hoặc volatility bất lợi. Greeks giúp hiểu độ nhạy option.','Call = S N(d1) - K e^{-rT}N(d2)','Với CW, hướng đúng chưa đủ; thời gian và volatility quyết định lớn.'),
('19','Event Contracts: xác suất của biến cố','Lecture 20','Video nói về event contracts và sàn giao dịch sự kiện được quản lý. Payoff phụ thuộc sự kiện xảy ra hay không.','Bài này giúp nhà đầu tư hiểu các rủi ro dạng binary: KQKD, chính sách, pháp lý, cổ tức, nâng hạng. Event risk cần mô hình riêng.','Price ≈ market-implied probability of event','Không dùng technical backtest bình thường để bỏ qua event lớn.'),
('20','Machine Learning: học từ dữ liệu nhưng dễ overfit','Lecture 23','Video giới thiệu supervised learning, feature, label, train/test, classification, regression và overfitting.','Trong tài chính, ML rất dễ overfit vì dữ liệu nhiễu và regime đổi. Model nên xuất probability/ranking, không xuất chắc chắn.','Model: features → prediction/probability','ML chỉ đáng tin khi validation theo thời gian và calibration tốt.'),
('21','Stochastic Calculus I: toán cho ngẫu nhiên liên tục','Lecture 24','Video giới thiệu Brownian motion, Wiener process và Ito calculus. Đây là nền cho option pricing và continuous-time finance.','Khác calculus thường, quá trình ngẫu nhiên có quadratic variation nên cần Ito lemma để xử lý hàm của random process.','Ito Lemma: df(Xₜ,t) includes drift + diffusion + second-order term','Không cần dùng Ito hằng ngày, nhưng cần hiểu nền của option/volatility.'),
('22','SDE: mô hình hóa drift và shock','Lecture 25','Video tiếp tục stochastic calculus với stochastic differential equations. Mô hình cổ điển: dS = μSdt + σSdW.','SDE cho thấy giá gồm drift kỳ vọng và shock ngẫu nhiên. Thực tế có volatility thay đổi, jump và fat tail, nên không nên tin một đường dự báo duy nhất.','dS = μSdt + σSdW','Hãy nghĩ theo phân phối kịch bản: base, bull, bear, shock, gap risk.')]

css='''@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,Segoe UI,sans-serif;color:#111827;background:white}.slide{width:210mm;height:297mm;padding:17mm 18mm;page-break-after:always;position:relative;overflow:hidden;background:linear-gradient(180deg,#fff,#f8fafc)}.cover{background:radial-gradient(circle at 18% 10%,#60a5fa,transparent 25%),linear-gradient(135deg,#020617,#0f2d5c 50%,#111827);color:white;display:flex;flex-direction:column;justify-content:center}.badge{display:inline-block;width:max-content;border:1px solid rgba(255,255,255,.35);border-radius:999px;padding:7px 12px;font-size:11px;letter-spacing:.08em}.cover h1{font-size:42px;line-height:1.05;margin:18px 0}.cover h2{font-weight:400;font-size:21px;opacity:.92}.head{display:flex;gap:14px;align-items:center;border-bottom:2px solid #e5e7eb;padding-bottom:10px;margin-bottom:12px}.num{width:50px;height:50px;border-radius:16px;background:#2563eb;color:white;display:flex;align-items:center;justify-content:center;font-size:22px;font-weight:900;flex-shrink:0}.kicker{font-size:11px;color:#2563eb;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.title{font-size:25px;line-height:1.1;font-weight:900;color:#0f172a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{background:white;border:1px solid #e5e7eb;border-radius:18px;padding:13px;box-shadow:0 8px 22px rgba(15,23,42,.05)}.card h3{margin:0 0 8px;color:#1d4ed8;font-size:15px}.card p,.card li{font-size:13px;line-height:1.55}.formula{white-space:pre-wrap;background:#0f172a;color:#bbf7d0;border-radius:14px;padding:12px;font-family:Consolas,monospace;font-size:12px;line-height:1.45}.take{margin-top:12px;background:#fffbeb;border:1px solid #fde68a;border-left:6px solid #f59e0b;border-radius:16px;padding:12px;color:#78350f;font-size:13px;line-height:1.5}.footer{position:absolute;bottom:9mm;left:18mm;right:18mm;display:flex;justify-content:space-between;color:#64748b;font-size:10px}.tocgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.tocitem{border:1px solid #e5e7eb;border-radius:12px;padding:8px;font-size:11px;background:white}.tocitem b{display:block;color:#0f172a;margin-bottom:3px}'''

def esc(x): return x.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
slides=[]; md=['# MIT 18.642 — Bài giảng chuyên nghiệp cho nhà đầu tư\n']
slides.append('<section class="slide cover"><div class="badge">MIT 18.642 · PROFESSIONAL LECTURE NOTES · FOR INVESTORS</div><h1>Bài giảng Toán Tài chính<br/>cho Nhà đầu tư Chứng khoán</h1><h2>Biên soạn lại từ transcript 22 video: mạch lạc như thuyết trình, chỉnh chu, chuyên nghiệp, không biến chất nội dung.</h2><div class="footer"><span>Prepared by Tiểu đệ for Hòa Đại ka</span><span>Lecture Edition</span></div></section>')
toc=''.join(f'<div class="tocitem"><b>{n}. {esc(title)}</b>{esc(src)}</div>' for n,title,src,*_ in lectures)
slides.append(f'<section class="slide"><h1>Mục lục 22 bài giảng</h1><div class="tocgrid">{toc}</div><div class="footer"><span>MIT 18.642 Lecture Edition</span><span>Contents</span></div></section>')
for n,title,src,main,investor,formula,take in lectures:
    slides.append(f'''<section class="slide"><div class="head"><div class="num">{n}</div><div><div class="kicker">{esc(src)}</div><div class="title">{esc(title)}</div></div></div><div class="grid"><div class="card"><h3>1. Mở bài — video này muốn dạy gì?</h3><p>{esc(main)}</p></div><div class="card"><h3>2. Giảng cho nhà đầu tư</h3><p>{esc(investor)}</p></div><div class="card"><h3>3. Công thức / mô hình trung tâm</h3><div class="formula">{esc(formula)}</div></div><div class="card"><h3>4. Cách nghe bài này cho đúng</h3><ul><li>Hiểu khái niệm trước khi áp công thức.</li><li>Ghi rõ giả định của mô hình.</li><li>Luôn hỏi rủi ro, chi phí, xác suất và điều kiện sai.</li></ul></div></div><div class="take"><b>Takeaway:</b> {esc(take)}</div><div class="footer"><span>MIT 18.642 · {esc(src)}</span><span>Bài {n}/22</span></div></section>''')
    md.append(f'\n## {n}. {title}\nNguồn: {src}\n\n### Mở bài\n{main}\n\n### Giảng cho nhà đầu tư\n{investor}\n\n### Công thức\n```\n{formula}\n```\n\n### Takeaway\n{take}\n')
html='<!doctype html><html><head><meta charset="utf-8"><title>MIT 18.642 Lecture Notes</title><style>'+css+'</style></head><body>'+''.join(slides)+'</body></html>'
OUT_HTML.write_text(html,encoding='utf-8')
OUT_MD.write_text('\n'.join(md),encoding='utf-8')
with sync_playwright() as p:
    b=p.chromium.launch(headless=True)
    page=p.chromium.launch(headless=True).new_page(viewport={"width":1240,"height":1754})
    page.goto(OUT_HTML.resolve().as_uri(),wait_until='networkidle')
    page.pdf(path=str(OUT_PDF),format='A4',print_background=True,margin={"top":"0","right":"0","bottom":"0","left":"0"})
    page.context.browser.close()
print(OUT_HTML, OUT_HTML.stat().st_size)
print(OUT_MD, OUT_MD.stat().st_size)
print(OUT_PDF, OUT_PDF.stat().st_size)
