import json, html, shutil
from pathlib import Path
web=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap')
deploy=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\deploy_bds_legal_process\public\bds-legal-process')
final=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\FINAL_BDS_LEGAL_WEB')
data=json.loads((web/'bds_process_timeline_lawfaithful.json').read_text(encoding='utf-8'))
# inline data for single-file portability
payload=json.dumps(data,ensure_ascii=False)
html_text='''<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quy trình pháp lý BĐS</title><style>
:root{{--bg:#070b11;--panel:#0d131d;--panel2:#101824;--ink:#e8f0f8;--muted:#7f8fa1;--line:#213044;--cyan:#22d3ee;--green:#34d399;--violet:#a78bfa;--amber:#fbbf24;--red:#fb7185;--glow:#22d3ee55}}
*{{box-sizing:border-box}}body{{margin:0;background:radial-gradient(circle at 10% -10%,#164e632e,transparent 34%),radial-gradient(circle at 90% 0,#4c1d9524,transparent 30%),var(--bg);color:var(--ink);font:14px/1.55 Inter,system-ui,Segoe UI,Arial,sans-serif}}
body:before{{content:"";position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(#ffffff05 1px,transparent 1px),linear-gradient(90deg,#ffffff05 1px,transparent 1px);background-size:44px 44px;mask-image:radial-gradient(circle at 50% 0,#000 0,transparent 70%);animation:gridDrift 18s linear infinite}}@keyframes gridDrift{{to{{transform:translateY(44px)}}}}
header{{position:sticky;top:0;z-index:20;background:#070b11dd;backdrop-filter:blur(14px);border-bottom:1px solid var(--line);padding:18px clamp(16px,4vw,56px)}}.eyebrow{{display:flex;align-items:center;gap:8px;color:var(--cyan);font:800 11px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.12em}}.dot{{width:7px;height:7px;border-radius:50%;background:var(--cyan);box-shadow:0 0 18px var(--glow)}}h1{{margin:8px 0 4px;font-size:clamp(24px,4vw,42px);line-height:1.05;letter-spacing:-.04em}}.sub{{color:var(--muted);max-width:1100px}}
.wrap{{max-width:1360px;margin:0 auto;padding:22px clamp(14px,3vw,34px) 48px}}.flow{{display:grid;gap:14px;position:relative}}.node{{position:relative;border:1px solid var(--line);background:linear-gradient(180deg,#101824,#0b111a);border-radius:18px;padding:14px;box-shadow:0 20px 60px #0006;transition:.25s transform,.25s border,.25s box-shadow;overflow:hidden}}.node:before{{content:"";position:absolute;inset:-1px;background:linear-gradient(90deg,transparent,var(--cyan),transparent);opacity:0;transform:translateX(-100%);transition:.5s}}.node:hover{{transform:translateY(-2px);border-color:#35506d}}.node.active{{border-color:var(--cyan);box-shadow:0 0 0 1px #22d3ee66,0 18px 60px #22d3ee1a}}.node.active:before{{opacity:.35;transform:translateX(100%)}}
.node-head{{display:grid;grid-template-columns:72px 1fr auto;gap:12px;align-items:center;cursor:pointer}}.no{{font:900 12px ui-monospace,monospace;color:var(--cyan)}}.phase{{font:800 11px ui-monospace,monospace;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}}.ntitle{{font-size:18px;font-weight:850;margin-top:2px}}.when{{color:var(--muted);font-size:12px;margin-top:2px}}.chev{{width:34px;height:34px;border-radius:999px;border:1px solid var(--line);display:grid;place-items:center;color:var(--cyan);transition:.25s}}.node.active .chev{{transform:rotate(180deg);background:#22d3ee22}}
.connector{{width:2px;height:18px;background:linear-gradient(var(--cyan),transparent);margin-left:35px;opacity:.55}}
.detail{{display:grid;grid-template-rows:0fr;transition:grid-template-rows .38s cubic-bezier(.2,.9,.2,1);opacity:0}}.node.active .detail{{grid-template-rows:1fr;opacity:1}}.detail-inner{{overflow:hidden}}.detail-pad{{padding-top:14px;animation:fadeUp .35s ease both}}@keyframes fadeUp{{from{{opacity:0;transform:translateY(8px)}}to{{opacity:1;transform:none}}}}
.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:10px}}.card{{border:1px solid var(--line);background:#0a1018;border-radius:14px;padding:12px;min-width:0;overflow:visible}}.card h3{{margin:0 0 8px;font:900 11px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--cyan)}}.card.focus h3,.card.output h3{{color:var(--green)}}.card.steps h3,.card.deep h3{{color:var(--violet)}}.card.time h3,.card.check h3{{color:var(--amber)}}.card.risk{{background:#1a0f14;border-color:#3f1d2a}}.card.risk h3{{color:var(--red)}}.line{{padding:6px 0;border-bottom:1px dashed #ffffff0d;color:#dce7f0;overflow-wrap:anywhere}}.line:last-child{{border-bottom:0}}.muted{{color:var(--muted)}}
.proc-area{{margin-top:14px;border-top:1px solid #ffffff14;padding-top:12px}}.proc-title{{font:900 11px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin-bottom:8px}}.proc-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px}}.proc{{border:1px solid var(--line);background:#0b121b;border-radius:12px;padding:10px;cursor:pointer;transition:.2s}}.proc:hover{{border-color:var(--cyan);transform:translateY(-1px)}}.proc b{{color:var(--ink)}}.proc p{{margin:4px 0 0;color:var(--muted);font-size:12px}}
.basis{{margin-top:12px}}.basis-item{{border:1px solid var(--line);background:#0b111a;border-radius:12px;padding:10px;margin-top:8px}}.basis-top{{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:6px}}.doc{{font:900 11px ui-monospace,monospace;color:var(--cyan);background:#22d3ee18;padding:4px 7px;border-radius:7px}}.art{{font-size:12px;color:var(--muted);font-weight:700}}.abbr{{display:flex;gap:7px;flex-wrap:wrap;margin-top:16px}}.abbr span{{border:1px solid var(--line);background:#0b111a;border-radius:999px;padding:6px 9px;color:var(--muted);font-size:12px}}.abbr b{{color:var(--ink)}}
.floatbar{{position:fixed;right:18px;bottom:18px;z-index:30;display:flex;gap:8px}}.floatbar button{{border:1px solid var(--line);background:#0b111add;color:var(--ink);border-radius:999px;padding:10px 12px;backdrop-filter:blur(12px);cursor:pointer}}@media(max-width:760px){{.node-head{{grid-template-columns:52px 1fr auto}}.cards{{grid-template-columns:1fr}}}}
</style></head><body><header><div class=eyebrow><span class=dot></span>Inline flow · bấm node xổ chi tiết</div><h1>Quy trình pháp lý đầu tư dự án BĐS</h1><div class=sub>Detail nằm ngay dưới từng bước trong flow. Phần căn cứ giữ theo luật gốc, phần thực chiến tách riêng để dễ đọc.</div></header><main class=wrap><section class=flow id=flow></section><section class=card style="margin-top:18px"><h3>Chú thích viết tắt</h3><div class=abbr id=abbr></div></section></main><div class=floatbar><button onclick="openAll()">Mở tất cả</button><button onclick="closeAll()">Thu gọn</button></div><script>const DATA=__PAYLOAD__;let open=new Set([0]);
function arr(title,items,cls=''){{return `<div class="card ${{cls}}"><h3>${{title}}</h3>${{items&&items.length?items.map(x=>`<div class=line>${{x}}</div>`).join(''):'<div class="line muted">Chưa có / tùy case.</div>'}}</div>`}}
function basis(items){{if(!items||!items.length)return '';return `<div class=basis><div class=proc-title>Căn cứ & tóm tắt nội dung văn bản</div>${{items.map(b=>`<div class=basis-item><div class=basis-top><span class=doc>${{b.doc}}</span><span class=art>${{b.article}}</span></div>${{(b.points||[]).map(p=>`<div class=line>${{p}}</div>`).join('')}}</div>`).join('')}}</div>`}}
function procList(s){{return `<div class=proc-area><div class=proc-title>Thủ tục con, bấm để xem nhanh</div><div class=proc-grid>${{(s.procedures||[]).map((p,idx)=>`<div class=proc onclick="event.stopPropagation();toggleProc(${{DATA.steps.indexOf(s)}},${{idx}})"><b>${{p.title}}</b><p>${{p.summary||''}}</p><div id="proc-${{DATA.steps.indexOf(s)}}-${{idx}}" style="display:none;margin-top:8px">${{arr('Output',p.outputs)}}${{arr('Checkpoint',p.checkpoints,'check')}}${{arr('Rủi ro',p.risks,'risk')}}${{basis(p.legal_points)}}</div></div>`).join('')}}</div></div>`}}
function node(s,i){{let active=open.has(i);return `<article class="node ${{active?'active':''}"><div class=node-head onclick="toggle(${{i}})"><div><div class=no>B${{s.no}}</div><div class=phase>${{s.phase}}</div></div><div><div class=ntitle>${{s.title}}</div><div class=when>${{s.when}}</div></div><div class=chev>⌄</div></div><div class=detail><div class=detail-inner><div class=detail-pad><p class=muted>${{s.summary}}</p><div class=cards>${{arr('Việc NĐT cần chú ý',s.expert_focus||[],'focus')}}${{arr('Output thực chiến',s.expert_outputs||s.outputs,'output')}}${{arr('Checkpoint / điều kiện',s.expert_checkpoints||s.checkpoints,'check')}}${{arr('Rủi ro',s.expert_risks||s.risks,'risk')}}${{arr('Route/rẽ nhánh cần quyết',s.routes,'route')}}${{s.deep_summary?arr('Phân tích sâu',[s.deep_summary],'deep'):''}}${{arr('Điều kiện pháp lý chi tiết',s.detail_conditions||[],'check')}}${{arr('Trình tự thực hiện',s.detail_steps||[],'steps')}}${{arr('Cơ quan xử lý/tham gia',s.detail_authority||[],'auth')}}${{arr('Thời hạn / thời gian thực tế',s.detail_timeline||[],'time')}}${{arr('Lỗi thực chiến thường gặp',s.detail_mistakes||[],'risk')}}</div>${{procList(s)}}${{basis(s.legal_points)}}</div></div></div></article>${{i<DATA.steps.length-1?'<div class=connector></div>':''}}`}}
function render(){{flow.innerHTML=DATA.steps.map(node).join('');abbr.innerHTML=Object.entries(DATA.abbreviations||{{}}).map(([k,v])=>`<span><b>${{k}}</b>: ${{v}}</span>`).join('')}}function toggle(i){{open.has(i)?open.delete(i):open.add(i);render();setTimeout(()=>document.querySelectorAll('.node')[i]?.scrollIntoView({{behavior:'smooth',block:'center'}}),60)}}function toggleProc(i,j){{let el=document.getElementById(`proc-${{i}}-${{j}}`);if(el)el.style.display=el.style.display==='none'?'block':'none'}}function openAll(){{open=new Set(DATA.steps.map((_,i)=>i));render()}}function closeAll(){{open=new Set();render()}}render();</script></body></html>'''.replace('__PAYLOAD__', payload)
(web/'bds_inline_flow.html').write_text(html_text,encoding='utf-8')
(deploy/'bds_inline_flow.html').write_text(html_text,encoding='utf-8')
(deploy/'index.html').write_text(html_text,encoding='utf-8')
final.mkdir(parents=True,exist_ok=True)
(final/'index.html').write_text(html_text,encoding='utf-8')
(final/'bds_inline_flow.html').write_text(html_text,encoding='utf-8')
shutil.copy2(web/'bds_process_timeline_lawfaithful.json', final/'bds_process_timeline_lawfaithful.json')
print('built inline flow', web/'bds_inline_flow.html')

