import json, pathlib
web=pathlib.Path(r"C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap")
v5=json.loads((web/'legal_project_flow_v5.json').read_text(encoding='utf-8'))
N={n['id']:n for n in v5['nodes']}
order=['gate0','gate1','gate2','gate3','gate4','gate5','gate6','gate7']
step_meta={
'gate0':{'no':'01','phase':'Tiền khả thi','when':'Làm đầu tiên, trước khi đặt cọc/mua đất/góp vốn lớn','must':'Kết luận quỹ đất có thể phát triển và chọn route pháp lý sơ bộ.'},
'gate1':{'no':'02','phase':'Quy hoạch','when':'Sau khi thấy đất có cửa đi; trước CTCTĐT/đấu thầu/thiết kế','must':'Khóa quy hoạch, chỉ tiêu, sản phẩm dự kiến và khả năng hiệu quả tài chính.'},
'gate2':{'no':'03','phase':'Chủ trương & NĐT','when':'Sau khi route đất/quy hoạch sơ bộ rõ; trước giao đất/xây dựng','must':'Có chủ trương đầu tư hoặc cơ sở lựa chọn/công nhận nhà đầu tư.'},
'gate3':{'no':'04','phase':'Đất đai','when':'Sau khi có NĐT/CTCTĐT; trước triển khai xây dựng và mở bán','must':'Hoàn tất giao/thuê/chuyển mục đích, GPMB, nghĩa vụ tài chính đất.'},
'gate4':{'no':'05','phase':'Điều kiện kỹ thuật','when':'Sau đất/quy hoạch/chủ trương; trước khởi công','must':'Đủ thiết kế, GPXD nếu cần, môi trường, PCCC, hạ tầng đấu nối.'},
'gate5':{'no':'06','phase':'Thi công','when':'Sau khi đủ điều kiện khởi công; trước bán/bàn giao theo từng mốc','must':'Thi công đúng phép, nghiệm thu móng/hạ tầng/công trình theo tiến độ.'},
'gate6':{'no':'07','phase':'Kinh doanh','when':'Chỉ sau khi đủ điều kiện pháp lý sản phẩm; không được làm sớm trá hình','must':'Đủ điều kiện mở bán/huy động vốn/chuyển nhượng dự án.'},
'gate7':{'no':'08','phase':'Bàn giao & hậu kiểm','when':'Sau nghiệm thu, thu tiền cuối kỳ và bàn giao cho khách hàng/cư dân','must':'Bàn giao hợp lệ, cấp sổ, vận hành/ban quản trị/quỹ bảo trì.'}
}
route_notes={
'gate0':['Nếu đất Nhà nước quản lý/đất sạch: kiểm tra khả năng đấu giá QSDĐ.','Nếu dự án có sử dụng đất thuộc Điều 126 Luật Đất đai hoặc luật chuyên ngành: kiểm tra đấu thầu NĐT.','Nếu NĐT tự có/nhận QSDĐ hợp pháp và không đề xuất Nhà nước thu hồi: kiểm tra chấp thuận NĐT/CTCTĐT.'],
'gate2':['Route A: chấp thuận chủ trương trước rồi lựa chọn/công nhận NĐT.','Route B: đấu thầu lựa chọn NĐT theo NĐ 274/2026.','Route C: đấu giá QSDĐ rồi triển khai thủ tục đầu tư/đất đai sau trúng đấu giá.'],
'gate6':['Mở bán nhà ở hình thành trong tương lai chỉ khi đủ điều kiện pháp lý, xây dựng, bảo lãnh nếu thuộc diện.','Không dùng booking/đặt cọc để huy động vốn khi chưa đủ điều kiện kinh doanh.']
}
steps=[]
for gid in order:
    g=N[gid]; children=[N[c] for c in g.get('children',[]) if c in N]
    steps.append({**step_meta[gid], 'id':gid,'title':g['title'],'summary':g.get('summary',''),'outputs':g.get('outputs',[]),'risks':g.get('risks',[]),'checkpoints':g.get('checkpoints',[]),'routes':route_notes.get(gid,[]),'procedures':[{'id':c['id'],'title':c['title'],'summary':c.get('summary',''),'outputs':c.get('outputs',[]),'risks':c.get('risks',[]),'checkpoints':c.get('checkpoints',[]),'legal_basis':c.get('legal_basis',[])[:6]} for c in children], 'legal_basis':g.get('legal_basis',[])[:8]})
out={'title':'Quy trình pháp lý đầu tư dự án BĐS', 'subtitle':'Sắp xếp lại thành timeline: bước nào làm trước, bước nào làm sau, chỗ nào rẽ nhánh. Bấm từng bước để xem thủ tục con và căn cứ.', 'version':'process-timeline-v1','steps':steps}
(web/'bds_process_timeline.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
html=r'''<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quy trình pháp lý BĐS</title><style>
:root{--bg:#f4efe7;--paper:#fffaf2;--ink:#152019;--muted:#667166;--line:#d7cbb9;--green:#1f513d;--gold:#a97a24;--red:#96382e;--blue:#244d76}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 Inter,system-ui,Segoe UI,Arial}header{padding:26px clamp(18px,4vw,56px);background:#fbf7ef;border-bottom:1px solid var(--line)}h1{font-size:clamp(30px,4.5vw,54px);line-height:1;margin:0 0 10px;letter-spacing:-.045em}.sub{max-width:1100px;color:var(--muted);font-size:17px}.wrap{display:grid;grid-template-columns:430px 1fr;gap:22px;padding:22px clamp(18px,4vw,56px)}aside{position:sticky;top:14px;align-self:start;max-height:calc(100vh - 28px);overflow:auto}.timeline{border-left:3px solid var(--line);padding-left:18px}.stepbtn{position:relative;display:block;width:100%;text-align:left;margin:0 0 12px;border:1px solid var(--line);background:#fffaf5;border-radius:18px;padding:13px 14px;cursor:pointer}.stepbtn:before{content:"";position:absolute;left:-29px;top:20px;width:16px;height:16px;border-radius:50%;background:white;border:3px solid var(--gold)}.stepbtn.active{background:var(--green);color:white}.stepbtn.active .meta{color:#dfeae3}.no{font-weight:900;color:var(--gold);font-size:13px;letter-spacing:.08em}.stepbtn.active .no{color:#f3cf83}.name{font-weight:850;font-size:16px}.meta{color:var(--muted);font-size:13px}.card{background:var(--paper);border:1px solid var(--line);border-radius:24px;padding:22px;box-shadow:0 12px 28px #0000000b}.crumb{color:var(--gold);font-weight:900;text-transform:uppercase;font-size:12px;letter-spacing:.08em}h2{font-size:clamp(26px,3vw,42px);line-height:1.08;margin:8px 0}.lead{font-size:19px;font-weight:650}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.box{background:#fffdf8;border:1px solid var(--line);border-radius:16px;padding:14px;margin-top:13px}.box h3{margin:0 0 8px;color:var(--green);font-size:13px;text-transform:uppercase;letter-spacing:.06em}.risk{border-color:#e3b9ae;background:#fff7f4}.risk h3{color:var(--red)}ul{margin:0;padding-left:18px}.proc{border:1px solid var(--line);border-radius:16px;background:white;margin:10px 0;padding:13px}.proc summary{cursor:pointer;font-weight:850;color:var(--blue)}.quote{border-left:3px solid var(--gold);padding-left:10px;margin:9px 0;color:#313b34}.small{font-size:13px;color:var(--muted)}.arrow{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:14px 0}.pill{border:1px solid var(--line);border-radius:999px;background:white;padding:7px 10px;font-weight:700;color:var(--green)}@media(max-width:980px){.wrap{grid-template-columns:1fr}aside{position:relative;max-height:none}.grid{grid-template-columns:1fr}}
</style></head><body><header><div class=crumb>Process timeline / bước trước bước sau</div><h1 id=title></h1><div class=sub id=sub></div></header><div class=wrap><aside><div class=timeline id=timeline></div></aside><main><section class=card id=detail></section></main></div><script>
let DATA,active=0;fetch('bds_process_timeline.json').then(r=>r.json()).then(d=>{DATA=d;init()});function init(){title.textContent=DATA.title;sub.textContent=DATA.subtitle;timeline.innerHTML=DATA.steps.map((s,i)=>`<button class="stepbtn ${i==0?'active':''}" onclick="show(${i})"><div class=no>BƯỚC ${s.no} · ${s.phase}</div><div class=name>${s.title.replace(/^Gate \d+ — /,'')}</div><div class=meta>${s.when}</div></button>`).join('');show(0)}
function arr(t,a,cls=''){return `<div class="box ${cls}"><h3>${t}</h3>${a&&a.length?`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class=small>Chưa có / tùy case.</p>'}</div>`}
function basis(lb){if(!lb||!lb.length)return '<p class=small>Chưa gắn căn cứ ở mục này.</p>';return lb.map(b=>`<div class=quote><b>${b.article||''}</b><div class=small>${b.source_file||''}</div><div>${(b.summary||b.quote||'').slice(0,520)}${(b.summary||b.quote||'').length>520?'…':''}</div></div>`).join('')}
function proc(p){return `<details class=proc><summary>${p.title}</summary><p>${p.summary||''}</p>${arr('Output',p.outputs)}${arr('Checkpoint',p.checkpoints)}${arr('Rủi ro',p.risks,'risk')}<div class=box><h3>Căn cứ/tóm tắt văn bản</h3>${basis(p.legal_basis)}</div></details>`}
function show(i){active=i;document.querySelectorAll('.stepbtn').forEach((b,j)=>b.classList.toggle('active',j==i));let s=DATA.steps[i];let prev=DATA.steps[i-1],next=DATA.steps[i+1];detail.innerHTML=`<div class=crumb>BƯỚC ${s.no} · ${s.phase}</div><h2>${s.title}</h2><p class=lead>${s.summary}</p><div class=arrow>${prev?`<span class=pill>Trước: ${prev.phase}</span>`:''}<span class=pill>Đang làm: ${s.phase}</span>${next?`<span class=pill>Sau: ${next.phase}</span>`:''}</div><div class=grid>${arr('Làm khi nào?', [s.when])}${arr('Mục tiêu bắt buộc', [s.must])}${arr('Output của bước',s.outputs)}${arr('Rủi ro chính',s.risks,'risk')}</div>${arr('Route/rẽ nhánh cần quyết',s.routes)}<div class=box><h3>Thủ tục con trong bước này</h3>${s.procedures.map(proc).join('')}</div><div class=box><h3>Căn cứ/tóm tắt văn bản cấp bước</h3>${basis(s.legal_basis)}</div>`}
</script></body></html>'''
(web/'bds_process_timeline.html').write_text(html,encoding='utf-8')
print('steps',len(steps),'procedures',sum(len(s['procedures']) for s in steps))
