import json, pathlib
base=pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS')
out=base/'web_mindmap/tpre_legal_deep_modules.json'
def mod(title, items): return {'title':title,'items':items}
data={
'I':[mod('Pháp lý chuyên sâu cần kiểm tra',['Chuỗi quyền sử dụng đất và quyền định đoạt của bên bán/chủ dự án.','Quy hoạch/kế hoạch sử dụng đất/kế hoạch phát triển nhà ở/chương trình phát triển đô thị.','Thế chấp, tranh chấp, hạn chế chuyển nhượng, nghĩa vụ tài chính đất còn tồn.','Route đầu tư khả thi: tự có đất, nhận QSDĐ, M&A, đấu giá, đấu thầu, chấp thuận NĐT.']),mod('Cách thực hiện',['Lập legal DD index theo từng tài liệu và từng rủi ro.','Gắn mỗi rủi ro với điều kiện xử lý trong term sheet/SPA.','Lập ma trận route pháp lý + timeline + chi phí + xác suất thành công.','Chốt điều kiện tiên quyết trước khi đặt cọc hoặc chi tiền lớn.'])],
'II':[mod('Pháp lý GPMB/thu mua đất',['Phân biệt Nhà nước thu hồi đất và tự thỏa thuận nhận QSDĐ.','Kiểm tra đất công/xen kẹt, hạ tầng hiện hữu, kênh rạch, mồ mả, công trình tôn giáo.','Mỗi khoản chi GPMB phải có chứng từ/căn cứ nếu muốn xét khấu trừ hoặc ghi nhận tài chính đất.']),mod('Cách thực hiện',['Lập landowner matrix theo thửa/chủ/diện tích/loại đất/GCN/tài sản/trạng thái.','Lập ngân sách bồi thường, hỗ trợ, TĐC, chi phí phát sinh và điều kiện giải ngân.','Theo dõi từng hộ/thửa: tiếp xúc, đàm phán, ký, chi trả, bàn giao, chỉnh lý.'])],
'III':[mod('Căn cứ và route lựa chọn NĐT',['Luật Đầu tư: CTCTĐT/CTNĐT, đề xuất dự án, thẩm quyền, điều kiện.','Luật Đất đai/NĐ 102: đấu giá QSDĐ, đấu thầu dự án có sử dụng đất, thỏa thuận nhận QSDĐ.','Luật Đấu thầu/NĐ 115 nếu dự án thuộc diện đấu thầu lựa chọn NĐT.','Ký quỹ/bảo đảm thực hiện dự án phải đưa vào dòng tiền và tiến độ.']),mod('Cách thực hiện',['Dựng bảng so sánh route: điều kiện, hồ sơ, thẩm quyền, thời gian, rủi ro.','Chuẩn bị hồ sơ năng lực tài chính: vốn chủ sở hữu, BCTC, cam kết tín dụng/bảo lãnh nếu có.','Khóa nội dung CTCTĐT: mục tiêu, quy mô, đất, tổng vốn, tiến độ, phân kỳ.'])],
'IV':[mod('Pháp lý quy hoạch chuyên sâu',['QHCT/tổng mặt bằng phải có thuyết minh, bản vẽ, chỉ tiêu, quy định quản lý theo đồ án.','Chỉ tiêu phải đủ: đất, dân số, tầng cao, mật độ, hệ số sử dụng đất, HTKT, HTXH, PCCC/giao thông.','Output quy hoạch phải dùng được cho thiết kế, giao đất, GPXD, định giá đất, bán hàng, cấp GCN.']),mod('Cách thực hiện',['Rà quy hoạch cấp trên và chỉ tiêu đầu vào.','Kiểm tra ngược từ sản phẩm bán hàng, PCCC, giao thông, cấp sổ.','Mọi thay đổi chỉ tiêu phải đánh giá ảnh hưởng tới đất, nghĩa vụ tài chính, GPXD, HĐMB.'])],
'V':[mod('Pháp lý tài chính đất',['Luật Đất đai 2024: căn cứ giao/thuê/chuyển mục đích, bảng giá đất, giá đất cụ thể.','NĐ 102/2024: trình tự thủ tục đất và route đất.','NĐ 103/2024: tiền sử dụng đất, tiền thuê đất, miễn giảm, khấu trừ, thông báo nghĩa vụ.','NĐ 87/2025: giảm tiền thuê đất năm 2024 nếu thuộc trường hợp thuê đất trả tiền hằng năm.']),mod('Cách tính/workbook',['Tách từng phần diện tích theo loại đất và hình thức sử dụng.','Workbook gồm: diện tích, loại đất trước/sau, thời hạn, giá đất/bảng giá/giá cụ thể, GPMB được trừ, miễn giảm, gross payable, deduction, net payable.','Không dùng số tài chính nếu chưa khóa được diện tích, mục đích sử dụng và căn cứ giá.'])],
'VI':[mod('Pháp lý thiết kế - GPXD - PCCC - môi trường',['Luật Xây dựng/NĐ quản lý dự án: BCNCKT, TKCS, TKKT, TKBVTC, thẩm định, GPXD, khởi công.','PCCC: góp ý giải pháp, thẩm duyệt thiết kế, nghiệm thu PCCC trước vận hành.','Môi trường: ĐTM, GPMT, vận hành thử nghiệm công trình xử lý chất thải.','Đấu nối hạ tầng là nhóm pháp lý kỹ thuật riêng: giao thông, điện, nước, thoát nước, XLNT.']),mod('Cách thực hiện',['Lập ma trận giấy phép kỹ thuật theo từng hạng mục.','Xác định miễn/không miễn GPXD, cơ quan cấp, điều kiện khởi công.','PCCC và môi trường phải chạy từ thiết kế cơ sở, không để sát nghiệm thu.'])],
'VII':[mod('Pháp lý thi công',['Thi công phải theo GPXD/TKBVTC và điều kiện khởi công.','Thay đổi thiết kế phải phân loại: nội bộ, thẩm tra/thẩm định lại, điều chỉnh GPXD/QHCT/PCCC.','Hồ sơ nghiệm thu giai đoạn có thể là điều kiện bán BĐS HTTTL.']),mod('Cách thực hiện',['Lập ma trận phân kỳ thi công: san nền, HTKT, phần ngầm, phần thân, hoàn thiện, cảnh quan.','Hồ sơ chất lượng realtime: nhật ký, nghiệm thu vật liệu, nghiệm thu công việc, ảnh, bản vẽ hoàn công.'])],
'VIII':[mod('Pháp lý kinh doanh BĐS',['Luật KDBĐS 2023: điều kiện đưa BĐS vào kinh doanh, công khai thông tin, BĐS hình thành trong tương lai.','NĐ 96/2024: hồ sơ, điều kiện, công khai, thông báo đủ điều kiện bán.','Bảo lãnh nhà ở HTTTL phải kiểm đến chứng thư/cam kết cho người mua.','HĐMB phải theo mẫu/nội dung bắt buộc và khớp trạng thái pháp lý.']),mod('Cách thực hiện',['Lập ma trận điều kiện bán theo từng loại sản phẩm.','Kiểm soát sales script/booking/giữ chỗ/đặt cọc để tránh huy động vốn trái luật.','Lưu bằng chứng công khai thông tin, văn bản đủ điều kiện, bảo lãnh, HĐMB mẫu.'])],
'IX':[mod('Pháp lý nghiệm thu hoàn thành',['NĐ quản lý chất lượng công trình: nghiệm thu, kiểm tra công tác nghiệm thu, hoàn thành đưa vào sử dụng.','PCCC, GPMT/vận hành thử, đấu nối hạ tầng là điều kiện chéo không được thiếu.','Văn bản kiểm tra nghiệm thu là input cho bàn giao, vận hành và cấp GCN.']),mod('Cách thực hiện',['Lập ma trận nghiệm thu theo hạng mục: HTKT, HTXH, nhà ở, PCCC, môi trường, đấu nối.','Soát sai khác hiện trường so với GPXD/TKBVTC/QHCT trước khi mời CQNN.'])],
'X':[mod('Pháp lý cấp GCN/bàn giao',['NĐ 101/2024: đăng ký đất đai, cấp GCN dự án/người mua, phiếu chuyển thông tin nghĩa vụ tài chính.','Điều kiện gồm hoàn công/nghiệm thu, nghĩa vụ tài chính, bản vẽ sơ đồ, giải chấp, hồ sơ khách hàng.','Tách cấp GCN dự án và cấp GCN từng khách hàng.']),mod('Cách thực hiện',['Dashboard từng căn/lô: đủ hồ sơ, đang nộp, bổ sung, đã có GCN, đã bàn giao GCN.','Theo dõi phiếu chuyển thuế, giải chấp, sai diện tích/sơ đồ, giấy hẹn, yêu cầu bổ sung.'])],
'XI':[mod('Pháp lý hậu bàn giao',['Hồ sơ bảo hành, vận hành, bàn giao tài sản/hạ tầng và xử lý khiếu nại cần lưu như hồ sơ pháp lý hậu dự án.','Nghĩa vụ bảo hành/bảo trì, phần chung-riêng, bàn giao BQL/ban quản trị phải kiểm soát để giảm tranh chấp.']),mod('Cách thực hiện',['Lập danh mục tài sản/hồ sơ vận hành.','Mỗi lỗi bảo hành có mã, ảnh, vị trí, nguyên nhân, owner, deadline, trạng thái.','Chỉ đóng dự án pháp lý khi cấp GCN cơ bản, bàn giao hạ tầng, xử lý tồn tại và hồ sơ lưu trữ đầy đủ.'])]
}
out.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
for target in [base/'FINAL_BDS_LEGAL_WEB/tpre_legal_deep_modules.json', pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\deploy_bds_legal_process\public\bds-legal-process\tpre_legal_deep_modules.json')]:
    target.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print(out)
