import json, pathlib, textwrap
web=pathlib.Path(r"C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap")
data={
  "version":"investment-focused-2026-07-09",
  "title":"Luật đầu tư dự án BĐS — bản trọng tâm",
  "subtitle":"Đi theo quyết định đầu tư: được làm không, chọn NĐT thế nào, đất sạch chưa, được bán/huy động chưa.",
  "principles":[
    "Mặt chính chỉ hiển thị ý cần quyết; căn cứ pháp lý nằm trong drill-down.",
    "Chỉ dùng nguồn anh cung cấp/local + Additional; bỏ file không liên quan trực tiếp đầu tư BĐS.",
    "Không tóm tắt dài: mỗi card tối đa vài dòng, tập trung điều kiện/rủi ro/output."
  ],
  "sources_used":[
    {"name":"Nghị định 274/2026/NĐ-CP", "file":"Additional/274_2026_ND-CP_690308.doc", "status":"đã extract sạch phần đầu; TVPL ghi đang cập nhật full Word", "role":"xác định tuyến đấu thầu lựa chọn nhà đầu tư dự án đầu tư kinh doanh"},
    {"name":"Nghị định 94/2024/NĐ-CP", "file":"Additional/94_2024_ND-CP_619415.doc", "status":"file .doc nhị phân, chưa convert sạch bằng CLI; cần dùng Word/LibreOffice nếu muốn trích đầy đủ", "role":"nguồn nhà ở cần kiểm tra thêm"},
    {"name":"QD 50/2023/UBND", "file":"Additional/50_2023_QD-UBND_580638.doc", "status":"đã extract; chỉ dùng nếu liên quan địa phương/quỹ đất", "role":"tham chiếu phụ"}
  ],
  "gates":[
    {"id":"g0","title":"0. Lọc quỹ đất","investor_question":"Khu đất này có đi được thành dự án thương mại không?","decision":["Xác định đất do Nhà nước thu hồi/giao/cho thuê hay tự thỏa thuận nhận QSDĐ.","Check quy hoạch, kế hoạch sử dụng đất, danh mục dự án/khu đất đấu thầu/đấu giá.","Loại sớm đất vướng mục đích sử dụng, quốc phòng/an ninh, di sản, hành lang bảo vệ, dân cư chưa GPMB."],"output":"Bản đồ tuyến tiếp cận đất: đấu giá / đấu thầu NĐT / chấp thuận NĐT / tự thỏa thuận.","risk":"Sai tuyến đất từ đầu làm hỏng toàn bộ deal: không được giao đất, không được công nhận chủ đầu tư, không ra được pháp lý bán hàng.","citations":["Luật Đất đai 2024: Điều 79, 126", "NĐ 274/2026/NĐ-CP: Điều 4"]},
    {"id":"g1","title":"1. Chọn tuyến nhà đầu tư","investor_question":"Dự án phải đấu thầu lựa chọn NĐT, đấu giá đất, hay chấp thuận NĐT?","decision":["Nếu thuộc dự án có sử dụng đất theo Điều 126 Luật Đất đai: kiểm tra bắt buộc đấu thầu.","Nếu có đất sạch Nhà nước quản lý đủ điều kiện đấu giá: nghiêng về đấu giá QSDĐ.","Nếu nhà đầu tư đang có/nhận quyền sử dụng đất hợp pháp và không đề xuất Nhà nước thu hồi đất: xem tuyến chấp thuận chủ trương đồng thời chấp thuận NĐT."],"output":"Route memo: tender / auction / direct investor approval.","risk":"Nhầm giữa đấu thầu NĐT và đấu giá đất tạo rủi ro vô hiệu quy trình, chậm dự án, mất quyền ưu tiên.","citations":["NĐ 274/2026/NĐ-CP: Điều 4 khoản 1–4", "Luật Đấu thầu 2023/sửa đổi: nhóm quy định lựa chọn NĐT", "Luật Đất đai 2024: Điều 126"]},
    {"id":"g2","title":"2. Chấp thuận chủ trương / thông tin dự án","investor_question":"Cơ quan nào duyệt chủ trương và điều kiện công bố dự án là gì?","decision":["Xác định thẩm quyền: Quốc hội/Thủ tướng/UBND tỉnh theo quy mô, đất, dân số, ngành nghề.","Với dự án không thuộc diện chấp thuận chủ trương nhưng phải lựa chọn NĐT: cần công bố thông tin dự án theo NĐ 274.","Chốt sơ bộ tổng vốn đầu tư gồm chi phí dự án + bồi thường hỗ trợ tái định cư + chi phí khác."],"output":"Quyết định chủ trương hoặc bộ thông tin dự án đủ để mời quan tâm/đấu thầu.","risk":"Sơ bộ vốn/chi phí đất sai làm lệch năng lực tài chính, tiêu chuẩn đánh giá, hiệu quả IRR.","citations":["NĐ 274/2026/NĐ-CP: Điều 1, Điều 3 khoản 6", "Luật Đầu tư hiện hành: thẩm quyền chấp thuận chủ trương"]},
    {"id":"g3","title":"3. Đấu thầu lựa chọn NĐT","investor_question":"Nếu phải đấu thầu, nhà đầu tư cần thắng bằng gì?","decision":["Chuẩn bị năng lực tài chính, kinh nghiệm dự án tương tự, phương án kỹ thuật/quy hoạch, tiến độ, hiệu quả sử dụng đất.","Theo dõi mời quan tâm, HSMT/HSYC, tiêu chuẩn đánh giá, bảo đảm cạnh tranh, ưu đãi nếu có.","Kiểm tra điều kiện quỹ đất trước khi bỏ chi phí lớn: NĐ 274 yêu cầu quỹ đất dự kiến phải đáp ứng điều kiện."],"output":"Kết quả lựa chọn NĐT + hợp đồng dự án đầu tư có sử dụng đất.","risk":"Không chứng minh được năng lực/kinh nghiệm hoặc quỹ đất chưa đủ điều kiện → rớt thầu/dừng thầu.","citations":["NĐ 274/2026/NĐ-CP: Điều 1 khoản 1, Điều 4", "NĐ 274/2026/NĐ-CP: quy định về phương pháp/tiêu chuẩn đánh giá HSDT và hợp đồng dự án có sử dụng đất"]},
    {"id":"g4","title":"4. Hoàn tất đất đai","investor_question":"Sau khi được chọn, bao giờ đất chuyển thành quyền triển khai thật?","decision":["Thực hiện bồi thường, hỗ trợ, tái định cư/GPMB nếu Nhà nước thu hồi đất.","Hoàn tất quyết định giao đất/cho thuê đất/chuyển mục đích và nghĩa vụ tài chính đất.","Kiểm tra điều kiện cấp GCN/đăng ký biến động trước khi huy động vốn hoặc thế chấp."],"output":"Quyết định đất + nghĩa vụ tài chính + quyền sử dụng đất đủ điều kiện triển khai.","risk":"Tiền sử dụng đất/tiền thuê đất và GPMB là điểm nghẽn lớn nhất của dòng tiền dự án.","citations":["Luật Đất đai 2024", "NĐ 102/2024/NĐ-CP", "NĐ 103/2024/NĐ-CP", "NĐ 71/2024/NĐ-CP"]},
    {"id":"g5","title":"5. Pháp lý xây dựng","investor_question":"Đã đủ điều kiện khởi công chưa?","decision":["Chốt quy hoạch chi tiết/chỉ tiêu kiến trúc, thiết kế, thẩm định, GPXD nếu thuộc diện phải có.","Rà ĐTM/GPMT, PCCC, đấu nối hạ tầng, giao thông, cấp thoát nước.","Không khởi công khi thiếu điều kiện khởi công hoặc chưa xong thủ tục môi trường/PCCC bắt buộc."],"output":"Bộ điều kiện khởi công: thiết kế/thẩm định/GPXD/PCCC/môi trường.","risk":"Khởi công sai điều kiện kéo theo phạt, đình chỉ, không nghiệm thu được, ảnh hưởng mở bán.","citations":["Luật Xây dựng và nghị định quản lý dự án", "Luật BVMT/NĐ 08/2022", "Luật PCCC/NĐ 136/2020, NĐ 50/2024"]},
    {"id":"g6","title":"6. Bán hàng / huy động vốn","investor_question":"Khi nào được bán, đặt cọc, huy động vốn?","decision":["Chỉ mở bán/huy động khi dự án và sản phẩm đủ điều kiện theo Luật KDBĐS/Nhà ở.","Với nhà ở hình thành trong tương lai: cần điều kiện pháp lý dự án, giấy tờ đất, xây dựng, bảo lãnh ngân hàng nếu thuộc diện.","Tách rõ booking/đặt cọc/giữ chỗ với giao dịch mua bán/huy động vốn để tránh huy động trái phép."],"output":"Thông báo đủ điều kiện bán/hồ sơ bán hàng + bảo lãnh + hợp đồng mẫu.","risk":"Huy động vốn sai thời điểm là rủi ro hình sự/dân sự/truyền thông lớn nhất ở phase thương mại.","citations":["Luật Kinh doanh BĐS 2023", "Luật Nhà ở 2023", "NĐ 96/2024/NĐ-CP", "TT 49/2024/TT-NHNN"]},
    {"id":"g7","title":"7. Bàn giao – sổ – vận hành","investor_question":"Dự án kết thúc pháp lý khi nào?","decision":["Nghiệm thu công trình/hạ tầng đủ điều kiện bàn giao.","Hoàn công, đăng ký tài sản, cấp GCN cho người mua.","Thiết lập quản lý vận hành, quỹ bảo trì, bàn giao hồ sơ nhà chung cư nếu có."],"output":"Bàn giao hợp lệ + cấp sổ + vận hành ổn định.","risk":"Không cấp sổ/bàn giao thiếu nghiệm thu gây tồn kho pháp lý và tranh chấp cư dân.","citations":["Luật Đất đai 2024", "Luật Nhà ở 2023", "Luật Xây dựng", "NĐ 95/2024 hoặc NĐ hướng dẫn nhà ở cần verify thêm từ file 94/2024"]}
  ]
}
(web/'investment_bds_flow.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
html='''<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Luật đầu tư dự án BĐS</title><style>
:root{--bg:#f7f3eb;--ink:#17211b;--muted:#69736c;--line:#d8cfbf;--card:#fffaf1;--accent:#245b45;--red:#9a3c2e;--gold:#b8872e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 Inter,system-ui,Segoe UI,Arial}header{padding:28px clamp(18px,4vw,56px);border-bottom:1px solid var(--line);background:#fbf8f1}h1{font-size:clamp(26px,4vw,48px);line-height:1.05;margin:0 0 10px;letter-spacing:-.04em}.sub{max-width:920px;color:var(--muted);font-size:18px}.wrap{display:grid;grid-template-columns:320px 1fr;gap:24px;padding:24px clamp(18px,4vw,56px)}nav{position:sticky;top:16px;align-self:start;border:1px solid var(--line);background:#fffaf5;border-radius:18px;padding:12px}.navbtn{width:100%;text-align:left;border:0;background:transparent;padding:12px;border-radius:12px;color:var(--muted);cursor:pointer}.navbtn.active{background:var(--accent);color:white}.card{background:var(--card);border:1px solid var(--line);border-radius:24px;padding:24px;box-shadow:0 12px 30px #0000000c}.eyebrow{color:var(--gold);font-weight:700;text-transform:uppercase;font-size:12px;letter-spacing:.08em}h2{font-size:32px;line-height:1.1;margin:6px 0 12px}.q{font-size:22px;font-weight:750;margin:12px 0 18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.box{border:1px solid var(--line);border-radius:16px;padding:16px;background:#fffdf8}.box h3{margin:0 0 8px;font-size:14px;color:var(--accent);text-transform:uppercase;letter-spacing:.06em}ul{margin:0;padding-left:19px}.risk{border-color:#e3b9ae;background:#fff6f3}.risk h3{color:var(--red)}.cite span{display:inline-block;margin:4px 6px 0 0;padding:6px 9px;border:1px solid var(--line);border-radius:999px;background:white;color:#39443d;font-size:13px}.principles{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.pill{border:1px solid var(--line);border-radius:999px;padding:7px 10px;background:white;color:var(--muted);font-size:13px}footer{padding:18px 56px;color:var(--muted);font-size:13px}@media(max-width:850px){.wrap{grid-template-columns:1fr}nav{position:relative}.grid{grid-template-columns:1fr}}
</style></head><body><header><div class="eyebrow">Bản đầu tư BĐS / concise</div><h1 id="title"></h1><div class="sub" id="sub"></div><div class="principles" id="principles"></div></header><main class="wrap"><nav id="nav"></nav><section><article class="card" id="card"></article></section></main><footer>Ghi chú: đây là bản curated ngắn, tập trung quyết định đầu tư; bấm từng gate để xem output/rủi ro/căn cứ.</footer><script>
let DATA,active=0;fetch('investment_bds_flow.json').then(r=>r.json()).then(d=>{DATA=d;init()});
function init(){title.textContent=DATA.title;sub.textContent=DATA.subtitle;principles.innerHTML=DATA.principles.map(p=>`<span class=pill>${p}</span>`).join('');nav.innerHTML=DATA.gates.map((g,i)=>`<button class="navbtn ${i==0?'active':''}" onclick="show(${i})">${g.title}</button>`).join('');show(0)}
function show(i){active=i;document.querySelectorAll('.navbtn').forEach((b,j)=>b.classList.toggle('active',j==i));let g=DATA.gates[i];card.innerHTML=`<div class=eyebrow>Gate ${i}</div><h2>${g.title}</h2><div class=q>${g.investor_question}</div><div class=grid><div class=box><h3>Nhà đầu tư cần quyết</h3><ul>${g.decision.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class=box><h3>Output phải có</h3><p>${g.output}</p></div><div class="box risk"><h3>Rủi ro chính</h3><p>${g.risk}</p></div><div class="box cite"><h3>Căn cứ</h3>${g.citations.map(c=>`<span>${c}</span>`).join('')}</div></div>`}
</script></body></html>'''
(web/'investment_bds_flow.html').write_text(html,encoding='utf-8')
print('wrote investment_bds_flow')
