import json, pathlib, shutil
base=pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS')
out=base/'web_mindmap/tpre_bds_flow.json'

def law(doc, arts, source, pts):
    return {'doc':doc,'article':arts,'source_file':source,'points':pts}

common={
'pre':[law('Luật Đầu tư 2025','Điều 3, Điều 23, Điều 24','143_2025_qh15_681550_full.md',['Xác định CTCTĐT, hình thức lựa chọn NĐT và nghĩa vụ bảo đảm thực hiện dự án.','Lựa chọn NĐT thông qua đấu giá QSDĐ, đấu thầu lựa chọn NĐT, chấp thuận NĐT hoặc hình thức khác theo luật chuyên ngành.']),law('Luật Đất đai 2024','Điều 116, 124, 126, 127','31_2024_qh15_523642_full.md',['Rà route đất: giao/thuê đất, chuyển mục đích, đấu giá QSDĐ, đấu thầu dự án có sử dụng đất, thỏa thuận nhận QSDĐ/đang có QSDĐ.'])],
'planning':[law('Luật Quy hoạch đô thị và nông thôn 2024','Nhóm quy định hệ thống quy hoạch; QHCT','47_2024_qh15_583645_full.md',['QHCT tỷ lệ 1/500 hoặc quy hoạch tổng mặt bằng là nền tảng cho thiết kế, GPXD, điều kiện bán hàng và cấp GCN.']),law('Luật Nhà ở 2023 / văn bản hướng dẫn','Chương trình, kế hoạch phát triển nhà ở','27_2023_qh15_530121_full.md',['Dự án nhà ở phải kiểm tra sự phù hợp chương trình/kế hoạch phát triển nhà ở và chỉ tiêu phát triển nhà ở tại địa phương.'])],
'land':[law('Luật Đất đai 2024','Điều 79, 116, 124, 126, 127, 153, 158, 160','31_2024_qh15_523642_full.md',['Căn cứ thu hồi đất, bồi thường, GPMB, giao/thuê đất, chuyển mục đích, xác định giá đất và nghĩa vụ tài chính.']),law('NĐ 102/2024/NĐ-CP','Điều 44, 49, 55, 62','102_2024_nd-cp_603982_full.md',['Trình tự giao đất/cho thuê đất/chuyển mục đích; thủ tục đấu giá, đấu thầu, thỏa thuận nhận QSDĐ.']),law('NĐ 103/2024/NĐ-CP','Nhóm quy định tiền sử dụng đất, tiền thuê đất','103_2024_nd-cp_550020_full.md',['Xác định diện tích, giá đất, tiền sử dụng đất/tiền thuê đất và thời điểm xác định nghĩa vụ tài chính.'])],
'design':[law('Luật Xây dựng / NĐ quản lý dự án đầu tư xây dựng','Thiết kế cơ sở, TKKT, TKBVTC, GPXD','175_2024_nd-cp_619462_full.md',['Thẩm định BCNCKT/TKCS, TKKT/TKBVTC và cấp GPXD theo loại/cấp công trình, nguồn vốn và thẩm quyền.']),law('Luật Kiến trúc','Thi tuyển phương án kiến trúc','40_2019_qh14_387023_full.md',['Công trình công cộng cấp I, cấp đặc biệt hoặc công trình có yêu cầu kiến trúc đặc thù có thể phải thi tuyển phương án kiến trúc.'])],
'env':[law('Luật BVMT 2020/sửa đổi 2025','ĐTM, GPMT, vận hành thử nghiệm','72_2020_qh14_431147_full.md;146_2025_qh15_675259_full.md',['Xác định dự án thuộc đối tượng ĐTM/GPMT; thời điểm có GPMT và vận hành thử nghiệm công trình xử lý chất thải.']),law('NĐ 131/2025/NĐ-CP','Điều 26','131_2025_nd-cp_660659_full.md',['Thẩm quyền cấp GPMT của Chủ tịch UBND cấp tỉnh đối với dự án/cơ sở thuộc nhóm tương ứng.'])],
'pccc':[law('Luật PCCC và văn bản hướng dẫn','Ý kiến giải pháp PCCC, thẩm duyệt, nghiệm thu PCCC','55_2024_qh15_650673_full.md',['Dự án/công trình thuộc diện quản lý PCCC phải xin ý kiến giải pháp, thẩm duyệt thiết kế và nghiệm thu hệ thống PCCC trước vận hành/bàn giao.'])],
'business':[law('Luật KDBĐS 2023','Điều 6; nhóm quy định BĐS HTTTL','29_2023_qh15_530116_full.md',['Công khai thông tin dự án trước khi kinh doanh; điều kiện bán/cho thuê mua BĐS hình thành trong tương lai gắn với đất, thiết kế, GPXD, nghiệm thu mốc và bảo lãnh.']),law('NĐ 96/2024/NĐ-CP','Quy định chi tiết Luật KDBĐS','96_2024_nd-cp_600395_full.md',['Hồ sơ, điều kiện, công khai thông tin và quản lý giao dịch BĐS theo loại sản phẩm.']),law('Thông tư NHNN về bảo lãnh nhà ở HTTTL','Bảo lãnh nghĩa vụ tài chính CĐT','49_2024_tt-nhnn_629634_full.md',['Kiểm tra phạm vi/thời hạn/chứng thư bảo lãnh khi bán nhà ở hình thành trong tương lai.'])],
'handover':[law('NĐ quản lý chất lượng công trình','Nghiệm thu, kiểm tra nghiệm thu, hoàn thành đưa vào sử dụng','06_2021_nd-cp_469018_full.md;144_2025_nd-cp_660606_full.md',['Nghiệm thu với nhà thầu, kiểm tra công tác nghiệm thu bởi CQNN theo loại/cấp công trình; hoàn công và đưa công trình vào sử dụng.']),law('NĐ 101/2024/NĐ-CP','Đăng ký đất đai, cấp GCN','101_2024_nd-cp_613131_full.md',['Cấp GCN cho dự án/người mua; đăng ký biến động/tài sản gắn liền với đất; nơi nộp hồ sơ, trả kết quả và thời gian xử lý theo quy định.'])]
}

def item(code,title,owner,summary,inputs,outputs,laws,parallel=False):
    return {'code':code,'title':title,'owner':owner,'summary':summary,'inputs':inputs,'outputs':outputs,'legal_basis':laws,'parallel':parallel}

phases=[
{'id':'I','title':'Nghiên cứu tiền khả thi / Pre-FS','lane':'Đầu tư pháp lý + NCPT + GPMB','summary':'Khảo sát khu đất, thị trường, cấu trúc pháp lý route đầu tư trước khi đặt tiền lớn hoặc M&A.','items':[item('I','Nghiên cứu tiền khả thi ĐTXDDA / Pre-FS','Đầu tư pháp lý, NCPT, GPMB, Kinh doanh','Lập product brief: cấu trúc pháp lý, sản phẩm, tổng tiến độ, TMĐT/NSDA, cơ hội/rủi ro, phân kỳ, sơ bộ môi trường.',['Kiểm tra hiện trạng khu đất','Thu thập tiêu chí chọn NĐT','Khảo sát thị trường, giá bán','Legal DD hồ sơ dự án/quỹ đất'],['Product brief','Legal DD report','Sơ bộ cấu trúc pháp lý chính','Ma trận route đất/đầu tư'],common['pre'])]},
{'id':'II','title':'GPMB / thu mua đất / M&A','lane':'Giải phóng mặt bằng','summary':'Song song với chuẩn bị dự án: kiểm kê, bồi thường, thu mua/chỉnh lý hồ sơ, chuẩn bị nền đất sạch hoặc hồ sơ M&A.','items':[item('II','Thông báo thu hồi đất, kiểm đếm, bồi thường, GPMB','GPMB + CQNN','Thực hiện khảo sát, đo đạc, kiểm đếm, phương án bồi thường, hỗ trợ, TĐC; hoặc thu mua/M&A quyền dự án/quỹ đất.',['Bản đồ ranh đất/hiện trạng','Danh sách chủ sử dụng đất','Kế hoạch/khả năng tài chính GPMB','Phương án bồi thường nội bộ'],['Quyết định thu hồi đất','Phương án bồi thường/GPMB/TĐC','Xác nhận hoàn thành bồi thường','Hồ sơ chỉnh lý GCN'],common['land'],True)]},
{'id':'III','title':'CTCTĐT, lựa chọn NĐT, công nhận CĐT','lane':'Đầu tư pháp lý','summary':'Chốt tư cách dự án và chủ thể triển khai: CTCTĐT, lựa chọn NĐT, công nhận/chấp thuận CĐT, ký quỹ.','items':[item('III','Chấp thuận chủ trương đầu tư và NĐT thực hiện dự án','Đầu tư pháp lý + CQNN','Chuẩn bị hồ sơ pháp lý, năng lực tài chính, đất đai, thiết kế sơ bộ và các thỏa thuận kỹ thuật để trình CTCTĐT/CTNĐT.',['Hồ sơ năng lực NĐT','Hồ sơ đất đai','Thiết kế phục vụ CTCTĐT','Tài liệu đấu nối/giao thông/PCCC/môi trường nếu cần'],['Quyết định CTCTĐT/CTNĐT','Công nhận CĐT dự án','Thỏa thuận/ký quỹ thực hiện dự án','Cập nhật kế hoạch sử dụng đất/nhà ở'],common['pre']+common['planning'])]},
{'id':'IV','title':'Quy hoạch chi tiết 1/500 / Tổng mặt bằng','lane':'Quản lý thiết kế + Pháp lý','summary':'Từ quy hoạch 1/2000/chỉ tiêu đầu vào đến nhiệm vụ QHCT, đồ án QHCT 1/500 hoặc quy hoạch tổng mặt bằng cho khu nhỏ.','items':[item('IV','Lập nhiệm vụ, đồ án QHCT 1/500 hoặc quy hoạch tổng mặt bằng','QLTK + Đầu tư pháp lý','Lập nhiệm vụ QHCT, đồ án QHCT, quy định quản lý xây dựng; bản đồ hiện trạng, cao độ, cắm mốc phục vụ giao đất và thiết kế.',['Quy hoạch 1/2000/chỉ tiêu','Design brief TGĐ phê duyệt','Bản đồ HTVT/cao độ','Hồ sơ khảo sát địa hình, địa chất'],['Phê duyệt QHCT 1/500 hoặc tổng mặt bằng','Quy định QLXD theo đồ án','Bản đồ HTVT/cắm mốc giới được phê duyệt','Chỉ tiêu thiết kế sản phẩm'],common['planning']+common['design'])]},
{'id':'V','title':'Đất đai: giao/thuê đất, chuyển mục đích, tài chính, GCN dự án','lane':'Đầu tư pháp lý','summary':'Chuyển từ pháp lý dự án sang quyền sử dụng đất cụ thể: bàn giao ranh, quyết định đất, giá đất, nghĩa vụ tài chính, GCN QSDĐ dự án.','items':[item('V','QĐ giao thuê đất/chuyển mục đích, nghĩa vụ tài chính, GCN dự án','Đầu tư pháp lý + CQNN','Dựa trên QHCT/HTVT/cắm mốc và GPMB để giao đất/thuê đất/chuyển mục đích; xác định giá đất, nộp tiền, cấp GCN dự án.',['Bản đồ HTVT phục vụ giao đất','Hồ sơ cắm mốc giới','Biên bản bàn giao ranh mốc thực địa','Hồ sơ chứng thư thẩm định giá'],['QĐ giao/thuê đất/chuyển mục đích','Phê duyệt giá đất','Xác nhận hoàn tất nghĩa vụ tài chính','GCN QSDĐ dự án','Hoàn trả ký quỹ theo mốc'],common['land'])]},
{'id':'VI','title':'Thiết kế, môi trường, PCCC, đấu nối, GPXD','lane':'QLTK + Pháp lý + Kỹ thuật','summary':'Thiết kế và giấy phép kỹ thuật trước xây dựng: TKCS/BCNCKT, TKKT/TKBVTC, ĐTM/GPMT, PCCC, đấu nối hạ tầng, GPXD.','items':[item('VI','Thẩm định thiết kế, môi trường, PCCC, đấu nối, GPXD','QLTK + Đầu tư pháp lý','Chuẩn bị hồ sơ TKCS/BCNCKT, TKKT/TKBVTC, thỏa thuận đấu nối, PCCC, ĐTM/GPMT, GPXD và thông báo khởi công.',['Hồ sơ khảo sát địa hình/địa chất','Hồ sơ TKCS/BCNCKT','Hồ sơ TKKT/TKBVTC','Hồ sơ ĐTM/GPMT','Hồ sơ PCCC','Hồ sơ đấu nối HTKT'],['Văn bản thẩm định TKCS/BCNCKT','Thẩm duyệt PCCC','Thỏa thuận đấu nối điện/nước/thoát nước/giao thông','GPMT/ĐTM','GPXD','Thông báo khởi công'],common['design']+common['env']+common['pccc'])]},
{'id':'VII','title':'Thi công HTKT/HTXH/nhà ở','lane':'Quản lý thi công','summary':'Tổ chức thi công theo phân phần: san nền, hạ tầng kỹ thuật, phần ngầm/thân/hoàn thiện, tiện ích/cảnh quan, công trình tạm.','items':[item('VII','Triển khai thi công theo thiết kế và GPXD','QLTC + Nhà thầu','Thi công san nền, giao thông, thoát nước, cấp điện, cấp nước, thông tin liên lạc, trạm XLNT, phần ngầm/thân/hoàn thiện, tiện ích/cảnh quan.',['GPXD/thông báo khởi công','TKBVTC được phê duyệt','Hồ sơ công trình tạm nếu có','Kế hoạch QA/QC và an toàn'],['Biên bản nghiệm thu giai đoạn','Nghiệm thu HTKT/đấu nối theo giai đoạn','Hồ sơ hoàn công','Kế hoạch vận hành thử nghiệm XLNT'],common['design']+common['handover'])]},
{'id':'VIII','title':'Kinh doanh, huy động vốn, bán hàng','lane':'Kinh doanh + Pháp lý DN + Marketing','summary':'Chuẩn bị điều kiện bán/huy động vốn: product, mẫu HĐMB, bảo lãnh, nghiệm thu mốc, thông báo đủ điều kiện, marketing và ký HĐMB.','items':[item('VIII','Đủ điều kiện huy động vốn/bán BĐS HTTTL','Kinh doanh + P.PLDN + QLTC','Tạo điều kiện bán hàng sau khi có đủ pháp lý, nghiệm thu mốc HTKT/phần móng, mẫu HĐMB, bảo lãnh và thông báo đủ điều kiện mua bán.',['Bản vẽ thiết kế sản phẩm','Kế hoạch kinh doanh + rumor','Kế hoạch marketing','Mẫu HĐMB','Biên bản nghiệm thu HTKT/phần móng','Bảo lãnh ngân hàng nếu thuộc diện'],['Thông báo đủ điều kiện bán nhà/căn hộ HTTTL','Bán hàng','Ký HĐMB','Triển khai marketing chính thức'],common['business'])]},
{'id':'IX','title':'Nghiệm thu, hoàn thành đưa vào sử dụng','lane':'QLTC + CQNN + PCCC','summary':'Nghiệm thu với nhà thầu, kiểm tra nghiệm thu bởi CQNN, nghiệm thu PCCC, hoàn thành HTKT/HTXH/nhà ở để đủ điều kiện bàn giao.','items':[item('IX','Nghiệm thu hoàn thành HTKT/HTXH/nhà ở/PCCC','QLTC + CQNN + Cảnh sát PCCC','Nghiệm thu hoàn thành đưa vào sử dụng với nhà thầu và CQNN; kiểm tra nghiệm thu PCCC; bàn giao hệ thống PCCC nếu thuộc diện.',['Hồ sơ hoàn công','Biên bản nghiệm thu nhà thầu','Hồ sơ nghiệm thu PCCC','Kết quả vận hành thử XLNT/GPMT nếu có'],['Văn bản kiểm tra công tác nghiệm thu','Nghiệm thu PCCC','Biên bản kiểm tra hiện trạng công trình','Công trình đủ điều kiện đưa vào sử dụng'],common['handover']+common['pccc']+common['env'])]},
{'id':'X','title':'Bàn giao HTKT/HTXH, nhà ở và cấp GCN cho khách hàng','lane':'DVKH + Pháp lý + QLTC','summary':'Bàn giao công trình cho CQNN/khách hàng, hoàn tất hồ sơ cấp GCN QSDĐ, QSH nhà ở và tài sản gắn liền với đất.','items':[item('X','Bàn giao và cấp GCN QSDĐ, QSHNO, TSKGLVĐ','DVKH + Đầu tư pháp lý + CQNN','Bàn giao HTKT/HTXH cho CQNN; bàn giao nhà cho khách hàng; chuẩn bị bản vẽ phân lô/sơ đồ nhà đất, hồ sơ cấp GCN.',['Bản vẽ HTVT phân lô được duyệt','Bản vẽ sơ đồ nhà ở, đất ở','Biên bản nghiệm thu/bàn giao','Xác nhận đủ điều kiện cấp GCN','Hồ sơ nghĩa vụ tài chính'],['Bàn giao nhà cho khách hàng','VB đủ điều kiện cấp GCN','GCN QSDĐ, QSH nhà ở và TSKGLVĐ','Hồ sơ vận hành/bảo hành'],common['handover']+common['business'])]},
{'id':'XI','title':'Vận hành, bảo hành, hậu kiểm','lane':'DVKH + QLTC + CĐT','summary':'Quản lý vận hành sau bàn giao: bảo hành nhà thầu, bảo hành cho khách hàng, cập nhật dữ liệu và xử lý hậu kiểm.','items':[item('XI','Quản lý vận hành và bảo hành sau bàn giao','DVKH + QLTC + CĐT','Theo dõi bảo hành nhà thầu và bảo hành cho khách hàng; bàn giao hồ sơ vận hành; cập nhật dữ liệu nhà ở/thị trường BĐS nếu có.',['Hồ sơ bàn giao','Quy trình bảo hành','Danh mục lỗi/tồn tại','Hồ sơ pháp lý vận hành'],['Hoàn tất nghĩa vụ bảo hành','Hồ sơ vận hành dự án','Dữ liệu dự án/sản phẩm được cập nhật','Kết thúc vòng đời pháp lý đầu tư xây dựng'],common['handover'])]}
]

data={'source':'TPRE_LUU_DO_DAU_TU_XD_DA_BDS_V2_BAN_GOC_2024.05.28.pdf','version':'tpre_flow_v1','description':'Cấu trúc lưu đồ đầu tư xây dựng dự án BĐS dựa trên PDF TPRE do người dùng cung cấp, có map căn cứ luật local theo từng mốc.','phases':phases,'lanes':['Đầu tư pháp lý','Quản lý thiết kế','Quản lý thi công','Dịch vụ khách hàng','Kinh doanh','Giải phóng mặt bằng','Tiếp thị'],'abbreviations':{'BĐS':'Bất động sản','ĐTXDDA':'Đầu tư xây dựng dự án','Pre-FS':'Nghiên cứu tiền khả thi','CTCTĐT':'Chấp thuận chủ trương đầu tư','NĐT':'Nhà đầu tư','CĐT':'Chủ đầu tư','QHCT':'Quy hoạch chi tiết','TL 1/500':'Tỷ lệ 1/500','QSDĐ':'Quyền sử dụng đất','GCN':'Giấy chứng nhận','GPMB':'Giải phóng mặt bằng','TĐC':'Tái định cư','TKCS':'Thiết kế cơ sở','BCNCKT':'Báo cáo nghiên cứu khả thi','TKKT':'Thiết kế kỹ thuật','TKBVTC':'Thiết kế bản vẽ thi công','HTKT':'Hạ tầng kỹ thuật','HTXH':'Hạ tầng xã hội','ĐTM':'Đánh giá tác động môi trường','GPMT':'Giấy phép môi trường','PCCC':'Phòng cháy chữa cháy','HĐMB':'Hợp đồng mua bán','HTTTL':'Hình thành trong tương lai','CQNN':'Cơ quan nhà nước'}}
out.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
for p in [base/'FINAL_BDS_LEGAL_WEB/tpre_bds_flow.json', pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\deploy_bds_legal_process\public\bds-legal-process\tpre_bds_flow.json')]:
    p.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print(out)
