from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
# CSS for full checklist sections
s=s.replace('.summaryBox{border:1px solid #cfe0f5;background:linear-gradient(180deg,#f8fbff,#fff);border-radius:18px;padding:16px;grid-column:1/-1}', '.summaryBox{border:1px solid #cfe0f5;background:linear-gradient(180deg,#f8fbff,#fff);border-radius:18px;padding:16px;grid-column:1/-1}.fullChecklist{grid-column:1/-1;border:1px solid #dbeafe;background:#f8fbff;border-radius:18px;padding:16px}.fullChecklist h4{margin:0 0 12px;text-transform:uppercase;font-size:12px;letter-spacing:.08em;color:#0b3d91}.checkGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.checkGroup{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:12px}.checkGroup b{display:block;color:#0b3d91;margin-bottom:8px}.checkGroup .line{font-size:13px;padding:6px 0}')
s=s.replace('@media(max-width:900px){.expertGrid,.formulaGrid{grid-template-columns:1fr}}', '@media(max-width:900px){.expertGrid,.formulaGrid,.checkGrid{grid-template-columns:1fr}}')
old='''<div class=\"summaryBox\"><b>Mục tiêu thủ tục:</b> ${esc(it.summary||p.summary)}<div class=\"toc\"><span>1. Quy trình</span><span>2. Hồ sơ/điều kiện</span><span>3. Thời gian</span><span>4. Kết quả</span><span>5. Căn cứ pháp lý</span></div></div><div class=\"dossier\">'''
new='''<div class=\"summaryBox\"><b>Mục tiêu thủ tục:</b> ${esc(it.summary||p.summary)}<div class=\"toc\"><span>1. Áp dụng</span><span>2. Đầu vào</span><span>3. Hồ sơ</span><span>4. Quy trình</span><span>5. Điều kiện</span><span>6. Thời gian</span><span>7. Output</span><span>8. Rủi ro</span><span>9. Căn cứ</span></div></div>${fullChecklistBlock(it.code||p.id,p.id)}<div class=\"dossier\">'''
s=s.replace(old,new)
insert=r'''
function fullChecklistBlock(code,id){const groups=fullChecklistFor(code,id); if(!groups.length) return ''; return `<div class="fullChecklist"><h4>Checklist chi tiết — tóm tắt nhưng không thiếu ý</h4><div class="checkGrid">${groups.map(g=>`<div class="checkGroup"><b>${esc(g.title)}</b>${lines(g.items)}</div>`).join('')}</div></div>`}
function fullChecklistFor(code,id){const base={
I:[['Phải hiểu gì trước khi quyết định đầu tư',['Chủ đất/chủ dự án là ai, quyền định đoạt có hợp pháp không.','Đất đang là loại đất gì, mục đích sau dự án là gì, có phải chuyển mục đích không.','Dự án đi theo route nào: đấu giá, đấu thầu, chấp thuận NĐT, M&A, tự thỏa thuận nhận QSDĐ.','Có phù hợp quy hoạch, kế hoạch sử dụng đất, kế hoạch phát triển nhà ở không.']],['Tài liệu cần gom',['GCN/hồ sơ đất, bản đồ ranh, hiện trạng, thông tin quy hoạch.','Hồ sơ pháp lý chủ đất/dự án, hợp đồng/thỏa thuận đã có.','Thông tin tranh chấp, thế chấp, hạn chế chuyển nhượng, đất công/xen kẹt.','Sơ bộ sản phẩm, giá bán, tổng mức đầu tư, tiến độ, phân kỳ.']],['Kết luận cần ra',['Ma trận route pháp lý.','Danh mục rủi ro đỏ/vàng/xanh.','Điều kiện tiên quyết trước đặt cọc/M&A.','Khuyến nghị đi tiếp/dừng/đàm phán điều kiện.']]],
II:[['Phạm vi kiểm tra GPMB',['Ranh dự án và từng thửa trong ranh.','Chủ sử dụng đất, tài sản trên đất, hiện trạng cư trú/sản xuất.','Đất công, kênh rạch, đường giao thông, hạ tầng kỹ thuật hiện hữu.','Khả năng thu hồi đất hay phải tự thỏa thuận.']],['Hồ sơ/việc phải làm',['Bản đồ ranh, bản đồ hiện trạng, kiểm kê tài sản.','Phương án bồi thường, hỗ trợ, TĐC và ngân sách chi trả.','Kế hoạch kiểm đếm, vận động, chi trả, bàn giao mặt bằng.','Chỉnh lý GCN/hồ sơ địa chính sau bồi thường.']],['Điểm nghẽn',['Khiếu nại/khiếu kiện.','Không đồng thuận giá bồi thường.','Đất công/xen kẹt chưa xử lý.','Chậm bố trí vốn GPMB làm chậm giao đất/thi công.']]],
III:[['Phân loại thủ tục đầu tư',['Dự án có phải CTCTĐT không.','Có phải lựa chọn NĐT qua đấu giá/đấu thầu không.','Có thể chấp thuận NĐT do đang có/nhận QSDĐ không.','Dự án nhà ở có cần công nhận/chấp thuận CĐT riêng không.']],['Hồ sơ trọng yếu',['Đề xuất dự án: mục tiêu, quy mô, địa điểm, tiến độ, vốn.','Hồ sơ năng lực pháp lý và tài chính NĐT.','Tài liệu đất đai/quy hoạch/kế hoạch nhà ở/kế hoạch sử dụng đất.','Phương án ký quỹ/bảo đảm thực hiện dự án.']],['Điểm phải khóa',['Thẩm quyền chấp thuận.','Route lựa chọn NĐT.','Nội dung CTCTĐT khớp mô hình kinh doanh.','Điều kiện sau chấp thuận: ký quỹ, đất, quy hoạch, thiết kế.']]],
IV:[['Nội dung phải có trong QHCT',['Ranh giới, diện tích, cơ cấu sử dụng đất.','Dân số, tầng cao, mật độ xây dựng, hệ số sử dụng đất.','Chỉ tiêu HTKT: giao thông, cấp nước, thoát nước, điện, rác thải.','Chỉ tiêu HTXH, cây xanh, bãi xe, tiện ích.']],['Đầu vào thiết kế/quy hoạch',['Quy hoạch cấp trên, nhiệm vụ QHCT/tổng mặt bằng.','Bản đồ hiện trạng, cao độ, khảo sát.','Design brief/product brief.','Ý kiến giao thông, PCCC, môi trường sơ bộ nếu cần.']],['Rủi ro cần tránh',['Chỉ tiêu bán hàng không khớp quy hoạch.','Không đủ hạ tầng/dân số/bãi xe/PCCC.','Điều chỉnh QHCT sau khi đã làm thiết kế/GPXD.','QHCT không phục vụ được cấp sổ/phân lô.']]],
V:[['Tách bài toán tài chính đất',['Giao đất có thu tiền sử dụng đất.','Thuê đất trả tiền một lần.','Thuê đất trả tiền hằng năm.','Chuyển mục đích sử dụng đất.','Điều chỉnh quy hoạch làm tăng nghĩa vụ tài chính.']],['Biến đầu vào để tính',['Diện tích tính tiền theo từng loại đất.','Mục đích sử dụng trước/sau.','Thời hạn sử dụng đất/thời hạn thuê.','Bảng giá đất hoặc giá đất cụ thể.','Khoản GPMB/ứng trước/miễn giảm/khấu trừ.']],['Output cần giữ',['Quyết định giao/thuê/chuyển mục đích.','Quyết định giá đất hoặc căn cứ bảng giá đất.','Thông báo nộp tiền.','Chứng từ nộp và xác nhận hoàn thành nghĩa vụ tài chính.','GCN QSDĐ dự án.']]],
VI:[['Nhóm thủ tục kỹ thuật',['TKCS/BCNCKT, TKKT, TKBVTC.','PCCC: góp ý giải pháp, thẩm duyệt, nghiệm thu.','Môi trường: ĐTM/GPMT/vận hành thử.','Đấu nối HTKT: giao thông, điện, nước, thoát nước, XLNT.','GPXD và thông báo khởi công.']],['Hồ sơ phải đồng bộ',['QHCT, ranh đất, chỉ tiêu quy hoạch.','Khảo sát địa hình, địa chất, hạ tầng ngầm.','Thiết kế kiến trúc/kết cấu/MEP/PCCC/môi trường.','Văn bản đấu nối và thẩm định chuyên ngành.']],['Điểm nghẽn',['PCCC và môi trường làm muộn.','Thiết kế không khớp QHCT/GPXD.','Đấu nối hạ tầng chưa có thỏa thuận.','Thiếu thẩm tra/thẩm định.']]],
VII:[['Quản trị thi công',['Thi công đúng GPXD/TKBVTC.','Tách mốc san nền, HTKT, phần móng, phần thân, hoàn thiện.','Quản lý thay đổi thiết kế/phát sinh.','Lập hồ sơ chất lượng theo ngày, không gom cuối.']],['Hồ sơ nghiệm thu',['Nhật ký thi công, biên bản nghiệm thu công việc/giai đoạn.','Kết quả thí nghiệm vật liệu/thiết bị.','Bản vẽ hoàn công.','Hồ sơ an toàn, môi trường, PCCC trong thi công.']],['Liên kết pháp lý',['Nghiệm thu mốc có thể là điều kiện bán HTTTL.','Hoàn công là nền nghiệm thu đưa vào sử dụng và cấp sổ.','Sai thi công có thể phải điều chỉnh GPXD/QHCT.']]],
VIII:[['Điều kiện mở bán',['Có pháp lý dự án/đất/quy hoạch/GPXD.','Có nghiệm thu mốc: phần móng hoặc HTKT tùy sản phẩm.','Có bảo lãnh nhà ở HTTTL nếu thuộc diện.','Có mẫu HĐMB và công khai thông tin.','Có thông báo đủ điều kiện bán.']],['Kiểm soát kinh doanh',['Sales script phải khớp pháp lý.','Booking/giữ chỗ/đặt cọc không được biến thành huy động vốn trái phép.','Tiến độ thanh toán khớp luật và tiến độ xây dựng.','Thông tin marketing không vượt trạng thái pháp lý.']],['Hồ sơ cần lưu',['Bộ pháp lý bán hàng.','Thông báo đủ điều kiện bán.','Bảo lãnh/chứng thư.','Mẫu hợp đồng, phụ lục, chính sách bán hàng.']]],
IX:[['Điều kiện nghiệm thu',['Thi công xong đúng thiết kế/GPXD.','Hồ sơ hoàn công đầy đủ.','PCCC, môi trường, đấu nối đạt yêu cầu.','Không còn tồn tại trọng yếu hiện trường.']],['Hồ sơ phải có',['Biên bản nghiệm thu nhà thầu/tư vấn/CĐT.','Bản vẽ hoàn công.','Kết quả kiểm định/thí nghiệm.','Hồ sơ PCCC/GPMT/đấu nối.','Văn bản kiểm tra nghiệm thu của CQNN nếu thuộc diện.']],['Output sử dụng sau',['Đưa công trình vào sử dụng.','Bàn giao nhà/HTKT/HTXH.','Lập hồ sơ cấp GCN.','Kết thúc điều kiện xây dựng cho bán hàng/bàn giao.']]],
X:[['Hồ sơ bàn giao/cấp sổ',['Biên bản bàn giao nhà/căn hộ/sản phẩm.','Bản vẽ sơ đồ nhà đất/phân lô.','Hồ sơ hoàn công/nghiệm thu.','Xác nhận nghĩa vụ tài chính.','Hồ sơ giải chấp nếu tài sản đang thế chấp.','Hồ sơ khách hàng/HĐMB/chứng từ thanh toán.']],['Việc phải kiểm soát',['Diện tích thực tế và diện tích hợp đồng.','Phần sở hữu riêng/chung.','Tình trạng bảo hành, tồn tại bàn giao.','Thời hạn cam kết cấp GCN.']],['Rủi ro',['Sai diện tích/sơ đồ.','Thiếu nghĩa vụ tài chính.','Chưa giải chấp.','Hồ sơ khách hàng thiếu/sai.','Chưa hoàn tất bàn giao hạ tầng.']]],
XI:[['Sau bàn giao cần quản gì',['Bảo hành nhà thầu.','Bảo hành cho khách hàng.','Hồ sơ vận hành, tài sản, thiết bị.','Khiếu nại, tồn tại, hậu kiểm.']],['Tài liệu nội bộ',['Danh mục tồn tại.','Sổ bảo hành.','Biên bản bàn giao vận hành.','Hồ sơ pháp lý hoàn công/cấp sổ.','Ma trận trách nhiệm CĐT - nhà thầu - BQL.']],['Rủi ro',['Không phân định lỗi bảo hành.','Thiếu hồ sơ vận hành.','Tranh chấp phần chung/riêng.','Chậm xử lý khiếu nại ảnh hưởng uy tín dự án.']]]
}; let data=base[id]||[]; if(code==='V-O.1') data=[...data,['Cách tính cần trình bày riêng',['Công thức tiền sử dụng đất.','Công thức tiền thuê đất một lần.','Công thức tiền thuê đất hằng năm.','Khoản trừ/khấu trừ/miễn giảm.','Check NĐ 87/2025/NĐ-CP hoặc văn bản mới nếu có.']]]; return data.map(x=>({title:x[0],items:x[1]}))}
'''
marker='function formulaBlock(code,id)'
s=s.replace(marker,insert+'\n'+marker)
p.write_text(s,encoding='utf-8')
print('patched full checklist sections')
