from pathlib import Path
p=Path(r"C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\build_bds_process_timeline_lawfaithful.py")
s=p.read_text(encoding='utf-8')
marker="for s in data['steps']:\n    s['legal_points']=basis(s.get('legal_basis',[]))\n    for p in s.get('procedures',[]):\n        p['legal_points']=basis(p.get('legal_basis',[]))\n"
if 'EXPERT = {' not in s:
    expert=r'''
EXPERT = {
 'gate0': {'focus':['Kiểm tra pháp lý đất trước khi đặt cọc/góp vốn lớn.','Chốt route: đấu giá QSDĐ / đấu thầu NĐT / tự thỏa thuận QSDĐ / CTCTĐT.','Lập mô hình tài chính sơ bộ gồm giá đất, GPMB, tiền đất, hạ tầng, thời gian pháp lý.','Khoanh red flag: đất xen kẹt, quy hoạch treo, thiếu đường, thiếu chỉ tiêu dân số.'], 'outputs':['Legal DD quỹ đất có kết luận đi/không đi.','Ma trận route pháp lý + xác suất + thời gian + chi phí.','Danh sách hồ sơ cần lấy trước khi ký tiền lớn.','Điều kiện precedent đưa vào MOU/SPA/đặt cọc.'], 'checkpoints':['QSDĐ/rường ranh khớp thực địa.','Quy hoạch/kế hoạch sử dụng đất phù hợp mục tiêu dự án.','Có phương án GPMB/đất xen kẹt/đường vào.','Có ước tính nghĩa vụ tài chính đất và timeline.'], 'risks':['Đặt cọc xong mới biết phải đấu giá/đấu thầu hoặc không chuyển mục đích được.','GPMB kéo dài làm vỡ IRR.','Chủ đất cam kết quá mức nhưng thiếu hồ sơ gốc.','Nhầm loại đất với khả năng làm nhà ở thương mại.']},
 'gate1': {'focus':['Không chỉ xem đất có quy hoạch ở; phải xem mật độ, tầng cao, dân số, FAR, hạ tầng xã hội.','Đối chiếu sản phẩm với bãi xe, giao thông, trường học, cây xanh, thoát nước.','Nếu điều chỉnh quy hoạch, cộng thêm thời gian và rủi ro phê duyệt.','Kiểm tra quy hoạch cấp trên có “đỡ” QHCT không.'], 'outputs':['Bảng chỉ tiêu phát triển khả thi.','Phương án sản phẩm sơ bộ.','Danh mục nội dung cần điều chỉnh quy hoạch.','Kết luận tác động chỉ tiêu đến doanh thu/chi phí/timeline.'], 'checkpoints':['Chỉ tiêu khớp mục tiêu đầu tư.','Không vượt năng lực hạ tầng khu vực.','Có cơ sở lập/điều chỉnh QHCT.','Sản phẩm không mâu thuẫn pháp lý đất/nhà ở.'], 'risks':['Chỉ tiêu không được cơ quan quy hoạch chấp thuận.','Tăng dân số kéo theo nghĩa vụ hạ tầng lớn.','Điều chỉnh quy hoạch kéo dài và phát sinh chi phí.','Thiếu bãi xe/hạ tầng làm thiết kế phải làm lại.']},
 'gate2': {'focus':['Xác định đúng thẩm quyền CTCTĐT và hình thức chọn NĐT.','Chuẩn bị năng lực tài chính bằng BCTC/cam kết hỗ trợ/bảo lãnh/tài liệu tương đương.','Nếu đấu thầu NĐT, chuẩn bị kinh nghiệm, vốn CSH, phương án triển khai, tiến độ.','Không để CTCTĐT mâu thuẫn quy hoạch, đất, tổng vốn, GPMB.'], 'outputs':['Hồ sơ CTCTĐT/đề xuất dự án đủ nộp.','Văn bản CTCTĐT hoặc bộ hồ sơ mời quan tâm/đấu thầu.','Bảng điều kiện NĐT cần đáp ứng.','Timeline lựa chọn NĐT và mốc phê duyệt.'], 'checkpoints':['Tổng vốn, vốn CSH, tiến độ, nhu cầu đất nhất quán.','NĐT đủ năng lực so với quy mô dự án.','Route đấu giá/đấu thầu/chấp thuận NĐT đã rõ.','Có phương án nếu có từ 2 NĐT quan tâm.'], 'risks':['Sai route lựa chọn NĐT phải làm lại thủ tục.','Không đủ năng lực tài chính/kinh nghiệm.','Hồ sơ bị trả vì số liệu đất/quy hoạch/tổng vốn không khớp.','Đối thủ tham gia đấu thầu làm đổi chiến lược deal.']},
 'gate3': {'focus':['Quản đất đai như critical path: GPMB, quyết định đất, tiền đất, GCN.','Hợp đồng deal phải có điều kiện về tiến độ giao/thuê/chuyển mục đích.','Ước tính tiền đất theo nhiều kịch bản.','Không mở bán/huy động khi giấy tờ đất chưa đủ điều kiện.'], 'outputs':['Quyết định giao/thuê/chuyển mục đích.','Phương án/biên bản GPMB/bàn giao mặt bằng.','Thông báo nghĩa vụ tài chính đất.','GCN/đăng ký đất hoặc hồ sơ đủ điều kiện tiếp tục.'], 'checkpoints':['Ranh, diện tích, mục đích khớp hồ sơ dự án.','GPMB đạt điều kiện triển khai.','Nghĩa vụ tài chính đất được xác định/nộp.','Không có tranh chấp/kê biên/hạn chế giao dịch.'], 'risks':['Tiền đất cao hơn phương án đầu tư.','GPMB không xong làm đình trệ dự án.','Quyết định đất không khớp quy hoạch/CTCTĐT.','Chậm GCN làm tắc vay vốn, thế chấp, bán hàng.']},
 'gate4': {'focus':['Trước khởi công phải khóa thiết kế, GPXD, ĐTM/GPMT, PCCC, hạ tầng đấu nối.','Xử lý PCCC/môi trường sớm, không để cuối mới làm.','Thiết kế phải khớp QHCT, tầng cao, dân số, công năng, sản phẩm.','Kiểm tra năng lực tư vấn/nhà thầu vì lỗi hồ sơ kỹ thuật gây chậm lớn.'], 'outputs':['Hồ sơ thiết kế/thẩm định.','GPXD hoặc căn cứ miễn GPXD.','Văn bản ĐTM/GPMT tương ứng.','Thẩm duyệt PCCC, thỏa thuận đấu nối.'], 'checkpoints':['Thiết kế không vượt chỉ tiêu quy hoạch.','Đủ điều kiện khởi công.','PCCC/môi trường xử lý trước mốc thi công chính.','Đấu nối giao thông/điện/nước/thoát nước có cơ sở.'], 'risks':['Khởi công thiếu điều kiện bị đình chỉ/xử phạt.','Thiết kế phải sửa do PCCC/môi trường/quy hoạch.','Hạ tầng đấu nối không được chấp thuận làm chậm bàn giao.','Chi phí kỹ thuật phát sinh đội tổng mức.']},
 'gate5': {'focus':['Quản thi công theo mốc pháp lý: khởi công, móng, hạ tầng, nghiệm thu, hoàn công.','Mốc nghiệm thu móng/hạ tầng liên quan điều kiện bán hàng.','Lưu hồ sơ chất lượng từ đầu, không đợi cuối mới gom.','Kiểm soát thay đổi thiết kế để tránh sai phép/sai quy hoạch.'], 'outputs':['Thông báo/biên bản khởi công nếu cần.','Hồ sơ quản lý chất lượng.','Biên bản nghiệm thu từng giai đoạn.','Hồ sơ hoàn công đủ cho bàn giao/cấp sổ.'], 'checkpoints':['Thi công đúng thiết kế, GPXD, QHCT.','Nghiệm thu móng/hạ tầng đúng mốc.','Hồ sơ hoàn công đủ chữ ký/chứng chỉ/chứng nhận.','Không có vi phạm xây dựng chưa xử lý.'], 'risks':['Xây sai phép không hoàn công được.','Thiếu nghiệm thu làm tắc mở bán/bàn giao.','Chậm thi công vi phạm tiến độ CTCTĐT/hợp đồng khách.','Tranh chấp nhà thầu ảnh hưởng nghiệm thu.']},
 'gate6': {'focus':['Chỉ mở bán/huy động khi đủ điều kiện; booking không biến thành huy động vốn trá hình.','Chuẩn bị bộ pháp lý bán hàng: đất, CTĐT, QHCT, GPXD, nghiệm thu móng/hạ tầng, bảo lãnh.','Công khai thông tin dự án và hợp đồng mẫu.','Kiểm soát truyền thông bán hàng không cam kết vượt pháp lý.'], 'outputs':['Thông báo/điều kiện đưa BĐS vào kinh doanh nếu thuộc diện.','Bộ hồ sơ bán hàng và hợp đồng mẫu.','Bảo lãnh NH cho nhà ở HTTTL nếu thuộc diện.','Quy trình nhận tiền đúng bản chất pháp lý.'], 'checkpoints':['Đủ giấy tờ đất và điều kiện xây dựng.','Đã công khai thông tin dự án.','Bảo lãnh/điều kiện bán HTTTL hoàn tất nếu cần.','Booking/đặt cọc/hợp đồng không trái luật huy động vốn.'], 'risks':['Thu tiền sai thời điểm gây tranh chấp/xử phạt/rủi ro hình sự.','Bán khi chưa đủ điều kiện làm mất uy tín và tắc ngân hàng.','Hợp đồng mẫu sai gây khiếu kiện tập thể.','Chuyển nhượng dự án khi chưa đủ điều kiện.']},
 'gate7': {'focus':['Kết thúc dự án gồm bàn giao đúng pháp lý, vận hành ổn và cấp sổ được.','Hoàn công, nghiệm thu PCCC/công trình và nghĩa vụ tài chính đất phải khép kín.','Với chung cư, minh bạch quỹ bảo trì, ban quản trị, sở hữu chung-riêng.','Cấp sổ chậm là rủi ro uy tín và tranh chấp lớn.'], 'outputs':['Biên bản bàn giao sản phẩm.','Hồ sơ vận hành/quản lý chung cư nếu có.','Hồ sơ cấp GCN cho người mua.','Biên bản bàn giao hạ tầng/công trình công cộng nếu thuộc diện.'], 'checkpoints':['Công trình đủ điều kiện nghiệm thu đưa vào sử dụng.','Không còn nghĩa vụ tài chính/chỉnh lý đất cản trở cấp sổ.','Hồ sơ khách hàng và dự án đủ để nộp GCN.','Quỹ bảo trì/vận hành xử lý minh bạch.'], 'risks':['Bàn giao khi chưa đủ nghiệm thu.','Chậm cấp sổ do thiếu hoàn công/nghĩa vụ tài chính/đăng ký đất.','Tranh chấp sở hữu chung-riêng, phí, quỹ bảo trì.','Không bàn giao hạ tầng đúng cam kết.']}
}
for step in data.get('steps',[]):
    e=EXPERT.get(step.get('id'))
    if e:
        step['expert_focus']=e['focus']; step['expert_outputs']=e['outputs']; step['expert_checkpoints']=e['checkpoints']; step['expert_risks']=e['risks']
'''
    if marker not in s:
        raise SystemExit('marker not found')
    s=s.replace(marker, marker+expert)
old="""<div class=grid>${arr('Làm khi nào?', [s.when])}${arr('Mục tiêu bắt buộc', [s.must])}${arr('Output của bước',s.outputs)}${arr('Rủi ro chính',s.risks,'risk')}</div>"""
new="""<div class=grid>${arr('Làm khi nào?', [s.when])}${arr('Việc NĐT cần chú ý',s.expert_focus||[])}${arr('Output thực chiến',s.expert_outputs||s.outputs)}${arr('Checkpoint / điều kiện',s.expert_checkpoints||s.checkpoints)}${arr('Rủi ro',s.expert_risks||s.risks,'risk')}</div>"""
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
print('patched')
