import json, pathlib, shutil
base=pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS')
p=base/'web_mindmap/tpre_bds_flow.json'
data=json.loads(p.read_text(encoding='utf-8'))

def detail_law(doc, article, source, applies, conditions, dossier, authority, output, notes):
    pts=[]
    if applies: pts.append('Áp dụng trong flow: '+applies)
    if conditions: pts.append('Điều kiện/checkpoint: '+conditions)
    if dossier: pts.append('Hồ sơ/dữ liệu cần chuẩn bị: '+dossier)
    if authority: pts.append('Cơ quan/thẩm quyền thường gặp: '+authority)
    if output: pts.append('Output pháp lý: '+output)
    if notes: pts.append('Lưu ý thực hiện: '+notes)
    return {'doc':doc,'article':article,'source_file':source,'points':pts}

basis={
'pre':[detail_law('Luật Đầu tư 2025','Điều 3, Điều 23, Điều 24','143_2025_qh15_681550_full.md','Dùng để xác định dự án có phải xin CTCTĐT/CTNĐT, lựa chọn NĐT theo hình thức nào và có nghĩa vụ ký quỹ/bảo lãnh thực hiện dự án hay không.','Có mục tiêu, địa điểm, quy mô, tiến độ, thời hạn dự án; xác định sơ bộ nhu cầu đất, hình thức tiếp cận đất và năng lực NĐT.','Văn bản/đề xuất dự án, hồ sơ pháp lý NĐT, năng lực tài chính, tài liệu đất đai/quy hoạch, thiết kế sơ bộ nếu có.','UBND cấp tỉnh, Thủ tướng, Quốc hội hoặc cơ quan đăng ký đầu tư tùy quy mô/tính chất dự án.','Quyết định/chấp thuận CTCTĐT, CTNĐT hoặc căn cứ đi vào thủ tục lựa chọn NĐT.','Ở giai đoạn Pre-FS phải chốt route: đấu giá QSDĐ, đấu thầu NĐT, chấp thuận NĐT, tự có đất/thỏa thuận nhận QSDĐ; route sai sẽ làm vỡ timeline.'),detail_law('Luật Đất đai 2024','Điều 116, 124, 126, 127','31_2024_qh15_523642_full.md','Dùng để phân loại con đường tiếp cận đất: giao/thuê đất, chuyển mục đích, đấu giá QSDĐ, đấu thầu dự án có sử dụng đất, hoặc thỏa thuận nhận QSDĐ/đang có QSDĐ.','Phù hợp quy hoạch/kế hoạch sử dụng đất; đáp ứng điều kiện giao/thuê/chuyển mục đích; không thuộc trường hợp buộc phải đấu giá/đấu thầu nếu chọn route khác.','Thông tin thửa đất, loại đất, GCN, bản đồ ranh, quy hoạch, hiện trạng sử dụng, thông tin đất công/xen kẹt nếu có.','UBND cấp tỉnh/cấp huyện, cơ quan tài nguyên môi trường, trung tâm phát triển quỹ đất tùy thủ tục.','Kết luận DD đất và ma trận route đất pháp lý cho dự án.','Không chỉ hỏi “có đất không”, phải hỏi “đất vào dự án bằng cơ chế nào”. Đây là điểm rủi ro lớn nhất khi đặt cọc/M&A.')],
'planning':[detail_law('Luật Quy hoạch đô thị và nông thôn 2024','Nhóm quy định hệ thống quy hoạch; QHCT','47_2024_qh15_583645_full.md','Làm căn cứ lập nhiệm vụ/đồ án QHCT 1/500 hoặc quy hoạch tổng mặt bằng, kiểm tra chỉ tiêu sử dụng đất, tầng cao, mật độ, dân số, hạ tầng.','Dự án phải phù hợp quy hoạch cấp trên; QHCT/Tổng mặt bằng phải đủ cơ sở cho thiết kế, GPXD, giao đất và kinh doanh.','Bản đồ hiện trạng, chỉ tiêu quy hoạch, nhiệm vụ QHCT, hồ sơ thiết kế ý tưởng, hồ sơ lấy ý kiến cộng đồng/cơ quan nếu thuộc diện.','UBND/cơ quan quy hoạch kiến trúc, Sở Xây dựng/Sở Quy hoạch Kiến trúc hoặc cơ quan được phân cấp.','Quyết định phê duyệt QHCT 1/500 hoặc tổng mặt bằng; quy định quản lý xây dựng theo đồ án.','QHCT là “xương sống” cho đất, GPXD, bán hàng và cấp sổ; thay đổi QHCT sau này kéo theo điều chỉnh nhiều thủ tục.'),detail_law('Luật Nhà ở 2023 / văn bản hướng dẫn','Chương trình, kế hoạch phát triển nhà ở','27_2023_qh15_530121_full.md','Áp dụng cho dự án nhà ở, khu đô thị có sản phẩm nhà ở; kiểm tra dự án có nằm trong chương trình/kế hoạch phát triển nhà ở địa phương hay không.','Dự án nhà ở phải phù hợp chỉ tiêu, chương trình/kế hoạch phát triển nhà ở và các yêu cầu về loại hình nhà ở, dân số, hạ tầng xã hội.','Văn bản cập nhật kế hoạch phát triển nhà ở, thông tin quy hoạch, cơ cấu sản phẩm, chỉ tiêu dân số, nhà ở xã hội nếu có.','UBND cấp tỉnh, Sở Xây dựng và cơ quan chuyên môn về nhà ở.','Văn bản/căn cứ xác nhận hoặc cập nhật kế hoạch phát triển nhà ở để làm nền CTCTĐT/QHCT.','Thiếu bước này dễ bị ách ở CTCTĐT hoặc QHCT, nhất là dự án nhà ở thương mại/khu đô thị lớn.')],
'land':[detail_law('Luật Đất đai 2024','Điều 79, 116, 124, 126, 127, 153, 158, 160','31_2024_qh15_523642_full.md','Điều chỉnh toàn bộ nhóm thu hồi đất, bồi thường/GPMB, giao đất/thuê đất/chuyển mục đích, định giá đất và nghĩa vụ tài chính.','Có căn cứ thu hồi/giao/thuê/chuyển mục đích; dự án phù hợp quy hoạch/kế hoạch sử dụng đất; hoàn thành GPMB hoặc đủ điều kiện theo phân kỳ; xác định giá đất theo trường hợp.','Bản đồ ranh, hồ sơ cắm mốc, quyết định CTCTĐT/QHCT, phương án bồi thường, hồ sơ giao/thuê đất, hồ sơ xác định giá đất, chứng thư thẩm định giá nếu có.','UBND cấp tỉnh/cấp huyện, Sở TNMT, cơ quan thuế, hội đồng thẩm định giá đất, văn phòng đăng ký đất đai.','QĐ giao/thuê đất/chuyển mục đích; phê duyệt giá đất; thông báo nộp tiền; xác nhận hoàn thành nghĩa vụ tài chính; GCN QSDĐ dự án.','Nên tách 3 luồng: pháp lý đất, tài chính đất, đăng ký/cấp GCN; mỗi luồng có hồ sơ và timeline khác nhau.'),detail_law('NĐ 102/2024/NĐ-CP','Điều 44, 49, 55, 62','102_2024_nd-cp_603982_full.md','Hướng dẫn thủ tục cụ thể để chuyển từ chủ trương/quy hoạch sang quyết định giao đất, thuê đất, chuyển mục đích hoặc cơ chế thỏa thuận nhận QSDĐ.','Tùy route: không đấu giá/đấu thầu, đấu giá, đấu thầu hoặc thỏa thuận nhận QSDĐ; phải rà điều kiện riêng từng route.','Đơn đề nghị, hồ sơ dự án, quyết định CTCTĐT/CTNĐT, QHCT, bản đồ địa chính/HTVT, hồ sơ bồi thường/GPMB, tài liệu chứng minh điều kiện giao đất.','Cơ quan TNMT, UBND có thẩm quyền, tổ chức đấu giá, bên mời thầu nếu là dự án có sử dụng đất.','Quyết định/biên bản/phê duyệt theo từng route đất.','Đây là nghị định cần bám sát khi lập checklist thủ tục đất; tránh chỉ viện dẫn Luật Đất đai chung chung.'),detail_law('NĐ 103/2024/NĐ-CP','Nhóm quy định tiền sử dụng đất, tiền thuê đất','103_2024_nd-cp_550020_full.md','Dùng để tính và thu tiền sử dụng đất, tiền thuê đất, tiền nộp bổ sung, xử lý nghĩa vụ tài chính khi giao/thuê/chuyển mục đích/điều chỉnh quy hoạch.','Phải xác định đúng diện tích tính tiền, thời điểm xác định giá, hình thức thuê trả tiền hằng năm/một lần, các khoản được trừ nếu có.','QĐ đất, QHCT, hồ sơ giá đất, chứng thư thẩm định giá, phương án tài chính, hồ sơ chi phí bồi thường được trừ nếu đủ điều kiện.','Cơ quan thuế, Sở TNMT, Sở Tài chính, hội đồng thẩm định giá đất, UBND cấp tỉnh.','Thông báo nghĩa vụ tài chính; xác nhận hoàn thành nghĩa vụ tài chính; cơ sở cấp GCN dự án.','Sai thời điểm/diện tích/đơn giá làm lệch mô hình tài chính; nên khóa giả định giá đất ngay từ Pre-FS.')],
'design':[detail_law('Luật Xây dựng / NĐ quản lý dự án đầu tư xây dựng','Thiết kế cơ sở, TKKT, TKBVTC, GPXD','175_2024_nd-cp_619462_full.md','Áp dụng cho thẩm định BCNCKT/TKCS, TKKT/TKBVTC, quản lý thiết kế 2 bước/3 bước và cấp GPXD.','Phải có QHCT/chỉ tiêu, hồ sơ khảo sát, thiết kế đủ thành phần, thẩm tra nếu thuộc diện; công trình phải đáp ứng quy chuẩn, tiêu chuẩn, PCCC, môi trường, đấu nối.','Hồ sơ khảo sát, TKCS/BCNCKT, báo cáo thẩm tra, TKKT/TKBVTC, hồ sơ GPXD, văn bản PCCC/môi trường/đấu nối liên quan.','Cơ quan chuyên môn về xây dựng, Sở Xây dựng/Sở quản lý công trình chuyên ngành, UBND/cơ quan cấp GPXD được phân cấp.','Văn bản thẩm định thiết kế; GPXD; cơ sở để thông báo khởi công và thi công.','Thiết kế phải đi song song với đất, PCCC, môi trường, đấu nối; thiếu một văn bản kỹ thuật có thể làm chậm GPXD.'),detail_law('Luật Kiến trúc','Thi tuyển phương án kiến trúc','40_2019_qh14_387023_full.md','Áp dụng khi công trình thuộc diện phải thi tuyển phương án kiến trúc, như công trình công cộng cấp I/cấp đặc biệt hoặc công trình có yêu cầu kiến trúc đặc thù.','Xác định loại/cấp công trình, vị trí, yêu cầu quản lý kiến trúc của địa phương.','Nhiệm vụ thiết kế, hồ sơ mời thi tuyển, phương án kiến trúc, hội đồng/biên bản đánh giá.','Cơ quan quản lý kiến trúc/quy hoạch, chủ đầu tư tổ chức thi tuyển theo quy định.','Phương án kiến trúc được lựa chọn/phê duyệt làm đầu vào thiết kế tiếp theo.','Không phải dự án nào cũng cần thi tuyển; nhưng nếu thuộc diện mà bỏ qua sẽ vướng ở thiết kế/GPXD.')],
'env':[detail_law('Luật BVMT 2020/sửa đổi 2025','ĐTM, GPMT, vận hành thử nghiệm','72_2020_qh14_431147_full.md;146_2025_qh15_675259_full.md','Dùng để xác định dự án phải lập ĐTM, phải có GPMT, thời điểm cấp phép và nghĩa vụ vận hành thử nghiệm trạm XLNT/công trình xử lý chất thải.','Phân loại dự án theo nhóm, quy mô, yếu tố nhạy cảm môi trường; xác định giai đoạn phải có ĐTM/GPMT trước khởi công/vận hành theo trường hợp.','Báo cáo ĐTM, hồ sơ GPMT, thiết kế trạm XLNT, kế hoạch vận hành thử nghiệm, số liệu xả thải, đấu nối thoát nước.','Bộ TNMT/UBND cấp tỉnh/cơ quan được phân cấp tùy nhóm dự án và thẩm quyền.','Quyết định phê duyệt/kết quả thẩm định ĐTM; GPMT; chấp thuận vận hành thử nghiệm/kết quả môi trường nếu có.','Môi trường phải chạy sớm cùng thiết kế hạ tầng; trạm XLNT thường là điểm nghẽn khi nghiệm thu/bàn giao.'),detail_law('NĐ 131/2025/NĐ-CP','Điều 26','131_2025_nd-cp_660659_full.md','Xác định thẩm quyền Chủ tịch UBND cấp tỉnh trong cấp GPMT đối với dự án/cơ sở nhóm I, II, III thuộc phụ lục tương ứng.','Dự án thuộc nhóm và thẩm quyền địa phương; hồ sơ GPMT đầy đủ theo loại hình hoạt động và công trình bảo vệ môi trường.','Đơn đề nghị GPMT, báo cáo đề xuất cấp GPMT, hồ sơ pháp lý dự án, thiết kế/công trình môi trường.','Chủ tịch UBND cấp tỉnh/cơ quan môi trường được giao tham mưu.','GPMT làm điều kiện cho thi công/vận hành theo trường hợp.','Cần chốt thẩm quyền sớm để tránh nộp sai cơ quan.')],
'pccc':[detail_law('Luật PCCC và văn bản hướng dẫn','Ý kiến giải pháp PCCC, thẩm duyệt, nghiệm thu PCCC','55_2024_qh15_650673_full.md','Áp dụng cho công trình/hạng mục thuộc diện quản lý PCCC: xin ý kiến giải pháp ở TKCS, thẩm duyệt ở TKKT/TKBVTC, nghiệm thu hệ thống trước đưa vào sử dụng.','Công trình thuộc danh mục/diện phải thẩm duyệt, nghiệm thu PCCC; thiết kế phải đáp ứng quy chuẩn PCCC, thoát nạn, cấp nước chữa cháy, báo cháy/chữa cháy.','Hồ sơ thiết kế PCCC, TKCS/TKKT/TKBVTC, thuyết minh, bản vẽ, tài liệu kỹ thuật hệ thống, biên bản nghiệm thu với nhà thầu.','Cơ quan Cảnh sát PCCC và CNCH có thẩm quyền.','Văn bản góp ý giải pháp PCCC; giấy/văn bản thẩm duyệt thiết kế PCCC; văn bản nghiệm thu PCCC.','PCCC là điều kiện cứng cho nghiệm thu, bàn giao, vận hành; không nên để sau thiết kế kỹ thuật mới xử lý.')],
'business':[detail_law('Luật KDBĐS 2023','Điều 6; nhóm quy định BĐS HTTTL','29_2023_qh15_530116_full.md','Dùng để kiểm tra điều kiện đưa dự án/BĐS vào kinh doanh, bán/cho thuê mua BĐS hình thành trong tương lai, công khai thông tin và hợp đồng.','Có pháp lý dự án, đất, quy hoạch, thiết kế/GPXD, nghiệm thu mốc HTKT/phần móng theo loại sản phẩm; công khai thông tin trước khi giao dịch; bảo lãnh nếu là nhà ở HTTTL thuộc diện.','Hồ sơ pháp lý dự án, QĐ đất/GCN, QHCT, GPXD, biên bản nghiệm thu mốc, mẫu HĐMB, văn bản bảo lãnh, tài liệu công khai thông tin.','Sở Xây dựng/cơ quan quản lý nhà ở và thị trường BĐS; ngân hàng bảo lãnh; chủ đầu tư.','Thông báo/đủ điều kiện bán; bộ HĐMB; hồ sơ công khai; cơ sở mở bán và ký HĐMB.','Booking/rumor/giữ chỗ phải kiểm soát để không biến thành huy động vốn trái điều kiện.'),detail_law('NĐ 96/2024/NĐ-CP','Quy định chi tiết Luật KDBĐS','96_2024_nd-cp_600395_full.md','Chi tiết hóa điều kiện, hồ sơ, công khai thông tin và quản lý giao dịch BĐS theo từng loại sản phẩm/dự án.','Sản phẩm đưa vào kinh doanh phải đúng loại được phép, đủ hồ sơ pháp lý và thông tin công khai.','Bộ pháp lý bán hàng, danh mục sản phẩm, hợp đồng mẫu, thông tin dự án/sản phẩm, tiến độ thanh toán.','Sở Xây dựng/cơ quan quản lý thị trường BĐS địa phương.','Cơ sở vận hành bán hàng, kiểm tra hậu kiểm và xử lý tranh chấp nếu có.','Dùng nghị định này để lập checklist bán hàng, không chỉ dựa vào Luật KDBĐS.'),detail_law('Thông tư NHNN về bảo lãnh nhà ở HTTTL','Bảo lãnh nghĩa vụ tài chính CĐT','49_2024_tt-nhnn_629634_full.md','Áp dụng cho bảo lãnh trong bán/cho thuê mua nhà ở hình thành trong tương lai, bảo vệ người mua nếu CĐT không bàn giao đúng cam kết.','Ngân hàng đủ điều kiện phát hành bảo lãnh; dự án/sản phẩm đủ điều kiện bán; phạm vi, thời hạn và nghĩa vụ bảo lãnh rõ.','Thỏa thuận cấp bảo lãnh giữa CĐT và ngân hàng, mẫu cam kết/chứng thư bảo lãnh, danh sách sản phẩm/khách hàng.','Ngân hàng thương mại phát hành bảo lãnh; CĐT cung cấp cho khách hàng theo giao dịch.','Cam kết/chứng thư bảo lãnh cho người mua; điều kiện mở bán an toàn hơn.','Phải kiểm tra từng chứng thư/cam kết, không chỉ có “văn bản nguyên tắc” với ngân hàng.')],
'handover':[detail_law('NĐ quản lý chất lượng công trình','Nghiệm thu, kiểm tra nghiệm thu, hoàn thành đưa vào sử dụng','06_2021_nd-cp_469018_full.md;144_2025_nd-cp_660606_full.md','Áp dụng cho nghiệm thu giai đoạn, nghiệm thu hoàn thành với nhà thầu, kiểm tra công tác nghiệm thu của CQNN và đưa công trình vào sử dụng.','Công trình thi công đúng thiết kế/GPXD, có hồ sơ hoàn công, kết quả thí nghiệm/kiểm định, nghiệm thu PCCC/môi trường/đấu nối nếu liên quan.','Nhật ký, bản vẽ hoàn công, biên bản nghiệm thu, hồ sơ chất lượng vật liệu, kết quả thí nghiệm, hồ sơ PCCC/GPMT/đấu nối.','CĐT, nhà thầu, tư vấn giám sát, cơ quan chuyên môn về xây dựng/CQNN kiểm tra nghiệm thu.','Biên bản nghiệm thu hoàn thành; văn bản kiểm tra công tác nghiệm thu; điều kiện bàn giao/vận hành.','Nghiệm thu là cầu nối giữa xây dựng, bán hàng, bàn giao và cấp GCN; thiếu hồ sơ chất lượng sẽ nghẽn toàn bộ phần sau.'),detail_law('NĐ 101/2024/NĐ-CP','Đăng ký đất đai, cấp GCN','101_2024_nd-cp_613131_full.md','Áp dụng cho đăng ký đất đai, tài sản gắn liền với đất, cấp GCN dự án và cấp GCN cho người mua sau bàn giao.','Hoàn thành nghĩa vụ tài chính, có hồ sơ hoàn công/nghiệm thu, bản vẽ sơ đồ nhà đất, đủ điều kiện chuyển quyền/cấp sổ, xử lý giải chấp nếu có.','Đơn đăng ký/cấp GCN, QĐ đất/GCN dự án, hồ sơ hoàn công, biên bản bàn giao, bản vẽ phân lô/sơ đồ nhà ở đất ở, chứng từ tài chính.','Văn phòng đăng ký đất đai, cơ quan TNMT, UBND có thẩm quyền, cơ quan thuế khi phát sinh nghĩa vụ.','GCN QSDĐ, QSH nhà ở và tài sản khác gắn liền với đất cho dự án/người mua.','Thời gian cấp sổ thường bị kéo bởi nghĩa vụ tài chính, hoàn công, giải chấp, sai khác diện tích/hiện trạng.')]
}
# replace by doc group markers in each law_basis
for ph in data['phases']:
    for it in ph['items']:
        docs=' '.join(l.get('doc','') for l in it.get('legal_basis',[])).lower()
        new=[]
        if any(k in docs for k in ['đầu tư','đất đai']) and ph['id'] in ['I','III']: new+=basis['pre']
        if ph['id']=='IV': new+=basis['planning']+basis['design'][:1]
        if ph['id'] in ['II','V']: new+=basis['land']
        if ph['id']=='VI': new+=basis['design']+basis['env']+basis['pccc']
        if ph['id']=='VII': new+=basis['design']+basis['handover'][:1]
        if ph['id']=='VIII': new+=basis['business']
        if ph['id']=='IX': new+=basis['handover']+basis['pccc']+basis['env']
        if ph['id'] in ['X','XI']: new+=basis['handover']+basis['business'][:1]
        it['legal_basis']=new or it.get('legal_basis',[])

data['legal_basis_detail_level']='detailed_working_summary_v2'
data['legal_basis_note']='Mỗi căn cứ được tóm tắt theo: áp dụng trong flow, điều kiện/checkpoint, hồ sơ, thẩm quyền, output pháp lý và lưu ý thực hiện.'
backup=p.with_suffix('.before_detailed_basis.json')
shutil.copy2(p,backup)
p.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
for out in [base/'FINAL_BDS_LEGAL_WEB/tpre_bds_flow.json', pathlib.Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\deploy_bds_legal_process\public\bds-legal-process\tpre_bds_flow.json')]: out.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
print('patched',p)
