from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
# css for deep howto
s=s.replace('.formulaBox{grid-column:1/-1;border:1px solid #ffec99;background:#fffdf3;border-radius:18px;padding:16px}', '.howtoBox{grid-column:1/-1;border:1px solid #c3fae8;background:#f6fffb;border-radius:18px;padding:16px}.howtoBox h4{margin:0 0 12px;text-transform:uppercase;font-size:12px;letter-spacing:.08em;color:#087f5b}.howtoGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.howtoItem{background:white;border:1px solid #d8f5e5;border-radius:14px;padding:12px}.howtoItem b{display:block;color:#087f5b;margin-bottom:6px}.formulaBox{grid-column:1/-1;border:1px solid #ffec99;background:#fffdf3;border-radius:18px;padding:16px}')
s=s.replace('@media(max-width:900px){.expertGrid,.formulaGrid,.checkGrid{grid-template-columns:1fr}}', '@media(max-width:900px){.expertGrid,.formulaGrid,.checkGrid,.howtoGrid{grid-template-columns:1fr}}')
s=s.replace('${fullChecklistBlock(it.code||p.id,p.id)}${gapBlock(it.code||p.id,p.id)}<div class="dossier">','${fullChecklistBlock(it.code||p.id,p.id)}${gapBlock(it.code||p.id,p.id)}${howtoBlock(it.code||p.id,p.id)}<div class="dossier">')
insert=r'''
function howtoBlock(code,id){const arr=howtoFor(code,id); if(!arr.length) return ''; return `<div class="howtoBox"><h4>Hướng dẫn thực hiện sâu — làm như thế nào</h4><div class="howtoGrid">${arr.map(x=>`<div class="howtoItem"><b>${esc(x.title)}</b>${lines(x.items)}</div>`).join('')}</div></div>`}
function howtoFor(code,id){const data={
III:[['Bước 1 — Chọn route NĐT',['Lập bảng so sánh 4 route: đấu giá QSDĐ, đấu thầu lựa chọn NĐT, chấp thuận NĐT do có/nhận QSDĐ, M&A/chuyển nhượng dự án.','Với mỗi route ghi: điều kiện áp dụng, cơ quan chủ trì, hồ sơ, timeline, rủi ro, chi phí, khả năng kiểm soát.','Không chọn route theo mong muốn kinh doanh; chọn theo tình trạng đất/quy hoạch/pháp luật.']],['Bước 2 — Hồ sơ năng lực',['Lập bảng vốn chủ sở hữu, khả năng huy động vốn, báo cáo tài chính, cam kết tín dụng/bảo lãnh nếu có.','Kiểm tra năng lực thực hiện dự án tương tự, pháp lý doanh nghiệp, ngành nghề, người đại diện, quyết định nội bộ.','Tách hồ sơ chứng minh năng lực cho CTCTĐT và hồ sơ dự thầu/đấu giá nếu route yêu cầu.']],['Bước 3 — Khóa nội dung CTCTĐT',['Mục tiêu, quy mô, diện tích, dân số, sản phẩm, tổng vốn, tiến độ, phân kỳ, nhu cầu đất, công nghệ/môi trường nếu có.','Đối chiếu với QHCT/kế hoạch nhà ở/kế hoạch sử dụng đất để tránh phải điều chỉnh.']],['Bước 4 — Sau khi có văn bản',['Lập checklist điều kiện hậu chấp thuận: ký quỹ, giao đất, QHCT, thiết kế, môi trường, PCCC, GPXD.','Gắn mỗi điều kiện với owner, deadline, hồ sơ cần chuẩn bị và rủi ro nếu trễ.']]],
IV:[['Bước 1 — Rà chỉ tiêu đầu vào',['Lấy quy hoạch cấp trên, ranh đất, hiện trạng, chỉ tiêu dân số/tầng cao/mật độ/hệ số sử dụng đất.','Kiểm tra chỉ giới đường đỏ, hành lang bảo vệ, cao độ nền, thoát nước, giao thông kết nối, đất HTXH/cây xanh/bãi xe.']],['Bước 2 — Lập nhiệm vụ/đồ án',['Nhiệm vụ QHCT phải nêu phạm vi, mục tiêu, chỉ tiêu, yêu cầu hạ tầng, yêu cầu đánh giá môi trường/chiến lược nếu có.','Đồ án cần thuyết minh, bản vẽ tổng mặt bằng, sử dụng đất, kiến trúc cảnh quan, HTKT, quy định quản lý.']],['Bước 3 — Kiểm tra ngược từ pháp lý sau',['QHCT có đủ để lập TKCS/TKBVTC và GPXD không.','Có đủ cơ sở để giao đất/định giá đất không.','Có khớp sản phẩm bán hàng, phân lô/cấp sổ, PCCC, giao thông không.']],['Bước 4 — Quản lý thay đổi',['Mọi thay đổi chỉ tiêu phải đánh giá ảnh hưởng đến đất, nghĩa vụ tài chính, GPXD, hợp đồng bán hàng và cấp GCN.']]],
VI:[['Bước 1 — Ma trận giấy phép kỹ thuật',['Lập ma trận theo từng hạng mục: HTKT, HTXH, thấp tầng, cao tầng, trạm XLNT, công trình tạm.','Cột kiểm tra: TKCS, TKKT/TKBVTC, PCCC, môi trường, đấu nối, GPXD, khởi công, nghiệm thu.']],['Bước 2 — GPXD',['Kiểm tra công trình có thuộc diện miễn GPXD không; nếu không, xác định cơ quan cấp phép.','Hồ sơ phải khớp QHCT, quyền sử dụng đất, thiết kế đã thẩm định, PCCC/môi trường/đấu nối liên quan.','Sau GPXD phải kiểm soát điều kiện khởi công và thông báo khởi công.']],['Bước 3 — PCCC',['Từ TKCS phải xin/kiểm tra giải pháp PCCC; sang TKBVTC phải thẩm duyệt thiết kế PCCC.','Trong thi công phải lưu hồ sơ vật tư, thiết bị, nghiệm thu hệ thống.','Trước đưa vào sử dụng phải nghiệm thu PCCC với cơ quan có thẩm quyền nếu thuộc diện.']],['Bước 4 — ĐTM/GPMT/XLNT',['Xác định nhóm dự án và thời điểm cần ĐTM/GPMT.','Thiết kế trạm XLNT và kế hoạch vận hành thử phải đi cùng tiến độ nghiệm thu.','Không chờ tới lúc bàn giao mới xử lý GPMT/vận hành thử.']]],
VIII:[['Bước 1 — Ma trận điều kiện bán theo sản phẩm',['Tách thấp tầng, cao tầng/căn hộ, đất nền nếu có, HTKT, HTXH.','Mỗi loại ghi điều kiện đất, QHCT, GPXD, nghiệm thu mốc, bảo lãnh, công khai thông tin, mẫu HĐMB.']],['Bước 2 — Hồ sơ thông báo đủ điều kiện',['Chuẩn bị bộ pháp lý dự án, GCN/QĐ đất, GPXD, biên bản nghiệm thu phần móng/HTKT, bảo lãnh, mẫu HĐMB, thông tin công khai.','Đối chiếu từng sản phẩm dự kiến bán với mốc nghiệm thu tương ứng.']],['Bước 3 — Kiểm soát marketing/sales',['Lập danh sách câu được nói/không được nói theo trạng thái pháp lý.','Booking/giữ chỗ/đặt cọc phải được pháp chế duyệt để tránh huy động vốn trái luật.','Tiến độ thanh toán không được vượt mốc pháp lý và hợp đồng.']],['Bước 4 — Sau khi đủ điều kiện',['Lưu bằng chứng công khai thông tin, văn bản đủ điều kiện, bảo lãnh, HĐMB mẫu, phiên bản sales kit được phê duyệt.']]],
X:[['Bước 1 — Chuẩn bị trước bàn giao',['Đối chiếu nghiệm thu hoàn thành, PCCC, môi trường, đấu nối, hoàn công, nghĩa vụ tài chính.','Chuẩn hóa biên bản bàn giao, danh mục thiết bị, bảo hành, diện tích, phần chung/riêng.']],['Bước 2 — Hồ sơ cấp GCN khách hàng',['Tách hồ sơ CĐT phải chuẩn bị và hồ sơ khách hàng phải ký/nộp.','CĐT: pháp lý dự án, GCN/QĐ đất, hoàn công, bản vẽ sơ đồ, nghĩa vụ tài chính, giải chấp.','Khách hàng: HĐMB, chứng từ thanh toán, giấy tờ pháp lý, tờ khai/lệ phí nếu có.']],['Bước 3 — Xử lý nghĩa vụ tài chính/phát sinh',['Theo dõi phiếu chuyển thông tin sang thuế, thông báo thu, khoản phải nộp bổ sung nếu có.','Nếu sai diện tích/sơ đồ phải điều chỉnh trước khi nộp hàng loạt.']],['Bước 4 — Quản trị cam kết cấp sổ',['Lập dashboard từng căn/lô: đủ hồ sơ, đang nộp, bổ sung, đã có GCN, đã bàn giao GCN.','Cảnh báo sớm các căn bị vướng giải chấp, tranh chấp, thiếu chữ ký, thiếu chứng từ.']]]
}; return (data[id]||[]).map(x=>({title:x[0],items:x[1]}))}
'''
s=s.replace('function gapBlock',insert+'\nfunction gapBlock')
p.write_text(s,encoding='utf-8')
print('patched deep howto modules')
