from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
start=s.index('function timelineFor(id){')
end=s.index('function laws(a){', start)
replacement=r'''function timelineFor(id){return {
I:['Bước 1: thu thập hồ sơ đất, quy hoạch, pháp lý chủ đất/dự án, thông tin thị trường và hạn chế pháp lý hiện hữu.','Bước 2: dựng ma trận route đầu tư/đất: đấu giá, đấu thầu, chấp thuận NĐT, tự có đất, M&A/chuyển nhượng dự án.','Bước 3: lập product brief, tổng tiến độ sơ bộ, ngân sách dự án/TMĐT, phân kỳ đầu tư và danh mục rủi ro cần xử lý trước khi đặt cọc.','Thời gian tham khảo nội bộ: 1–4 tuần nếu hồ sơ tương đối đầy đủ; dự án M&A/pháp lý phức tạp có thể lâu hơn.'],
II:['Bước 1: xác lập ranh dự án, hiện trạng sử dụng đất, chủ sử dụng, tài sản trên đất và hồ sơ GCN.','Bước 2: lựa chọn cơ chế GPMB: Nhà nước thu hồi đất, tự thỏa thuận nhận QSDĐ, hoán đổi/điều chỉnh đất công hoặc M&A.','Bước 3: lập/ thẩm định phương án bồi thường, hỗ trợ, tái định cư, kế hoạch vốn và lịch chi trả.','Bước 4: hoàn tất kiểm đếm, bồi thường, chỉnh lý hồ sơ địa chính và xác nhận hoàn thành GPMB theo phân kỳ.','Thời gian: thường là đường găng, phụ thuộc số lượng hộ dân, khiếu nại, đất công/xen kẹt và ngân sách bồi thường.'],
III:['Bước 1: xác định dự án thuộc diện CTCTĐT/CTNĐT và thẩm quyền chấp thuận.','Bước 2: chuẩn bị hồ sơ năng lực NĐT, tài liệu đất đai, mục tiêu/quy mô/tiến độ, sơ bộ phương án thiết kế và tổng vốn.','Bước 3: xử lý song song các văn bản nền: kế hoạch nhà ở, kế hoạch sử dụng đất, đấu nối/giao thông/PCCC/môi trường nếu cần.','Bước 4: nhận quyết định CTCTĐT/CTNĐT, công nhận/chấp thuận CĐT và thực hiện ký quỹ/bảo đảm dự án.','Thời gian: phụ thuộc thẩm quyền, hình thức chọn NĐT và mức độ đầy đủ của quy hoạch/đất/hồ sơ năng lực.'],
IV:['Bước 1: kiểm tra quy hoạch cấp trên, chỉ tiêu quy hoạch, chỉ tiêu dân số, hạ tầng và ràng buộc kiến trúc.','Bước 2: lập nhiệm vụ QHCT hoặc quy hoạch tổng mặt bằng; tổ chức thiết kế ý tưởng/design brief.','Bước 3: lập đồ án QHCT 1/500, lấy ý kiến, thẩm định và trình phê duyệt.','Bước 4: phê duyệt quy định quản lý xây dựng theo đồ án; cập nhật bản đồ hiện trạng/cắm mốc phục vụ đất và thiết kế.','Thời gian: phụ thuộc quy hoạch cấp trên, số vòng góp ý, yêu cầu điều chỉnh chỉ tiêu và thẩm quyền phê duyệt.'],
V:['Bước 1: chuẩn bị bản đồ HTVT, cắm mốc, QHCT, hồ sơ GPMB và hồ sơ giao/thuê đất/chuyển mục đích.','Bước 2: nộp/hoàn thiện hồ sơ quyết định giao đất, thuê đất hoặc chuyển mục đích sử dụng đất theo route đã chọn.','Bước 3: tổ chức xác định giá đất, chứng thư/thẩm định giá, trình phê duyệt giá đất và thông báo nghĩa vụ tài chính.','Bước 4: hoàn tất nộp tiền, xác nhận nghĩa vụ tài chính và cấp GCN QSDĐ dự án.','Thời gian: phải tách riêng timeline quyết định đất và timeline xác định giá đất/nghĩa vụ tài chính; đây thường là điểm nghẽn lớn.'],
VI:['Bước 1: khảo sát địa hình, địa chất, hạ tầng ngầm, công trình lân cận; lập TKCS/BCNCKT.','Bước 2: xin ý kiến/thẩm định TKCS, giải pháp PCCC, đấu nối hạ tầng, giao thông, cấp điện, cấp nước, thoát nước.','Bước 3: lập TKKT/TKBVTC, thẩm tra/thẩm định thiết kế, thẩm duyệt PCCC, hoàn thiện ĐTM/GPMT.','Bước 4: xin GPXD, thông báo khởi công và kiểm soát điều kiện khởi công.','Thời gian: các thủ tục kỹ thuật phải chạy song song; thiếu PCCC/môi trường/đấu nối sẽ kéo chậm GPXD và nghiệm thu.'],
VII:['Bước 1: tổ chức thi công theo GPXD/TKBVTC: san nền, HTKT, phần ngầm, phần thân, hoàn thiện, tiện ích/cảnh quan.','Bước 2: quản lý hồ sơ chất lượng: nhật ký, vật liệu, thí nghiệm, biên bản nghiệm thu giai đoạn, bản vẽ hoàn công.','Bước 3: nghiệm thu các mốc HTKT/phần móng/phần ngầm tương ứng với điều kiện bán hàng và nghiệm thu hoàn thành.','Thời gian: theo tiến độ xây dựng/phân kỳ; hồ sơ chất lượng phải lập từ đầu, không gom cuối dự án.'],
VIII:['Bước 1: kiểm tra điều kiện bán/huy động vốn theo từng loại sản phẩm: thấp tầng, cao tầng, căn hộ, HTKT, HTTTL.','Bước 2: chuẩn bị mẫu HĐMB, bảo lãnh ngân hàng, hồ sơ công khai thông tin dự án, bản vẽ sản phẩm và tiến độ thanh toán.','Bước 3: hoàn tất nghiệm thu mốc bắt buộc như HTKT/phần móng/phần ngầm tùy sản phẩm.','Bước 4: gửi/nhận thông báo đủ điều kiện bán và triển khai marketing, bán hàng, ký HĐMB.','Thời gian: không lấy theo kế hoạch marketing; phải khóa theo mốc nghiệm thu và văn bản đủ điều kiện bán.'],
IX:['Bước 1: nghiệm thu hoàn thành với nhà thầu, tư vấn giám sát và CĐT; hoàn thiện hồ sơ hoàn công/chất lượng.','Bước 2: nghiệm thu PCCC, môi trường/GPMT/vận hành thử XLNT nếu thuộc diện.','Bước 3: đề nghị CQNN kiểm tra công tác nghiệm thu và xác nhận đủ điều kiện đưa công trình vào sử dụng.','Thời gian: phụ thuộc độ sạch của hồ sơ hoàn công, PCCC, môi trường, đấu nối và tồn tại hiện trường.'],
X:['Bước 1: bàn giao HTKT/HTXH cho CQNN hoặc đơn vị quản lý theo quy định/dự án.','Bước 2: nghiệm thu bàn giao nhà cho khách hàng; hoàn thiện biên bản bàn giao, hồ sơ căn, hồ sơ bảo hành.','Bước 3: lập hồ sơ cấp GCN: bản vẽ phân lô/sơ đồ nhà đất, hoàn công, nghĩa vụ tài chính, giải chấp, hồ sơ người mua.','Bước 4: nộp và theo dõi cấp GCN QSDĐ, QSH nhà ở và tài sản gắn liền với đất.','Thời gian: phụ thuộc nghĩa vụ tài chính, hoàn công, giải chấp ngân hàng, sai khác diện tích và hồ sơ khách hàng.'],
XI:['Bước 1: tiếp nhận vận hành, danh mục tài sản/hồ sơ pháp lý, quy trình bảo hành và danh mục tồn tại.','Bước 2: quản lý bảo hành nhà thầu và bảo hành với khách hàng theo từng hạng mục.','Bước 3: xử lý hậu kiểm, khiếu nại, cập nhật hồ sơ vận hành và dữ liệu dự án.','Thời gian: theo thời hạn bảo hành, vận hành và cam kết hợp đồng/quy định pháp luật liên quan.']
}[id]||[]}
function checkFor(id){return {
I:['Không quyết định đầu tư nếu chưa xác định được route đất và route lựa chọn NĐT.','Phải có bản đồ ranh/hiện trạng, quy hoạch, GCN/chủ đất, đất công/xen kẹt, hạn chế chuyển nhượng, tranh chấp/thế chấp.','Tách rõ phần pháp lý chắc chắn, phần giả định và phần cần điều kiện tiên quyết.'],
II:['Rủi ro lớn: đất chưa sạch, hộ dân không đồng thuận, đất công xen kẹt, tài sản trên đất, mồ mả/hạ tầng ngầm, sai lệch diện tích.','Phải kiểm soát ngân sách GPMB và mốc hoàn tất theo phân kỳ để không nghẽn giao đất/thi công.'],
III:['Hình thức chọn NĐT phải khớp với trạng thái đất và quy hoạch.','Năng lực tài chính/NĐT phải chứng minh được; vốn chủ sở hữu, báo cáo tài chính, bảo lãnh/ký quỹ cần chuẩn bị sớm.','CTCTĐT phải khớp mục tiêu, quy mô, tiến độ, sơ bộ cơ cấu sản phẩm; sai sau này phải điều chỉnh.'],
IV:['QHCT phải khớp chỉ tiêu cấp trên và khả năng kinh doanh thực tế.','Cần khóa chỉ tiêu dân số, tầng cao, mật độ, đất ở, đất hạ tầng, đất cây xanh, giao thông, HTXH.','QHCT là đầu vào của đất, thiết kế, GPXD, bán hàng và cấp sổ.'],
V:['Không chỉ cần quyết định giao/thuê đất, mà phải có nghĩa vụ tài chính và GCN để giảm rủi ro bán hàng/cấp sổ.','Giá đất là rủi ro tài chính lớn; cần cập nhật lại mô hình TMĐT/lợi nhuận khi có kết quả giá đất.'],
VI:['Thiết kế phải đồng bộ với QHCT, đất, PCCC, môi trường, đấu nối và sản phẩm kinh doanh.','Hồ sơ PCCC/GPMT không được để cuối vì ảnh hưởng nghiệm thu đưa vào sử dụng.'],
VII:['Thi công sai GPXD/TKBVTC sẽ kéo theo điều chỉnh, phạt, không nghiệm thu hoặc khó cấp sổ.','Hồ sơ chất lượng phải lưu đầy đủ từ ngày đầu thi công.'],
VIII:['Không được bán/huy động vốn khi chưa đủ điều kiện pháp lý theo Luật KDBĐS.','Phân biệt giữ chỗ/booking/đặt cọc/huy động vốn; nội dung truyền thông không được vượt điều kiện pháp lý.','Bảo lãnh nhà ở HTTTL phải kiểm tra từng chứng thư/cam kết cho khách hàng.'],
IX:['Điều kiện đưa vào sử dụng không chỉ là xây xong; cần đủ hoàn công, PCCC, môi trường, đấu nối, chất lượng.','Các tồn tại hiện trường nhỏ cũng có thể làm chậm văn bản nghiệm thu.'],
X:['Cấp sổ bị nghẽn bởi nghĩa vụ tài chính, sai lệch diện tích, giải chấp, thiếu bản vẽ/hoàn công hoặc hồ sơ người mua.','Cần chuẩn hóa hồ sơ bàn giao và hồ sơ cấp GCN ngay trước khi bàn giao hàng loạt.'],
XI:['Bảo hành nhà thầu và bảo hành khách hàng phải có owner, SLA và hồ sơ nghiệm thu sửa lỗi.','Dữ liệu vận hành/cư dân/tài sản phải bàn giao đầy đủ cho đơn vị quản lý.']
}[id]||[]}
'''
s=s[:start]+replacement+s[end:]
p.write_text(s,encoding='utf-8')
print('patched detail depth')
