from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
needle="""III:[['Bước 1 — Chọn route NĐT',['Lập bảng so sánh 4 route: đấu giá QSDĐ, đấu thầu lựa chọn NĐT, chấp thuận NĐT do có/nhận QSDĐ, M&A/chuyển nhượng dự án.','Với mỗi route ghi: điều kiện áp dụng, cơ quan chủ trì, hồ sơ, timeline, rủi ro, chi phí, khả năng kiểm soát.','Không chọn route theo mong muốn kinh doanh; chọn theo tình trạng đất/quy hoạch/pháp luật.']]"""
insert="""I:[['Bước 1 — Lập legal DD map',['Lập danh mục tài liệu phải thu thập: GCN, bản đồ, quy hoạch, hiện trạng, hợp đồng, chấp thuận cũ, giấy phép cũ, thế chấp/tranh chấp.','Đánh dấu từng tài liệu: đã có, chưa có, nghi ngờ, cần xác minh CQNN, cần điều kiện trong hợp đồng.','Tách nhóm rủi ro: quyền đất, quy hoạch, đầu tư, xây dựng, môi trường, kinh doanh, tài chính đất.']],['Bước 2 — Route pháp lý sơ bộ',['Dựng cây quyết định: tự có đất/nhận chuyển nhượng QSDĐ/M&A dự án/đấu giá/đấu thầu/chấp thuận NĐT.','Với mỗi route ghi thủ tục bắt buộc, điều kiện tiên quyết, thời gian, chi phí, xác suất thành công.','Chốt route khuyến nghị và route dự phòng.']],['Bước 3 — Financial/legal assumptions',['Liệt kê giả định pháp lý ảnh hưởng model: diện tích tính tiền đất, nghĩa vụ tài chính, GPMB, hệ số sử dụng đất, số lượng sản phẩm, điều kiện bán hàng.','Mọi giả định phải có mức tin cậy: chắc / cần xác minh / rủi ro cao.']],['Bước 4 — Điều kiện giao dịch/M&A',['Đưa điều kiện pháp lý vào term sheet/SPA: điều kiện tiên quyết, hồ sơ phải bàn giao, cam kết/bồi thường, escrow, quyền rút lui nếu pháp lý sai.','Không ký/mua nếu không có cơ chế xử lý rủi ro đất, quy hoạch, nghĩa vụ tài chính và tranh chấp.']]],
II:[['Bước 1 — Bản đồ chủ sử dụng đất',['Lập landowner matrix: thửa đất, chủ sử dụng, diện tích, loại đất, GCN, tài sản trên đất, tình trạng thế chấp/tranh chấp.','Đánh dấu nhóm dễ/khó thương lượng, nhóm phải thu hồi, nhóm đất công/xen kẹt.']],['Bước 2 — Phương án GPMB/thu mua',['Tách kịch bản Nhà nước thu hồi đất và kịch bản tự thỏa thuận.','Lập ngân sách bồi thường, hỗ trợ, TĐC, chi phí phát sinh, mốc chi tiền và điều kiện giải ngân.','Tạo bảng theo dõi từng hộ/thửa: tiếp xúc, đàm phán, ký, chi trả, bàn giao, chỉnh lý.']],['Bước 3 — Hồ sơ pháp lý GPMB',['Bản đồ ranh, kiểm kê, phương án bồi thường, quyết định thu hồi nếu có, xác nhận hoàn thành bồi thường, hồ sơ chỉnh lý GCN.','Tất cả chứng từ chi trả phải đủ điều kiện để xem xét khấu trừ/ghi nhận vào nghĩa vụ tài chính nếu pháp luật cho phép.']],['Bước 4 — Rủi ro cần khóa',['Khiếu nại kéo dài, đất công, hạ tầng kỹ thuật hiện hữu, mồ mả/công trình tôn giáo, tài sản không có giấy tờ, người sử dụng đất không cư trú tại địa phương.','GPMB phải có owner và timeline riêng, không gộp chung vào tiến độ pháp lý tổng.']]],
"""+needle
s=s.replace(needle,insert)
needle2="""VIII:[['Bước 1 — Ma trận điều kiện bán theo sản phẩm'"""
insert2="""VII:[['Bước 1 — Ma trận phân kỳ thi công',['Chia theo hạng mục: san nền, giao thông, thoát nước mưa, thoát nước thải, cấp điện, cấp nước, thông tin liên lạc, trạm XLNT, phần ngầm, phần thân, hoàn thiện, cảnh quan.','Mỗi hạng mục gắn với TKBVTC, GPXD/miễn GPXD, nhà thầu, mốc nghiệm thu, hồ sơ chất lượng.']],['Bước 2 — Quản lý thay đổi trong thi công',['Mọi thay đổi thiết kế phải phân loại: thay đổi nội bộ, thay đổi phải thẩm tra/thẩm định lại, thay đổi phải điều chỉnh GPXD/QHCT/PCCC.','Không thi công theo shopdrawing/thay đổi nếu chưa rõ ảnh hưởng pháp lý.']],['Bước 3 — Hồ sơ chất lượng realtime',['Thiết lập checklist ngày/tuần: nhật ký, nghiệm thu vật liệu, nghiệm thu công việc, ảnh hiện trường, bản vẽ hoàn công cập nhật.','Hồ sơ không đủ từ đầu sẽ gây nghẽn nghiệm thu hoàn thành, bàn giao, cấp sổ.']],['Bước 4 — Mốc liên quan bán hàng',['Đánh dấu các mốc nghiệm thu phục vụ điều kiện bán HTTTL: HTKT, phần móng, phần ngầm, phần thân tùy sản phẩm.','Pháp chế/kinh doanh chỉ được dùng mốc nghiệm thu khi có biên bản/hồ sơ hợp lệ.']]],
"""+needle2
s=s.replace(needle2,insert2)
needle3="""}; return (data[id]||[]).map(x=>({title:x[0],items:x[1]}))}"""
insert3=""" ,
XI:[['Bước 1 — Bàn giao hồ sơ vận hành',['Tập hợp hồ sơ pháp lý hoàn công, nghiệm thu, PCCC, môi trường, đấu nối, bảo hành thiết bị, hướng dẫn vận hành.','Tạo danh mục tài sản bàn giao: hạ tầng, thiết bị, hệ thống kỹ thuật, khu chung/riêng, hồ sơ bảo trì.']],['Bước 2 — Quản lý bảo hành',['Tách bảo hành nhà thầu và bảo hành với khách hàng; quy định SLA tiếp nhận, kiểm tra, sửa lỗi, nghiệm thu sửa lỗi.','Mỗi lỗi phải có mã, ảnh, vị trí, nguyên nhân, đơn vị chịu trách nhiệm, deadline và trạng thái.']],['Bước 3 — Hậu kiểm pháp lý/vận hành',['Theo dõi yêu cầu của CQNN, phản ánh cư dân/khách hàng, tranh chấp phần chung/riêng, nghĩa vụ bảo trì/bảo hành.','Lưu hồ sơ xử lý khiếu nại để bảo vệ CĐT khi có tranh chấp.']],['Bước 4 — Đóng dự án pháp lý',['Chỉ coi đóng dự án khi: hoàn tất cấp GCN cơ bản, bàn giao hạ tầng/hồ sơ vận hành, xử lý tồn tại, bảo hành trong kiểm soát, hồ sơ lưu trữ đầy đủ.']]]
}; return (data[id]||[]).map(x=>({title:x[0],items:x[1]}))}"""
s=s.replace(needle3,insert3)
p.write_text(s,encoding='utf-8')
print('patched prefsgpmb construction ops')
