from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
# Add CSS for formula boxes
s=s.replace('.expertGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;grid-column:1/-1}', '.formulaBox{grid-column:1/-1;border:1px solid #ffec99;background:#fffdf3;border-radius:18px;padding:16px}.formulaBox h4{margin:0 0 10px;text-transform:uppercase;font-size:12px;letter-spacing:.08em;color:#b77900}.formulaGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.formulaItem{border:1px solid #ffe8a3;background:white;border-radius:14px;padding:12px}.formulaItem b{color:#8a5a00}.expertGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;grid-column:1/-1}')
s=s.replace('@media(max-width:900px){.expertGrid{grid-template-columns:1fr}}', '@media(max-width:900px){.expertGrid,.formulaGrid{grid-template-columns:1fr}}')
old='''<div class=\"section full\"><h4>Kết quả / output pháp lý</h4>${lines(it.outputs)}</div><div class=\"expertGrid\">'''
new='''<div class=\"section full\"><h4>Kết quả / output pháp lý</h4>${lines(it.outputs)}</div>${formulaBlock(it.code||p.id,p.id)}<div class=\"expertGrid\">'''
s=s.replace(old,new)
insert=r'''
function formulaBlock(code,id){const arr=formulaFor(code,id); if(!arr.length) return ''; return `<div class="formulaBox"><h4>Cách tính / mô hình nghĩa vụ tài chính</h4><div class="formulaGrid">${arr.map(x=>`<div class="formulaItem"><b>${esc(x.title)}</b><div class="line">${esc(x.text)}</div></div>`).join('')}</div></div>`}
function formulaFor(code,id){if(code==='V-O.1'||id==='V') return [
{title:'1. Xác định route tính tiền',text:'Tách theo từng trường hợp: giao đất có thu tiền sử dụng đất; thuê đất trả tiền một lần; thuê đất trả tiền hằng năm; chuyển mục đích sử dụng đất; điều chỉnh quy hoạch/làm tăng hệ số sử dụng đất; công nhận QSDĐ. Mỗi route có công thức và thời điểm xác định giá khác nhau.'},
{title:'2. Tiền sử dụng đất khi giao đất/chuyển mục đích',text:'Công thức làm việc: Tiền sử dụng đất phải nộp = Diện tích tính thu × Giá đất tính thu theo mục đích sau giao/chuyển mục đích − Khoản được trừ/miễn/giảm/khấu trừ hợp lệ. Nếu phải xác định giá đất cụ thể thì dùng quyết định giá đất cụ thể; nếu thuộc trường hợp bảng giá đất thì dùng bảng giá đất.'},
{title:'3. Tiền thuê đất trả tiền một lần',text:'Công thức làm việc: Tiền thuê đất một lần = Diện tích thuê × Đơn giá thuê đất cho cả thời gian thuê − Khoản được trừ/miễn/giảm/khấu trừ hợp lệ. Cần kiểm tra thời hạn thuê, hình thức thuê, mục đích sử dụng và thời điểm tính tiền.'},
{title:'4. Tiền thuê đất hằng năm',text:'Công thức làm việc: Tiền thuê đất năm = Diện tích thuê × Đơn giá thuê đất hằng năm. Đơn giá có thể ổn định theo chu kỳ và điều chỉnh theo quy định. Riêng NĐ 87/2025/NĐ-CP trong corpus local quy định giảm 30% tiền thuê đất phải nộp của năm 2024 cho đối tượng đủ điều kiện.'},
{title:'5. Khoản được trừ / khấu trừ',text:'Cần kiểm tra chi phí bồi thường, GPMB, hỗ trợ/TĐC, tiền đã ứng, khoản miễn giảm, khoản khấu trừ theo quyết định hoặc quy định chuyên ngành. Không tự động trừ nếu hồ sơ/chứng từ/phê duyệt chưa đủ điều kiện.'},
{title:'6. Dữ liệu đầu vào bắt buộc',text:'Diện tích tính tiền; loại đất trước/sau; hình thức giao/thuê; thời hạn sử dụng; vị trí/bảng giá đất; quyết định giá đất cụ thể nếu có; hệ số/đơn giá; chi phí GPMB được trừ; ưu đãi/miễn/giảm; thời điểm phát sinh nghĩa vụ.'},
{title:'7. Output cần có',text:'Quyết định phê duyệt giá đất hoặc căn cứ bảng giá đất; thông báo nộp tiền của cơ quan thuế; chứng từ nộp tiền; xác nhận hoàn thành nghĩa vụ tài chính; dữ liệu cập nhật vào model TMĐT/lợi nhuận.'},
{title:'8. Check luật mới/NQ87',text:'Corpus hiện có 87_2025_NĐ-CP về giảm 30% tiền thuê đất năm 2024. Chưa thấy file NQ87 khác trong thư mục local. Cần bổ sung file NQ87 nếu anh đang nói đến nghị quyết/hướng dẫn mới khác để trích đúng điều khoản.'}
]; return []}
'''
marker='function applyFor(id)'
s=s.replace(marker,insert+'\n'+marker)
# Enrich V-O.1 legal basis with ND87 and calculation notes
s=s.replace("{doc:'NĐ 103/2024/NĐ-CP',article:'Nhóm quy định tiền sử dụng đất, tiền thuê đất',source_file:'103_2024_nd-cp_550020_full.md',points:['Áp dụng trong flow: Xác định tiền sử dụng đất, tiền thuê đất, thời điểm tính tiền và khoản được trừ nếu có.','Điều kiện/checkpoint: Xác định đúng diện tích, hình thức thuê/giao đất, thời điểm xác định giá, chi phí bồi thường được trừ.','Output pháp lý: Thông báo nghĩa vụ tài chính và căn cứ xác nhận hoàn tất nghĩa vụ.']}]}", "{doc:'NĐ 103/2024/NĐ-CP',article:'Nhóm quy định tiền sử dụng đất, tiền thuê đất',source_file:'103_2024_nd-cp_550020_full.md',points:['Áp dụng trong flow: Là căn cứ chính để tính tiền sử dụng đất, tiền thuê đất, khoản được trừ, miễn giảm và thông báo nghĩa vụ tài chính.','Điều kiện/checkpoint: Xác định đúng route giao đất/thuê đất/chuyển mục đích, diện tích tính tiền, mục đích sử dụng, thời hạn, thời điểm xác định giá, chi phí GPMB được trừ.','Hồ sơ/dữ liệu cần chuẩn bị: Quyết định đất, QHCT, bảng giá đất/quyết định giá đất cụ thể, hồ sơ chi phí GPMB, chứng từ đã nộp/ứng, hồ sơ miễn giảm nếu có.','Output pháp lý: Thông báo nghĩa vụ tài chính, quyết định/phiếu xác định tiền sử dụng đất/tiền thuê đất, căn cứ xác nhận hoàn tất nghĩa vụ.','Lưu ý thực hiện: Phải lập bảng tính riêng cho từng loại đất và từng hình thức sử dụng; không dùng một đơn giá bình quân cho toàn dự án nếu pháp luật yêu cầu tách.']},{doc:'NĐ 87/2025/NĐ-CP',article:'Điều 2, Điều 3, Điều 4, Điều 5',source_file:'87_2025_nd-cp_625558_full.md',points:['Áp dụng trong flow: Kiểm tra trường hợp giảm tiền thuê đất năm 2024 đối với người sử dụng đất được Nhà nước cho thuê đất trả tiền thuê đất hằng năm.','Điều kiện/checkpoint: Chỉ áp dụng cho tiền thuê đất phải nộp của năm 2024; không giảm tiền nợ các năm trước và tiền chậm nộp.','Cách tính: Mức giảm = 30% × tiền thuê đất phải nộp năm 2024 sau khi đã áp dụng miễn/giảm/khấu trừ khác nếu có.','Hồ sơ/dữ liệu cần chuẩn bị: Giấy đề nghị giảm tiền thuê đất theo mẫu; thông báo nộp tiền thuê đất năm 2024 nếu có.','Thời hạn/thủ tục: Nộp hồ sơ đến hết ngày 31/7/2025; cơ quan có thẩm quyền xác định số tiền giảm trong không quá 30 ngày từ khi nhận giấy đề nghị.','Lưu ý thực hiện: Đây là nghị định giảm tiền thuê đất năm 2024, không phải công thức chung cho toàn bộ tiền sử dụng đất của dự án.']}]}")
p.write_text(s,encoding='utf-8')
print('patched land finance calculation')
