from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
# Replace howtoFor function content more safely by injecting additional cases before return
needle="""X:[['Bước 1 — Chuẩn bị trước bàn giao',['Đối chiếu nghiệm thu hoàn thành, PCCC, môi trường, đấu nối, hoàn công, nghĩa vụ tài chính.','Chuẩn hóa biên bản bàn giao, danh mục thiết bị, bảo hành, diện tích, phần chung/riêng.']],['Bước 2 — Hồ sơ cấp GCN khách hàng',['Tách hồ sơ CĐT phải chuẩn bị và hồ sơ khách hàng phải ký/nộp.','CĐT: pháp lý dự án, GCN/QĐ đất, hoàn công, bản vẽ sơ đồ, nghĩa vụ tài chính, giải chấp.','Khách hàng: HĐMB, chứng từ thanh toán, giấy tờ pháp lý, tờ khai/lệ phí nếu có.']],['Bước 3 — Xử lý nghĩa vụ tài chính/phát sinh',['Theo dõi phiếu chuyển thông tin sang thuế, thông báo thu, khoản phải nộp bổ sung nếu có.','Nếu sai diện tích/sơ đồ phải điều chỉnh trước khi nộp hàng loạt.']],['Bước 4 — Quản trị cam kết cấp sổ',['Lập dashboard từng căn/lô: đủ hồ sơ, đang nộp, bổ sung, đã có GCN, đã bàn giao GCN.','Cảnh báo sớm các căn bị vướng giải chấp, tranh chấp, thiếu chữ ký, thiếu chứng từ.']]]"""
replacement="""V:[['Bước 1 — Chốt route đất và loại nghĩa vụ',['Tạo bảng phân loại từng phần diện tích: đất ở, đất thương mại dịch vụ, đất HTKT/HTXH, đất giao không thu tiền, đất thuê trả tiền hằng năm, đất thuê trả tiền một lần.','Gắn mỗi phần diện tích với căn cứ pháp lý: giao đất, thuê đất, chuyển mục đích, công nhận QSDĐ, đấu giá/đấu thầu/thỏa thuận.','Xác định thời điểm phát sinh nghĩa vụ tài chính và cơ quan tính/thu.']],['Bước 2 — Lập workbook tính nghĩa vụ tài chính',['Sheet 1: dữ liệu diện tích theo QHCT/bản đồ địa chính/bản đồ HTVT.','Sheet 2: loại đất trước/sau và hình thức sử dụng đất.','Sheet 3: giá đất/bảng giá đất/giá đất cụ thể/hệ số/đơn giá thuê.','Sheet 4: chi phí GPMB được trừ, miễn giảm, khấu trừ, tiền đã ứng.','Sheet 5: gross payable, deduction, net payable, chứng từ và nguồn luật.']],['Bước 3 — Kiểm chứng số liệu với hồ sơ pháp lý',['Đối chiếu diện tích tính tiền với quyết định giao/thuê/chuyển mục đích và bản đồ.','Đối chiếu mục đích sử dụng với QHCT và quyết định đất.','Đối chiếu thời hạn thuê/giao đất với CTCTĐT và quyết định đất.','Không dùng số liệu tài chính nếu chưa khóa được nguồn diện tích và mục đích sử dụng.']],['Bước 4 — Quản trị output tài chính đất',['Theo dõi quyết định giá đất/thông báo nộp tiền/chứng từ nộp tiền/xác nhận hoàn thành nghĩa vụ.','Cập nhật ngay model TMĐT, lợi nhuận, giá bán và dòng tiền sau khi có số chính thức.','Lưu riêng căn cứ từng khoản trừ/miễn/giảm để phục vụ kiểm toán, thanh tra, cấp GCN.']]],
IX:[['Bước 1 — Lập ma trận nghiệm thu theo hạng mục',['Tách HTKT, HTXH, nhà thấp tầng, trung/cao tầng, PCCC, môi trường, đấu nối, cảnh quan, tiện ích.','Mỗi hạng mục ghi: hồ sơ chất lượng, bản vẽ hoàn công, biên bản nghiệm thu, cơ quan kiểm tra, điều kiện bàn giao.']],['Bước 2 — Hồ sơ hoàn công/chất lượng',['Nhật ký thi công, nghiệm thu công việc, nghiệm thu giai đoạn, nghiệm thu vật liệu/thiết bị.','Bản vẽ hoàn công, thí nghiệm/kiểm định, chứng chỉ vật liệu, hồ sơ an toàn.','Hồ sơ PCCC, GPMT/vận hành thử, đấu nối điện nước thoát nước giao thông.']],['Bước 3 — Kiểm tra trước khi mời CQNN',['Soát sai khác hiện trường so với GPXD/TKBVTC/QHCT.','Đóng tồn tại nghiêm trọng; lập danh mục tồn tại nhỏ và kế hoạch xử lý nếu được chấp nhận.','Đảm bảo PCCC/môi trường/đấu nối không còn thiếu văn bản cứng.']],['Bước 4 — Dùng output nghiệm thu',['Văn bản kiểm tra nghiệm thu/biên bản nghiệm thu là input cho bàn giao, vận hành, bán hàng tiếp, cấp GCN.','Nếu chưa nghiệm thu hoàn thành thì không nên cam kết bàn giao pháp lý/cấp sổ.']]],
X:[['Bước 1 — Chuẩn bị trước bàn giao',['Đối chiếu nghiệm thu hoàn thành, PCCC, môi trường, đấu nối, hoàn công, nghĩa vụ tài chính.','Chuẩn hóa biên bản bàn giao, danh mục thiết bị, bảo hành, diện tích, phần chung/riêng.','Chốt checklist điều kiện bàn giao: pháp lý, kỹ thuật, tài chính, dịch vụ khách hàng.']],['Bước 2 — Hồ sơ cấp GCN khách hàng',['Tách hồ sơ CĐT phải chuẩn bị và hồ sơ khách hàng phải ký/nộp.','CĐT: pháp lý dự án, GCN/QĐ đất, hoàn công, bản vẽ sơ đồ, nghĩa vụ tài chính, giải chấp.','Khách hàng: HĐMB, chứng từ thanh toán, giấy tờ pháp lý, tờ khai/lệ phí nếu có.','Tách hồ sơ theo từng căn/lô để tránh thiếu dây chuyền khi nộp hàng loạt.']],['Bước 3 — Xử lý nghĩa vụ tài chính/phát sinh',['Theo dõi phiếu chuyển thông tin sang thuế, thông báo thu, khoản phải nộp bổ sung nếu có.','Nếu sai diện tích/sơ đồ phải điều chỉnh trước khi nộp hàng loạt.','Theo dõi tình trạng giải chấp từng căn/lô; không để vướng ngân hàng mới phát hiện lúc nộp sổ.']],['Bước 4 — Quản trị cam kết cấp sổ',['Lập dashboard từng căn/lô: đủ hồ sơ, đang nộp, bổ sung, đã có GCN, đã bàn giao GCN.','Cảnh báo sớm các căn bị vướng giải chấp, tranh chấp, thiếu chữ ký, thiếu chứng từ.','Lưu toàn bộ log nộp hồ sơ, giấy hẹn, yêu cầu bổ sung, ngày trả kết quả để xử lý khiếu nại.']]]"""
if needle in s:
    s=s.replace(needle,replacement)
else:
    print('needle not found')
p.write_text(s,encoding='utf-8')
print('patched land acceptance deep')
