from pathlib import Path
p=Path(r'C:\Users\HoaD-CVDT\.openclaw\workspace\LH BDS\Luat BDS\web_mindmap\tpre_flowchart_popup.html')
s=p.read_text(encoding='utf-8')
# Add professional CSS additions before media query
insert_css=r'''
.badges{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.badge{background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.25);border-radius:999px;padding:6px 10px;font-weight:800;font-size:12px}.summaryBox{border:1px solid #cfe0f5;background:linear-gradient(180deg,#f8fbff,#fff);border-radius:18px;padding:16px;grid-column:1/-1}.summaryBox b{color:#0b3d91}.dossier{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;grid-column:1/-1}.mini{border:1px solid #e2e8f0;border-radius:16px;background:#fff;padding:14px}.mini h4{margin:0 0 8px;text-transform:uppercase;font-size:11px;letter-spacing:.08em;color:#0b3d91}.mini .line{font-size:13px}.lawGrid{display:grid;gap:14px}.law{background:linear-gradient(180deg,#f8fbff,#fff)}.lawPoint{display:grid;grid-template-columns:190px 1fr;gap:12px;padding:9px 0;border-bottom:1px solid #eef2f7}.lawPoint:last-child{border-bottom:0}.lawLabel{font-weight:900;color:#0b3d91;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.lawText{color:#24324a}.sourceBlock{margin-top:10px;background:#f8fafc;border:1px dashed #cbd5e1;border-radius:12px;padding:10px;color:#475569;font-size:12px}.toc{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.toc span{background:#eef6ff;color:#0b3d91;border:1px solid #cfe0f5;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800}
@media(max-width:900px){.dossier{grid-template-columns:1fr}.lawPoint{grid-template-columns:1fr;gap:3px}}
'''
s=s.replace('@media(max-width:900px){.dlgBody{grid-template-columns:1fr}.modal{padding:10px}.top h1{font-size:18px}}',insert_css+'@media(max-width:900px){.dlgBody{grid-template-columns:1fr}.modal{padding:10px}.top h1{font-size:18px}}')
old="""mmeta.textContent=`Lane: ${it.owner||p.lane} · Phase ${p.id}: ${p.title}`; mbody.innerHTML=`<div class="section full"><h4>Tóm tắt nội dung / vai trò trong lưu đồ</h4><div class="line">${esc(it.summary||p.summary)}</div></div><div class="section"><h4>Quy trình / việc phải làm</h4>${lines(it.inputs)}</div><div class="section"><h4>Kết quả / output pháp lý</h4>${lines(it.outputs)}</div><div class="section"><h4>Thời gian thực hiện</h4>${lines(timelineFor(p.id))}</div><div class="section"><h4>Điều kiện & thông tin quan trọng</h4>${lines(checkFor(p.id))}</div><div class="section full"><h4>Luật liên quan — tóm tắt trước, nguồn sau</h4>${laws(it.legal_basis)}</div>`; modal.classList.add('open')}"""
new="""mmeta.textContent=`Lane: ${it.owner||p.lane} · Phase ${p.id}: ${p.title}`; mbody.innerHTML=`<div class="summaryBox"><b>Mục tiêu thủ tục:</b> ${esc(it.summary||p.summary)}<div class="toc"><span>1. Quy trình</span><span>2. Hồ sơ/điều kiện</span><span>3. Thời gian</span><span>4. Kết quả</span><span>5. Căn cứ pháp lý</span></div></div><div class="dossier"><div class="mini"><h4>Quy trình / việc phải làm</h4>${lines(it.inputs)}</div><div class="mini"><h4>Điều kiện & checkpoint</h4>${lines(checkFor(p.id))}</div><div class="mini"><h4>Thời gian thực hiện</h4>${lines(timelineFor(p.id))}</div></div><div class="section full"><h4>Kết quả / output pháp lý</h4>${lines(it.outputs)}</div><div class="section full"><h4>Luật liên quan — tóm tắt trước, nguồn điều/khoản sau</h4><div class="lawGrid">${laws(it.legal_basis)}</div></div>`; modal.classList.add('open')}"""
s=s.replace(old,new)
old_laws="""function laws(a){return (a||[]).map(l=>`<div class="law"><div class="lawHead"><span class="doc">${esc(l.doc)}</span><span class="article">${esc(l.article)}</span></div>${lines(l.points)}<div class="source">Nguồn: ${esc(l.source_file||'local corpus')} · ${esc(l.article||'đang cập nhật điều/khoản')}</div></div>`).join('')||'<div class="line">Chưa map căn cứ.</div>'}"""
new_laws=r'''function splitPoint(x){let m=String(x||'').match(/^([^:]{3,45}):\s*(.*)$/);return m?{label:m[1],text:m[2]}:{label:'Nội dung chính',text:x}}
function laws(a){return (a||[]).map(l=>`<div class="law"><div class="lawHead"><span class="doc">${esc(l.doc)}</span><span class="article">${esc(l.article)}</span></div>${(l.points||[]).map(x=>{const p=splitPoint(x);return `<div class="lawPoint"><div class="lawLabel">${esc(p.label)}</div><div class="lawText">${esc(p.text)}</div></div>`}).join('')}<div class="sourceBlock"><b>Nguồn cuối mục:</b> ${esc(l.source_file||'local corpus')} · ${esc(l.article||'đang cập nhật điều/khoản/điểm')}</div></div>`).join('')||'<div class="line">Chưa map căn cứ.</div>'}'''
s=s.replace(old_laws,new_laws)
p.write_text(s,encoding='utf-8')
print('patched professional popup')
