from pathlib import Path
import subprocess

root = Path('firebase_public')
raw = subprocess.check_output(['git','show','fb91174:stock-news-backend/firebase_public/stocks-wyckoff-board.html'])
s = raw.decode('utf-8')

repls = [
    ("const S={chart:null,candle:null,symbol:'MWG',rows:[],hy:null,multi:null,legacy:null,like:null,focus:null,lockedFocus:null};",
     "const S={chart:null,candle:null,symbol:'MWG',rows:[],hy:null,multi:null,legacy:null,like:null,focus:null,lockedFocus:null,toggles:{mainTr:true,phase:true,channel:true,zones:true,events:true}};"),
    ("async function loadRows(symbol){const obj=await j(`/data/charts/${symbol}.json?v=${VER}`); return (Array.isArray(obj)?obj:(obj.rows||[])).map(x=>({time:x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}));}",
     "async function loadRows(symbol){try{const hist=await j(`/data/vn100_history_from_2023.json?v=${VER}`); const rows=hist?.symbols?.[symbol]?.rows||[]; if(rows.length) return rows.map(x=>({time:x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}));}catch(e){console.warn('long history fallback',e);} const obj=await j(`/data/charts/${symbol}.json?v=${VER}`); return (Array.isArray(obj)?obj:(obj.rows||[])).map(x=>({time:x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume}));}"),
    ("function trToVisible(tr){ if(!tr) return null; const s=S.rows[tr.start_idx], e=S.rows[tr.end_idx]; if(!s||!e) return tr; return tr; }",
     "function getIndexOffset(){ return Math.max(0,(S.rows?.length||0)-260); }\nfunction trToVisible(tr){ if(!tr) return null; const offset=getIndexOffset(); const mapped={...tr,start_idx:Number(tr.start_idx)+offset,end_idx:Number(tr.end_idx)+offset}; const s=S.rows[mapped.start_idx], e=S.rows[mapped.end_idx]; if(!s||!e) return tr; return mapped; }"),
    ("function drawRangeBox(tr,cls,label,focus){ try{ if(!tr) return; const i0=Number(tr.start_idx), i1=Number(tr.end_idx); const hi=Number(tr.high), lo=Number(tr.low); if(!Number.isFinite(i0)||!Number.isFinite(i1)||!Number.isFinite(hi)||!Number.isFinite(lo)||!S.rows[i0]||!S.rows[i1]) return; const x0=tX(S.rows[i0].time), x1=tX(S.rows[i1].time); if(!Number.isFinite(x0)||!Number.isFinite(x1)) return; const left=Math.min(x0,x1)-barHalf(i0), right=Math.max(x0,x1)+barHalf(i1); const top=Math.min(pY(hi),pY(lo)); const h=Math.max(16,Math.abs(pY(lo)-pY(hi))); addBox(cls,left,top,Math.max(8,right-left),h,focus); addTag(label,Math.max(8,left+4),Math.max(54,top-18), cls==='main-tr'?'rgba(111,179,255,.5)':cls==='phase'?'rgba(255,200,87,.5)':'rgba(255,255,255,.18)',focus); }catch(e){ console.warn('drawRangeBox failed', label, e); } }",
     "function drawRangeBox(tr,cls,label,focus){ try{ if(!tr) return; const box=trToVisible(tr); const i0=Number(box.start_idx), i1=Number(box.end_idx); const hi=Number(box.high), lo=Number(box.low); if(!Number.isFinite(i0)||!Number.isFinite(i1)||!Number.isFinite(hi)||!Number.isFinite(lo)||!S.rows[i0]||!S.rows[i1]) return; const x0=tX(S.rows[i0].time), x1=tX(S.rows[i1].time); if(!Number.isFinite(x0)||!Number.isFinite(x1)) return; const left=Math.min(x0,x1)-barHalf(i0), right=Math.max(x0,x1)+barHalf(i1); const top=Math.min(pY(hi),pY(lo)); const h=Math.max(16,Math.abs(pY(lo)-pY(hi))); addBox(cls,left,top,Math.max(8,right-left),h,focus); addTag(label,Math.max(8,left+4),Math.max(54,top-18), cls==='main-tr'?'rgba(111,179,255,.5)':cls==='phase'?'rgba(255,200,87,.5)':'rgba(255,255,255,.18)',focus); }catch(e){ console.warn('drawRangeBox failed', label, e); } }"),
    ("const lowPts=(wc.anchors?.lowPoints||[]).map(p=>({...p, gi:(wc.window?.start_idx||0)+p.idx})).filter(p=>S.rows[p.gi]); const highPts=(wc.anchors?.highPoints||[]).map(p=>({...p, gi:(wc.window?.start_idx||0)+p.idx})).filter(p=>S.rows[p.gi]);",
     "const offset=getIndexOffset(); const windowStart=(wc.window?.start_idx||0)+offset; const lowPts=(wc.anchors?.lowPoints||[]).map(p=>({...p, gi:windowStart+p.idx})).filter(p=>S.rows[p.gi]); const highPts=(wc.anchors?.highPoints||[]).map(p=>({...p, gi:windowStart+p.idx})).filter(p=>S.rows[p.gi]);"),
    ("const firstIdx=Math.min(lowPts[0].gi, highPts[0].gi), lastIdx=Math.max(lowPts[lowPts.length-1].gi, highPts[highPts.length-1].gi); if(!S.rows[firstIdx]||!S.rows[lastIdx]) return; const lowLine=wc.lines?.lowLine, highLine=wc.lines?.highLine; const rel=(gi)=>gi-(wc.window?.start_idx||0); const lowPrice=(gi)=> lowLine ? lowLine.slope*rel(gi)+lowLine.intercept : null; const highPrice=(gi)=> highLine ? highLine.slope*rel(gi)+highLine.intercept : null;",
     "const firstIdx=Math.min(lowPts[0].gi, highPts[0].gi), lastIdx=Math.max(lowPts[lowPts.length-1].gi, highPts[highPts.length-1].gi); if(!S.rows[firstIdx]||!S.rows[lastIdx]) return; const lowLine=wc.lines?.lowLine, highLine=wc.lines?.highLine; const rel=(gi)=>gi-windowStart; const lowPrice=(gi)=> lowLine ? lowLine.slope*rel(gi)+lowLine.intercept : null; const highPrice=(gi)=> highLine ? highLine.slope*rel(gi)+highLine.intercept : null;"),
    ("function drawOverlay(){ q('overlay').innerHTML=''; if(S.hy?.mainTr) drawRangeBox(S.hy.mainTr,'main-tr','Main TR','maintr'); const segs=S.hy?.mainTr?.phase_segments||[]; const active=S.hy?.phaseBox?.phase; segs.forEach(seg=>{ try{ if(seg.start==null||seg.end==null||seg.start<0||seg.end>=S.rows.length||seg.end<seg.start) return; const slice=S.rows.slice(seg.start,seg.end+1); if(!slice.length) return; drawRangeBox({start_idx:seg.start,end_idx:seg.end,high:Math.max(...slice.map(r=>r.high)),low:Math.min(...slice.map(r=>r.low))},'phase',seg.phase===active?`Phase ${seg.phase} (active)`: `Phase ${seg.phase}`,`phase:${seg.phase}`); }catch(e){ console.warn('phase failed', seg, e); }}); drawTrendChannel(); buildZones().forEach(drawZone); drawEvents(); applyFocus(); }",
     "function drawOverlay(){ q('overlay').innerHTML=''; if(S.toggles.mainTr && S.hy?.mainTr) drawRangeBox(S.hy.mainTr,'main-tr','Main TR','maintr'); const segs=S.hy?.mainTr?.phase_segments||[]; const active=S.hy?.phaseBox?.phase; if(S.toggles.phase){ segs.forEach(seg=>{ try{ if(seg.start==null||seg.end==null||seg.start<0||seg.end>=S.rows.length||seg.end<seg.start) return; const slice=S.rows.slice(seg.start,seg.end+1); if(!slice.length) return; drawRangeBox({start_idx:seg.start,end_idx:seg.end,high:Math.max(...slice.map(r=>r.high)),low:Math.min(...slice.map(r=>r.low))},'phase',seg.phase===active?`Phase ${seg.phase} (active)`: `Phase ${seg.phase}`,`phase:${seg.phase}`); }catch(e){ console.warn('phase failed', seg, e); }}); } if(S.toggles.channel) drawTrendChannel(); if(S.toggles.zones) buildZones().forEach(drawZone); if(S.toggles.events) drawEvents(); applyFocus(); }"),
    ("async function renderSymbol(symbol){ ensureChart(); S.symbol=symbol; S.focus=null; S.lockedFocus=null; const hy=getHybrid(symbol); if(!hy) throw new Error(`No hybrid data for ${symbol}`); const rows=await loadRows(symbol); S.rows=rows.slice(-260); S.hy={...hy, allRows:S.rows, localTrs:hy.localTrs||[], phaseBox:hy.phaseBox || (hy.mainTr?.phase_segments?.slice(-1)[0]||null)}; S.candle.setData(S.rows); S.chart.timeScale().fitContent(); rerender(); setTimeout(rerender,250); }",
     "async function renderSymbol(symbol){ ensureChart(); S.symbol=symbol; S.focus=null; S.lockedFocus=null; const hy=getHybrid(symbol); if(!hy) throw new Error(`No hybrid data for ${symbol}`); const rows=await loadRows(symbol); S.rows=rows; S.hy={...hy, allRows:S.rows, localTrs:hy.localTrs||[], phaseBox:hy.phaseBox || (hy.mainTr?.phase_segments?.slice(-1)[0]||null)}; S.candle.setData(S.rows); try{ if(S.rows.length){ S.chart.timeScale().setVisibleRange({ from:S.rows[0].time, to:S.rows[S.rows.length-1].time }); } else { S.chart.timeScale().fitContent(); } }catch(_){ S.chart.timeScale().fitContent(); } rerender(); setTimeout(()=>{ try{ if(S.rows.length){ S.chart.timeScale().setVisibleRange({ from:S.rows[0].time, to:S.rows[S.rows.length-1].time }); } else { S.chart.timeScale().fitContent(); } }catch(_){ S.chart.timeScale().fitContent(); } rerender(); },250); }"),
    ("async function run(){ await bootData(); const syms=['MWG',...Object.keys(S.multi?.symbols||{}).filter(x=>x!=='MWG')]; const sel=q('symbolSel'); syms.forEach(s=>{const o=el('option','',s); o.value=s; if(s==='MWG') o.selected=true; sel.appendChild(o);}); sel.onchange=()=>renderSymbol(sel.value).catch(e=>alert(String(e))); await renderSymbol('MWG'); try{S.chart.timeScale().subscribeVisibleLogicalRangeChange(()=>requestAnimationFrame(rerender));}catch{} try{S.chart.timeScale().subscribeVisibleTimeRangeChange(()=>requestAnimationFrame(rerender));}catch{} ['wheel','mousedown','mousemove','mouseup','touchstart','touchmove','touchend'].forEach(ev=>q('chart').addEventListener(ev,()=>requestAnimationFrame(rerender),{passive:true})); }",
     "async function run(){ await bootData(); let histSyms=[]; try{const hist=await j(`/data/vn100_history_from_2023.json?v=${VER}`); histSyms=Object.keys(hist?.symbols||{});}catch(e){console.warn('hist symbols load failed',e);} const syms=['MWG',...Array.from(new Set([...Object.keys(S.multi?.symbols||{}), ...Object.keys(S.like?.symbols||{}), ...histSyms])).filter(x=>x&&x!=='MWG').sort()]; const sel=q('symbolSel'); syms.forEach(s=>{const o=el('option','',s); o.value=s; if(s==='MWG') o.selected=true; sel.appendChild(o);}); sel.onchange=()=>renderSymbol(sel.value).catch(e=>alert(String(e))); await renderSymbol('MWG'); try{S.chart.timeScale().subscribeVisibleLogicalRangeChange(()=>requestAnimationFrame(rerender));}catch{} try{S.chart.timeScale().subscribeVisibleTimeRangeChange(()=>requestAnimationFrame(rerender));}catch{} ['wheel','mousedown','mousemove','mouseup','touchstart','touchmove','touchend'].forEach(ev=>q('chart').addEventListener(ev,()=>requestAnimationFrame(rerender),{passive:true})); }")
]
for old,new in repls:
    if old not in s:
        raise SystemExit(f'missing patch block: {old[:80]}')
    s = s.replace(old,new)
(root / 'wyckoff-board.html').write_text(s, encoding='utf-8')
print('rebuilt clean wyckoff-board.html')
