from pathlib import Path
p=Path('firebase_public/stocks-claude.html')
s=p.read_text(encoding='utf-8')
s=s.replace('const clusterSrLevels = (items = [], max = 6)', 'const clusterSrLevels = (items = [], max = 8)', 1)
s=s.replace('Math.abs(price / cluster.center - 1) <= 0.02', 'Math.abs(price / cluster.center - 1) <= 0.03', 1)
s=s.replace('const clusterTrendLines = (items = [], max = 6)', 'const clusterTrendLines = (items = [], max = 12)', 1)
s=s.replace('Math.abs(last / cluster.lastValue - 1) <= 0.02', 'Math.abs(last / cluster.lastValue - 1) <= 0.006', 1)
s=s.replace('Math.abs(mid / cluster.midValue - 1) <= 0.02', 'Math.abs(mid / cluster.midValue - 1) <= 0.006', 1)
s=s.replace('Math.abs(slope - cluster.slope) < 0.08', 'Math.abs(slope - cluster.slope) < 0.025', 1)
s=s.replace('const dedupeTrendLines = (lines = [], max = 8)', 'const dedupeTrendLines = (lines = [], max = 12)', 1)
s=s.replace('.slice(0, 4);\n          const resistance', '.slice(0, 6);\n          const resistance', 1)
s=s.replace('.slice(0, 4);\n          return [...support, ...resistance];', '.slice(0, 6);\n          return [...support, ...resistance];', 1)
s=s.replace('const trendLines = dedupeTrendLines(overlayData.trendlines, 8); const supportLike = trendLines.filter(x => Number(x?.slopePerBar || 0) >= 0); const resistanceLike = trendLines.filter(x => Number(x?.slopePerBar || 0) < 0);', 'const trendLines = dedupeTrendLines(overlayData.trendlines, 12); const supportLike = trendLines.filter(x => Number(x?.slopePerBar || 0) >= 0).slice(0, 6); const resistanceLike = trendLines.filter(x => Number(x?.slopePerBar || 0) < 0).slice(0, 6);', 1)
s=s.replace('Claude thử nghiệm: giữ nhiều trendline hơn để soi cấu trúc', 'Claude test rõ khác: giữ tối đa 6S + 6R, cluster rất lỏng để soi cấu trúc', 1)
s=s.replace('Claude Experimental Trendline View', 'Claude Experimental Trendline View - More Lines', 1)
p.write_text(s, encoding='utf-8')
print('done')
