from pathlib import Path
p=Path('firebase_public/pattern-reco.html')
s=p.read_text(encoding='utf-8')
start=s.index('<script>')+len('<script>')
end=s.index('</script>')
new=r'''
let payload=null, items=[], selected=null, chart=null, candleSeries=null, ma20=null, ma50=null;
let overlayMap={}, markerBase=[];
const $=id=>document.getElementById(id);
function clsBias(b){b=(b||'').toLowerCase(); return b.includes('bull')?'bullish':b.includes('bear')?'bearish':'neutral'}
function getPatterns(x){return x.patterns||[]}
function topText(x){return (x.summary?.primarySignals||[]).map(p=>p.type).join(', ') || getPatterns(x).slice(0,3).map(p=>p.type).join(', ') || 'No pattern'}
function lineColor(dir){return String(dir||'').toLowerCase().includes('bear')?'#ff7b7b':'#49d49d'}
function render(){const q=$('q').value.toLowerCase().trim(), b=$('bias').value, wy=$('wy').value; let arr=items.filter(x=>{const text=JSON.stringify({s:x.symbol,summary:x.summary,patterns:x.patterns}).toLowerCase(); if(q&&!text.includes(q))return false; if(b&&String(x.summary?.bias||'').toLowerCase()!=b)return false; if(wy&&!text.includes(wy))return false; return true;}); $('list').innerHTML=arr.map(x=>`<div class="card row ${selected?.symbol===x.symbol?'active':''}" onclick="show('${x.symbol}')"><div><span class="sym">${x.symbol}</span><span class="bias ${clsBias(x.summary?.bias)}">${x.summary?.bias||'n/a'} ${x.summary?.biasStrength??''}</span></div><div class="small">Close ${x.lastClose} • ${x.period?.[1]||''} • ${x.patternCount||0} patterns</div><div class="score"><span class="pill">Bull ${x.summary?.bullScore??'-'}</span><span class="pill">Bear ${x.summary?.bearScore??'-'}</span><span class="pill">${topText(x)}</span></div></div>`).join('')||'<div class="card small">Không có kết quả.</div>'}
function clearChart(){ if(chart){chart.remove(); chart=null;} overlayMap={}; markerBase=[]; $('chart').innerHTML=''; chart=LightweightCharts.createChart($('chart'),{layout:{background:{color:'#07111f'},textColor:'#dbeafe'},grid:{vertLines:{color:'#12243a'},horzLines:{color:'#12243a'}},rightPriceScale:{borderColor:'#20344f'},timeScale:{borderColor:'#20344f'}}); candleSeries=chart.addCandlestickSeries({upColor:'#49d49d',downColor:'#ff7b7b',borderUpColor:'#49d49d',borderDownColor:'#ff7b7b',wickUpColor:'#49d49d',wickDownColor:'#ff7b7b'}); ma20=chart.addLineSeries({color:'#63b3ff',lineWidth:1,priceLineVisible:false,lastValueVisible:false,title:'MA20'}); ma50=chart.addLineSeries({color:'#ffd166',lineWidth:1,priceLineVisible:false,lastValueVisible:false,title:'MA50'}); }
function rgba(hex, a){const h=hex.replace('#',''); const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16); return `rgba(${r},${g},${b},${a})`}
function addLineFor(key, points, color, title, faint=true){ if(!points||points.length<2||!chart) return; const s=chart.addLineSeries({color:rgba(color,faint?0.22:0.85),lineWidth:faint?1:2,priceLineVisible:false,lastValueVisible:false,title:title||''}); s.setData(points.map(p=>({time:p.time,value:Number(p.value)})).filter(p=>p.time&&isFinite(p.value))); (overlayMap[key] ||= []).push({series:s,color,title}); }
function focusOverlay(key){ Object.entries(overlayMap).forEach(([k,arr])=>arr.forEach(o=>o.series.applyOptions({color:rgba(o.color,k===key?0.95:0.08),lineWidth:k===key?4:1}))); candleSeries.setMarkers(markerBase.map(m=>({...m,color:m.key===key?m.baseColor:rgba('#ffd166',0.18),text:m.key===key?m.fullText:''}))); document.querySelectorAll('.pat').forEach(el=>el.classList.toggle('dim',el.dataset.key!==key)); }
function resetOverlay(){ Object.values(overlayMap).flat().forEach(o=>o.series.applyOptions({color:rgba(o.color,0.22),lineWidth:1})); candleSeries.setMarkers(markerBase.map(m=>({...m,color:m.baseColor,text:m.shortText}))); document.querySelectorAll('.pat').forEach(el=>el.classList.remove('dim')); }
async function loadChart(sym){ clearChart(); const url=`/data/charts/${sym}_auto_chart_day.json?ts=${Date.now()}`; let d=await fetch(url).then(r=>r.ok?r.json():Promise.reject(r.status)); const rows=d.rows||[]; candleSeries.setData(rows.map(r=>({time:r.time,open:+r.open,high:+r.high,low:+r.low,close:+r.close}))); ma20.setData((d.ma20||[]).filter(x=>x.value!=null)); ma50.setData((d.ma50||[]).filter(x=>x.value!=null)); const patterns=d.patterns||[]; patterns.forEach((p,i)=>{const key='p'+i, color=lineColor(p.direction); (p.lines||[]).forEach(l=>addLineFor(key,l.points,color,p.type,true)); if(p.time){markerBase.push({key,time:p.time,position:String(p.direction).includes('bear')?'aboveBar':'belowBar',baseColor:color,color,shape:String(p.direction).includes('bear')?'arrowDown':'arrowUp',shortText:String(i+1),fullText:`${i+1}. ${p.type}`});}}); (d.trendlines||[]).slice(0,8).forEach((t,i)=>{const key='t'+i; addLineFor(key,t.points,String(t.type||'').includes('resistance')?'#ff7b7b':'#49d49d',t.label||t.type,true)}); candleSeries.setMarkers(markerBase.map(m=>({...m,text:m.shortText})).slice(-60)); chart.timeScale().fitContent(); return d; }
async function show(sym){selected=items.find(x=>x.symbol===sym)||{symbol:sym}; render(); $('title').textContent=sym; $('sub').textContent='Đang tải chart overlay...'; let chartData={}; try{chartData=await loadChart(sym); $('sub').textContent=`${chartData.source||''} • ${chartData.patternSource||''} • ${chartData.patterns?.length||0} chart patterns • ${chartData.trendlines?.length||0} trendlines — hover panel để highlight`; }catch(e){$('sub').textContent='Không tải được auto chart: '+e;} const chartPats=(chartData.patterns||[]).map((p,i)=>({...p,_hoverKey:'p'+i,_idx:i+1,_src:'chart'})); const enginePats=getPatterns(selected).map((p,i)=>({...p,_hoverKey:'engine'+i,_idx:i+1,_src:'engine'})); const pats=[...chartPats,...enginePats].slice(0,80); $('detail').innerHTML=`<h2>${sym} <span class="bias ${clsBias(selected.summary?.bias)}">${selected.summary?.bias||''}</span></h2><div class="small">Engine cache: ${selected.period?.[0]||''} → ${selected.period?.[1]||''} • Last close ${selected.lastClose||''}</div><h3>Key levels</h3><div class="score"><span class="pill">Support: ${(selected.summary?.keyLevels?.supports||[]).join(', ')||'-'}</span><span class="pill">Resistance: ${(selected.summary?.keyLevels?.resistances||[]).join(', ')||'-'}</span></div><h3>Patterns / Overlay</h3>${pats.map(p=>`<div class="pat ${clsBias(p.direction)}" data-key="${p._hoverKey}" onmouseenter="focusOverlay('${p._hoverKey}')" onmouseleave="resetOverlay()"><div><span class="type">${p._src==='chart'?p._idx+'. ':''}${p.type||''}</span> <span class="small">${p.direction||''} • score ${p.score??''} • ${p.confidence||''} • ${p._src}</span></div><div class="note">${p.evidence?.notes||p.evidence?.confluence||''}</div><pre>${JSON.stringify(p.levels||{},null,1)}</pre></div>`).join('')||'<div class="small">Không có pattern.</div>'}`; }
function reloadSelected(){if(selected) show(selected.symbol)}
['q','bias','wy'].forEach(id=>$(id).addEventListener('input',render));
fetch('/data/pattern_reco_cache.json?ts='+Date.now()).then(r=>r.json()).then(d=>{payload=d;items=d.items||[];$('meta').textContent=`Pattern engine ${d.source} • Updated ${d.updatedAt} • ${d.count} mã • Errors ${d.errorCount}`;render(); const first=items.find(x=>x.symbol==='MWG')||items.find(x=>x.symbol==='FPT')||items[0]; if(first) show(first.symbol)}).catch(e=>{$('meta').textContent='Load lỗi '+e});
'''
p.write_text(s[:start]+new+s[end:],encoding='utf-8')
