from pathlib import Path
p=Path('pattern_engine_v2/chart_patterns.py')
s=p.read_text(encoding='utf-8')
anchor='''    def _significant(ix, v, kind, win=SIG_WIN):\n        """Đỉnh/đáy phải là CỰC TRỊ CỦA MỘT KHOẢNG THỜI GIAN ±win phiên."""\n        a, b = max(0, ix - win), min(n, ix + win + 1)\n        if kind == "low":\n            return float(low_arr[a:b].min()) >= v - 1e-9\n        return float(high_arr[a:b].max()) <= v + 1e-9\n'''
insert=anchor+'''\n    def _extreme_quality(ix, v, kind, win=SIG_WIN):\n        """Quality gate cho 2/3 đỉnh-đáy: pivot phải nổi bật so với vùng lân cận,\n        không chỉ là nhiễu sát giá. Trả về prominence theo giá và ATR."""\n        a, b = max(0, ix - win), min(n, ix + win + 1)\n        local_atr = max(float(df["atr20"].iloc[ix]) if pd.notna(df["atr20"].iloc[ix]) else atr, atr * 0.6)\n        if kind == "low":\n            left_high = float(high_arr[a:ix + 1].max()) if ix >= a else float(high_arr[ix])\n            right_high = float(high_arr[ix:b].max()) if b > ix else float(high_arr[ix])\n            prom = min(left_high - v, right_high - v)\n        else:\n            left_low = float(low_arr[a:ix + 1].min()) if ix >= a else float(low_arr[ix])\n            right_low = float(low_arr[ix:b].min()) if b > ix else float(low_arr[ix])\n            prom = min(v - left_low, v - right_low)\n        min_prom = max(local_atr * 0.75, close * 0.012)\n        return prom >= min_prom, prom, prom / max(local_atr, 1e-9)\n\n    def _shape_quality(grp, vals, necks, is_bottom):\n        """Chấm chất lượng hình học: symmetry thời gian, độ đều vùng đỉnh/đáy,\n        neckline đủ sâu/cao, và điểm chạm phải có prominence."""\n        span = grp[-1]["index"] - grp[0]["index"]\n        gaps = [b["index"] - a["index"] for a, b in zip(grp[:-1], grp[1:])]\n        if gaps and max(gaps) > 3.2 * max(min(gaps), 1):\n            return False, ["khoảng cách các điểm chạm lệch quá nhiều"]\n        spread = max(vals) - min(vals)\n        tol = max(atr * 0.95, float(np.mean(vals)) * 0.022)\n        reasons = []\n        if spread > tol:\n            return False, [f"độ lệch điểm chạm {spread:.2f} > ngưỡng {tol:.2f}"]\n        q = [_extreme_quality(g["index"], g["value"], "low" if is_bottom else "high") for g in grp]\n        if not all(x[0] for x in q):\n            return False, ["đỉnh/đáy chưa đủ nổi bật so với vùng lân cận"]\n        avg_prom_atr = float(np.mean([x[2] for x in q]))\n        if avg_prom_atr < 0.95:\n            return False, ["prominence trung bình dưới 0.95 ATR"]\n        neck_depths = []\n        for k, (ni, nv) in enumerate(necks):\n            if is_bottom:\n                neck_depths.append(nv - max(grp[k]["value"], grp[k + 1]["value"]))\n            else:\n                neck_depths.append(min(grp[k]["value"], grp[k + 1]["value"]) - nv)\n        if neck_depths and min(neck_depths) < max(atr * 1.35, close * 0.024):\n            return False, ["neckline chưa đủ tách biệt khỏi đỉnh/đáy"]\n        reasons.append(f"prominence TB {avg_prom_atr:.1f} ATR")\n        reasons.append(f"span {span} phiên")\n        return True, reasons\n'''
if anchor not in s: raise SystemExit('anchor not found')
s=s.replace(anchor,insert)
# bottom insert after necks ok before neckline
old='''            if not ok:\n                continue\n            # xác nhận chuẩn: phải vượt ĐỈNH HỒI CAO NHẤT giữa các đáy\n            neckline = float(max(v for _, v in necks))\n'''
new='''            if not ok:\n                continue\n            quality_ok, quality_notes = _shape_quality(grp, vals, necks, True)\n            if not quality_ok:\n                continue\n            # xác nhận chuẩn: phải vượt ĐỈNH HỒI CAO NHẤT giữa các đáy\n            neckline = float(max(v for _, v in necks))\n'''
if old not in s: raise SystemExit('bottom anchor not found')
s=s.replace(old,new,1)
old='''            if not ok:\n                continue\n            # xác nhận chuẩn: phải thủng ĐÁY HỒI THẤP NHẤT giữa các đỉnh\n            neckline = float(min(v for _, v in necks))\n'''
new='''            if not ok:\n                continue\n            quality_ok, quality_notes = _shape_quality(grp, vals, necks, False)\n            if not quality_ok:\n                continue\n            # xác nhận chuẩn: phải thủng ĐÁY HỒI THẤP NHẤT giữa các đỉnh\n            neckline = float(min(v for _, v in necks))\n'''
if old not in s: raise SystemExit('top anchor not found')
s=s.replace(old,new,1)
# add quality notes to extras and note strings
s=s.replace('''            if vol_dry:\n                extras.append("vol đáy sau giảm")''','''            extras.extend(quality_notes)\n            if vol_dry:\n                extras.append("vol đáy sau giảm")''')
s=s.replace('''                         f"{combo} đỉnh ~{resistance:.1f} (đỉnh {2 * SIG_WIN + 1} phiên), neckline {neckline:.1f}"\n                         + (f" · phá neckline vol {bvol:.1f}x ({'mạnh' if bvol >= 1.2 else 'yếu'})" if bvol is not None else "")\n                         + (" · đã retest neckline" if retested else ""))''','''                         f"{combo} đỉnh ~{resistance:.1f} (đỉnh {2 * SIG_WIN + 1} phiên), neckline {neckline:.1f}"\n                         + (" · " + " · ".join(quality_notes) if quality_notes else "")\n                         + (f" · phá neckline vol {bvol:.1f}x ({'mạnh' if bvol >= 1.2 else 'yếu'})" if bvol is not None else "")\n                         + (" · đã retest neckline" if retested else ""))''')
p.write_text(s,encoding='utf-8')
print('patched double/triple quality')
