from pathlib import Path
p=Path('firebase_public/stock-report.html')
s=p.read_text(encoding='utf-8')
s=s.replace(".graph{display:grid;gap:14px}.phase{border:1px solid var(--line);border-radius:20px;background:rgba(8,18,38,.58);padding:14px}.phaseTitle{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.nodes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.node{min-height:96px;border:1px solid var(--line);border-radius:16px;background:rgba(20,40,78,.72);padding:12px}.nodeTop{display:flex;justify-content:space-between;gap:8px}.name{font-size:13px;font-weight:850}.connector{height:28px;display:grid;place-items:center;color:var(--cyan);font-size:22px}",".graph{display:grid;gap:14px}.phase{border:1px solid var(--line);border-radius:20px;background:rgba(8,18,38,.58);padding:14px}.phaseTitle{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.phaseMeta{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0 10px}.phaseBar{height:9px;background:#061023;border-radius:999px;overflow:hidden;margin-bottom:12px}.phaseBar span{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--cyan),var(--green));transition:.35s}.nodes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.node{min-height:96px;border:1px solid var(--line);border-radius:16px;background:rgba(20,40,78,.72);padding:12px;opacity:.72}.node.running{opacity:1;border-color:var(--cyan);box-shadow:0 0 0 1px rgba(53,217,255,.25) inset,0 0 22px rgba(53,217,255,.14)}.node.done,.node.skipped{opacity:1;border-color:rgba(53,208,127,.55)}.node.error{opacity:1;border-color:var(--red)}.nodeTop{display:flex;justify-content:space-between;gap:8px}.name{font-size:13px;font-weight:850}.connector{height:28px;display:grid;place-items:center;color:var(--cyan);font-size:22px}")
start=s.index('function renderGraph(sections){')
end=s.index('function renderOutputs', start)
new="""function renderGraph(sections){const by=Object.fromEntries((sections||[]).map(s=>[s.key,s]));$('graph').innerHTML=phases.map((p,i)=>{const arr=p[1].map(k=>by[k]||{key:k,name:sectionLabels[k]||k,agent:'-',status:'pending'});const done=arr.filter(s=>s.status==='done'||s.status==='skipped').length;const running=arr.filter(s=>s.status==='running').length;const err=arr.filter(s=>s.status==='error').length;const wait=Math.max(arr.length-done-running-err,0);const pct=Math.round(((done+running*.5)/Math.max(arr.length,1))*100);return `<div class=\"phase\"><div class=\"phaseTitle\"><b>${p[0]}</b><span class=\"pill ${err?'error':running?'running':done===arr.length?'done':''}\">${pct}%</span></div><div class=\"phaseMeta\"><span class=\"pill done\">Xong ${done}/${arr.length}</span><span class=\"pill running\">\\u0110ang ch\\u1ea1y ${running}</span><span class=\"pill\">Ch\\u1edd ${wait}</span>${err?`<span class=\"pill error\">L\\u1ed7i ${err}</span>`:''}</div><div class=\"phaseBar\"><span style=\"width:${pct}%\"></span></div><div class=\"nodes\">${arr.map(k=>node(k)).join('')}</div></div>${i<phases.length-1?'<div class=\"connector\">↓</div>':''}`}).join('')}
"""
s=s[:start]+new+s[end:]
p.write_text(s,encoding='utf-8',newline='\n')
print('patched')
