from pathlib import Path
p=Path('pattern_engine_v2/chart_patterns.py')
s=p.read_text(encoding='utf-8')
s=s.replace('''        if avg_prom_atr < 0.65:\n            return False, ["prominence trung bình dưới 0.95 ATR"]''','''        if avg_prom_atr < 0.65:\n            reasons.append("cảnh báo: prominence dưới chuẩn")''')
s=s.replace('''        if neck_depths and min(neck_depths) < max(atr * 1.05, close * 0.018):\n            return False, ["neckline chưa đủ tách biệt khỏi đỉnh/đáy"]''','''        if neck_depths and min(neck_depths) < max(atr * 1.05, close * 0.018):\n            reasons.append("cảnh báo: neckline tách biệt chưa mạnh")''')
s=s.replace('''            quality_ok, quality_notes = _shape_quality(grp, vals, necks, True)\n            if not quality_ok:\n                continue\n            # xác nhận chuẩn: phải vượt ĐỈNH HỒI CAO NHẤT giữa các đáy''','''            quality_ok, quality_notes = _shape_quality(grp, vals, necks, True)\n            if not quality_ok:\n                continue\n            quality_penalty = 6 * sum(1 for x in quality_notes if x.startswith("cảnh báo"))\n            # xác nhận chuẩn: phải vượt ĐỈNH HỒI CAO NHẤT giữa các đáy''')
s=s.replace('''            quality_ok, quality_notes = _shape_quality(grp, vals, necks, False)\n            if not quality_ok:\n                continue\n            # xác nhận chuẩn: phải thủng ĐÁY HỒI THẤP NHẤT giữa các đỉnh''','''            quality_ok, quality_notes = _shape_quality(grp, vals, necks, False)\n            if not quality_ok:\n                continue\n            quality_penalty = 6 * sum(1 for x in quality_notes if x.startswith("cảnh báo"))\n            # xác nhận chuẩn: phải thủng ĐÁY HỒI THẤP NHẤT giữa các đỉnh''')
# insert score penalty before failed blocks in double/triple sections only
s=s.replace('''            if status == "failed":\n                score *= 0.5\n            score = clamp(score)\n            shape = []\n            for k2, g in enumerate(grp):''','''            score -= quality_penalty\n            if status == "failed":\n                score *= 0.5\n            score = clamp(score)\n            shape = []\n            for k2, g in enumerate(grp):''',1)
s=s.replace('''            if status == "failed":\n                score *= 0.5\n            score = clamp(score)\n            shape = []\n            for k2, g in enumerate(grp):''','''            score -= quality_penalty\n            if status == "failed":\n                score *= 0.5\n            score = clamp(score)\n            shape = []\n            for k2, g in enumerate(grp):''',1)
p.write_text(s,encoding='utf-8')
print('patched penalty')
