from pathlib import Path

p=Path('firebase_public/macro.html')
s=p.read_text(encoding='utf-8')
anchor='</body>'
script=r'''
<script>
/* Macro phase table v2 + clearer selected-chart cycle interpretation. */
(function(){
 const finite=x=>Number.isFinite(x), last=a=>{for(let i=a.length-1;i>=0;i--)if(finite(a[i]))return {i,v:a[i]};return {i:-1,v:null}};
 const av=(a,i0,i1)=>{const z=(a||[]).slice(i0,i1+1).filter(finite);return z.length?z.reduce((x,y)=>x+y,0)/z.length:null};
 const f=(v,d=1)=>finite(v)?v.toLocaleString('vi-VN',{maximumFractionDigits:d,minimumFractionDigits:d}):'–';
 const fp=v=>finite(v)?(v>0?'+':'')+f(v,1)+'%':'–';
 function bounds(p){let a=M.indexOf(p.s),b=M.indexOf(p.e);if(a<0)a=0;if(b<0)b=M.length-1;return [a,b]}
 function stats(p){const [a,b]=bounds(p),v=DATA.vni.slice(a,b+1).filter(finite);let ret=null,dd=null,start=null,end=null;if(v.length>1){start=v[0];end=v.at(-1);ret=(end/start-1)*100;let peak=start;dd=0;v.forEach(x=>{peak=Math.max(peak,x);dd=Math.min(dd,(x/peak-1)*100)})}return {a,b,start,end,ret,dd,gdp:av(IND.gdp_growth_ff?.series,a,b),iip:av(IND.iip_yoy?.series,a,b),cpi:av(IND.cpi_yoy?.series,a,b),cr:av(IND.credit_yoy?.series,a,b),m2:av(IND.m2_yoy?.series,a,b),usd:av(IND.usdvnd?.series,a,b)}}
 function growth(x){if(!finite(x.gdp)&&!finite(x.iip))return ['Chưa đủ dữ liệu','var(--mut)'];if((x.gdp||0)>=6.5&&(x.iip||0)>=7)return ['Mở rộng mạnh','#34d399'];if((x.gdp||0)>=5)return ['Mở rộng chậm','#fbbf24'];return ['Suy yếu','#fb7185']}
 function prices(x){if(!finite(x.cpi))return ['Chưa đủ dữ liệu','var(--mut)'];if(x.cpi>4.5)return ['Lạm phát cao','#fb7185'];if(x.cpi>=3)return ['Lạm phát vừa','#fbbf24'];return ['Lạm phát thấp','#34d399']}
 function money(x){if(!finite(x.cr)||!finite(x.m2))return ['Chưa đủ dữ liệu','var(--mut)','–'];const gap=x.cr-x.m2;if(gap>8)return ['Thanh khoản căng','#fb7185','Gap '+f(gap,1)+'đ%'];if(gap>3)return ['Hơi chặt','#fbbf24','Gap '+f(gap,1)+'đ%'];return ['Cân bằng','#34d399','Gap '+f(gap,1)+'đ%']}
 function lesson(x){const gr=growth(x)[0],pr=prices(x)[0],mo=money(x)[0];if(gr==='Mở rộng mạnh'&&pr==='Lạm phát cao')return '<b>Cuối mở rộng:</b> lợi nhuận còn được tăng trưởng hỗ trợ nhưng P/E dễ bị ép bởi lãi suất, tỷ giá và lạm phát. Ưu tiên chất lượng, tránh mua đuổi.';if(gr==='Mở rộng mạnh'&&pr!=='Lạm phát cao')return '<b>Pha thuận lợi:</b> tăng trưởng tốt và áp lực giá chưa quá cao. Có thể tăng tỷ trọng khi xu hướng và định giá xác nhận.';if(gr==='Suy yếu'&&mo==='Thanh khoản căng')return '<b>Risk-off:</b> tăng trưởng yếu đi trong lúc tiền tệ chặt. Giảm đòn bẩy, giữ tiền mặt và ưu tiên phòng thủ.';if(gr==='Suy yếu')return '<b>Giảm tốc:</b> theo dõi chính sách hỗ trợ; thị trường có thể hồi trước kinh tế nhưng độ phân hóa cao.';return '<b>Chuyển pha:</b> chưa có tín hiệu đồng thuận; giữ tỷ trọng vừa phải và chờ xác nhận từ tăng trưởng, CPI và thanh khoản.'}
 const box=document.getElementById('cyclePhaseTable');
 if(box){const rows=(DATA.phases||[]).map(p=>({p,x:stats(p)}));box.innerHTML=`<div style="padding:9px 11px;border-radius:8px;background:rgba(34,211,238,.06);color:var(--mut);line-height:1.55"><b>Cách đọc:</b> ba cột giữa xác định bối cảnh vĩ mô; VN-Index là phản ứng quan sát, không dùng để gán pha. Số năm 2026 là YTD. GDP quý được dùng để nhận diện hướng tăng trưởng, không coi là số tháng.</div><table style="width:100%;border-collapse:collapse;font-size:11.5px;min-width:1120px;margin-top:10px"><thead><tr><th style="text-align:left;padding:9px;border-bottom:1px solid var(--line)">Pha / thời gian</th><th style="text-align:left;padding:9px;border-bottom:1px solid var(--line)">Tăng trưởng thực</th><th style="text-align:left;padding:9px;border-bottom:1px solid var(--line)">Lạm phát</th><th style="text-align:left;padding:9px;border-bottom:1px solid var(--line)">Tiền tệ</th><th style="padding:9px;border-bottom:1px solid var(--line)">VN-Index</th><th style="padding:9px;border-bottom:1px solid var(--line)">DD tháng</th><th style="text-align:left;padding:9px;border-bottom:1px solid var(--line)">Insight cho nhà đầu tư</th></tr></thead><tbody>${rows.map(({p,x})=>{const gr=growth(x),pr=prices(x),mo=money(x),end=p.e>M[M.length-1]?'YTD '+M[M.length-1]:p.e;return `<tr><td style="padding:9px;border-bottom:1px solid var(--line);min-width:175px"><b style="color:${p.col}">${p.name}</b><div style="color:var(--mut2)">${p.s} → ${end}</div></td><td style="padding:9px;border-bottom:1px solid var(--line);min-width:145px"><b style="color:${gr[1]}">${gr[0]}</b><div style="color:var(--mut2)">GDP ${f(x.gdp)}% · IIP ${f(x.iip)}%</div></td><td style="padding:9px;border-bottom:1px solid var(--line);min-width:125px"><b style="color:${pr[1]}">${pr[0]}</b><div style="color:var(--mut2)">CPI TB ${f(x.cpi)}%</div></td><td style="padding:9px;border-bottom:1px solid var(--line);min-width:155px"><b style="color:${mo[1]}">${mo[0]}</b><div style="color:var(--mut2)">TD ${f(x.cr)}% · M2 ${f(x.m2)}%<br>${mo[2]}</div></td><td style="padding:9px;border-bottom:1px solid var(--line);text-align:center;color:${(x.ret||0)>=0?'#34d399':'#fb7185'}"><b>${fp(x.ret)}</b><div style="color:var(--mut2)">${finite(x.start)?Math.round(x.start).toLocaleString('vi'):'–'} → ${finite(x.end)?Math.round(x.end).toLocaleString('vi'):'–'}</div></td><td style="padding:9px;border-bottom:1px solid var(--line);text-align:center;color:#fb7185">${fp(x.dd)}</td><td style="padding:9px;border-bottom:1px solid var(--line);color:var(--mut);min-width:300px;line-height:1.5">${lesson(x)}</td></tr>`}).join('')}</tbody></table><div style="font-size:10.5px;color:var(--mut2);margin-top:8px">DD tháng = drawdown tính từ điểm đóng cửa tháng; không phải mức giảm sâu nhất trong ngày. Trung bình pha chỉ dùng mô tả vì các chuỗi có tần suất và kỳ công bố khác nhau.</div>`}

 // Improve the selected-chart paragraph after every selection, without changing charts/data.
 const oldAnalyze=window.analyzeInd;
 window.analyzeInd=function(){oldAnalyze();const k=window.curFac||curFac,a=IND[k]?.series;if(!a)return;const z=last(a);if(z.i<0)return;const v=z.v,u=unit(k),d3=z.i>=3&&finite(a[z.i-3])?v-a[z.i-3]:null,d12=z.i>=12&&finite(a[z.i-12])?v-a[z.i-12]:null;const nums=a.filter(finite),lo=Math.min(...nums),hi=Math.max(...nums),pos=(v-lo)/((hi-lo)||1)*100;const dir=d3==null?'chưa đủ dữ liệu 3 tháng':d3>0?'đang tăng':d3<0?'đang giảm':'đi ngang';const ph=curPhase(M[z.i]);let meaning='Chỉ tiêu này cần được đọc cùng tăng trưởng, lạm phát và thanh khoản; không nên dùng riêng để kết luận chu kỳ.';
  if(k==='credit_yoy')meaning=v>=16?'Tín dụng cao hỗ trợ hoạt động kinh tế, nhưng nếu tăng nhanh hơn M2 sẽ làm thanh khoản căng và đẩy chu kỳ về cuối mở rộng.':'Tín dụng chưa ở vùng quá nóng.';
  else if(k==='m2_yoy')meaning=v<10?'M2 tăng chậm cho thấy nguồn tiền không theo kịp nhu cầu tín dụng; bất lợi cho thanh khoản thị trường.':'M2 đang tạo nền thanh khoản tương đối thuận lợi.';
  else if(k==='cpi_yoy')meaning=v>4.5?'CPI vượt 4,5% làm giảm dư địa hạ lãi suất và có thể gây co P/E thị trường.':'CPI trong vùng kiểm soát giúp chính sách linh hoạt hơn.';
  else if(['vnibor_on','vnibor_1m','deposit','lending','mp_interbank_on'].includes(k))meaning=(dir==='đang tăng'?'Chi phí vốn tăng là lực cản đối với nhóm định giá cao và doanh nghiệp dùng nhiều nợ.':'Áp lực chi phí vốn đang ổn định hoặc dịu lại.');
  else if(k==='usdvnd'||k==='fx_central')meaning=(dir==='đang tăng'||pos>70)?'Áp lực tỷ giá có thể hạn chế nới lỏng và làm dòng vốn ngoại thận trọng hơn.':'Tỷ giá chưa tạo áp lực mới rõ rệt.';
  else if(['gdp_growth','gdp_growth_ff','gdp_growth_q_ff','iip_yoy','retail','exports'].includes(k))meaning=(v>0&&dir!=='đang giảm')?'Kinh tế thực còn mở rộng; đây là lý do chưa thể gọi suy thoái.':'Động lực kinh tế thực đang yếu đi và cần thêm chỉ tiêu xác nhận.';
  else if(['omo_net','mp_total_net','mp_reverse_repo_net'].includes(k))meaning=v>0?'NHNN đang hỗ trợ thanh khoản ngắn hạn; chưa đủ để kết luận một chu kỳ nới lỏng mới nếu CPI và tỷ giá còn cao.':'NHNN đang hút/không bơm ròng, điều kiện tiền tệ thận trọng hơn.';
  const el=document.getElementById('facAnalysis');if(el){const ps=el.querySelectorAll('p');if(ps.length)ps[ps.length-1].innerHTML=`<b>Nhận định chu kỳ theo chart:</b> ${IND[k].label} hiện <b>${fmt(v,u)}</b> tại kỳ <b>${M[z.i]}</b>, ${dir}${d3==null?'':` (${d3>0?'+':''}${f(d3,2)} trong 3 tháng)`}, nằm ở vùng <b>${pos>66?'cao':pos<33?'thấp':'trung bình'}</b> của lịch sử hiển thị. ${meaning} <b>Kết luận chung:</b> ${ph.name}. <span style="color:var(--mut2)">Điều kiện đổi quan điểm: phải có thêm xác nhận từ GDP/IIP, CPI, tín dụng–M2, lãi suất và tỷ giá.</span>`}
 };
 // Re-bind paths that call the lexical function by wrapping selection actions.
 document.getElementById('facMenu')?.addEventListener('click',()=>setTimeout(()=>window.analyzeInd(),0));
 document.getElementById('mkpi')?.addEventListener('click',()=>setTimeout(()=>window.analyzeInd(),0));
 setTimeout(()=>window.analyzeInd(),0);
})();
</script>
'''
if anchor not in s:raise SystemExit('body missing')
p.write_text(s.replace(anchor,script+anchor,1),encoding='utf-8')
print('macro table v2 and chart insights applied')
