const fs=require('fs'); const path=require('path');
const wsUrl='ws://127.0.0.1:18800/devtools/page/2E3F806C8EBE1BB2359728A6959BA047';
const outDir='C:/Users/HoaD-CVDT/.openclaw/workspace/projects/bds-project-database/teams_batches'; fs.mkdirSync(outDir,{recursive:true});
const ws=new WebSocket(wsUrl); let id=1;
function send(method,params={}){return new Promise((resolve,reject)=>{const mid=id++; const timer=setTimeout(()=>reject(new Error('timeout '+method)),30000); const on=ev=>{const msg=JSON.parse(ev.data); if(msg.id===mid){clearTimeout(timer); ws.removeEventListener('message',on); resolve(msg)}}; ws.addEventListener('message',on); ws.send(JSON.stringify({id:mid,method,params}));});}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function norm(s){return (s||'').replace(/\s+/g,' ').trim();}
async function evalv(expr){const r=await send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true}); if(r.result.exceptionDetails){throw new Error(JSON.stringify(r.result.exceptionDetails));} return r.result.result.value;}
const dumpExpr=`(() => { const t=document.querySelector('[data-tid="message-pane-list-viewport"]'); const root=t||document.body; const text=(root.innerText||document.body.innerText||'').slice(0,120000); return {found:!!t, top:t?t.scrollTop:null, h:t?t.scrollHeight:null, ch:t?t.clientHeight:null, text:text}; })()`;
const upExpr=`(() => { const t=document.querySelector('[data-tid="message-pane-list-viewport"]'); if(!t) return {found:false}; const before=t.scrollTop; t.scrollTop=Math.max(0,t.scrollTop-Math.floor(t.clientHeight*0.9)); t.dispatchEvent(new Event('scroll',{bubbles:true})); return {found:true,before:before,after:t.scrollTop,h:t.scrollHeight,ch:t.clientHeight}; })()`;
ws.addEventListener('open',async()=>{const seen=new Set(); const summary=[]; let stale=0; try{await send('Runtime.enable'); for(let i=917;i<=1300;i++){const v=await evalv(dumpExpr); const text=v.text||''; const key=norm(text).slice(0,1500); const duplicate=seen.has(key); seen.add(key); stale=duplicate?stale+1:0; const file=path.join(outDir,`batch_${String(i).padStart(3,'0')}.txt`); fs.writeFileSync(file,text,'utf8'); const dates=(text.match(/(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+[A-Za-z]+\s+\d{1,2},?\s+\d{4}|\b\d{1,2}\/\d{1,2}\/\d{4}\s+\d{1,2}:\d{2}\s+[AP]M|\b\d{1,2}\/\d{1,2}\/\d{4}/g)||[]).slice(0,10); const row={i,found:v.found,top:v.top,h:v.h,ch:v.ch,len:text.length,dates,duplicate,stale,file}; summary.push(row); console.log(JSON.stringify(row)); if(stale>=12 && v.top===0) break; for(let k=0;k<4;k++){await evalv(upExpr); await sleep(2500);} if(v.top===0) await sleep(8000);} fs.writeFileSync(path.join(outDir,'summary_dump_current_and_scroll.json'),JSON.stringify(summary,null,2),'utf8');}catch(e){console.error(e); process.exitCode=1;} ws.close();});
