const projects = (window.PROJECTS || []).filter(p => Number.isFinite(+p.lat) && Number.isFinite(+p.lng));
const qs = s => document.querySelector(s);
const map = L.map('map', { zoomControl: false }).setView([10.82, 106.72], 10);
L.control.zoom({ position: 'bottomright' }).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 20, attribution: '&copy; OpenStreetMap' }).addTo(map);
const markers = new Map(); let activeId = null; let sortMode = 'score';
function esc(v){ return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function clean(v){ return String(v ?? '').trim(); }
function val(v){ v=clean(v); return v ? esc(v) : '<span class="muted">—</span>'; }
function short(v,n=120){ v=clean(v); return v.length>n ? esc(v.slice(0,n-1))+'…' : esc(v); }
function priorityClass(p){ p=(p||'medium').toLowerCase(); return p.includes('high')?'high':p.includes('low')?'low':'medium'; }
function scoreClass(s){ s=+s||0; return s>=75?'score-good':s>=58?'score-mid':'score-low'; }
function markerIcon(p){ return L.divIcon({ className:'', iconSize:[30,30], iconAnchor:[15,30], popupAnchor:[0,-27], html:`<div class="marker-pin priority-${priorityClass(p.priority)}"><span>${Math.round(+p.score||0)}</span></div>` }); }
function rowsHtml(p, compact=false){
  const rows=[
    ['Ngày báo cáo', p.date || p.datetime_raw], ['Người gửi', p.sender], ['Trạng thái', p.status], ['Loại nguồn', p.type],
    ['Diện tích đất', p.area], ['Giá / chi phí', p.price], ['Giá bán SP', p.sell_price], ['FAR / HSSDĐ', p.far],
    ['Dân số', p.population], ['IRR', p.irr], ['NPV', p.npv], ['Rủi ro / note', p.risks], ['Source file', p.source_file]
  ];
  return `<table class="info-table ${compact?'compact':''}"><tbody>${rows.filter(([_,v])=>clean(v)).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${val(v)}</td></tr>`).join('')}</tbody></table>`;
}
function popupHtml(p){ return `<div class="popup"><div class="popup-title"><h3>${esc(p.name)}</h3><span class="score-badge ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div><div class="mini">${esc(p.id)} · ${esc(p.date || p.datetime_raw || 'chưa rõ ngày')}</div>${rowsHtml(p,true)}${p.map_url?`<a class="map-link" href="${esc(p.map_url)}" target="_blank" rel="noreferrer">Mở Google Maps</a>`:''}</div>`; }
function detailHtml(p){ return `<div class="drawer-head"><div><p class="eyebrow">Project detail</p><h3>${esc(p.name)}</h3><span class="mini">${esc(p.id)} · ${esc(p.source_chat || 'Teams database')}</span></div><span class="score-badge big ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div>${rowsHtml(p)}<section class="excerpt-box"><b>Excerpt tin nhắn gốc</b><p>${esc(p.excerpt || '')}</p></section>${p.map_url?`<p><a class="map-link" href="${esc(p.map_url)}" target="_blank" rel="noreferrer">Mở Google Maps gốc</a></p>`:''}`; }
function setActive(id, zoom=true){ activeId=id; const p=projects.find(x=>x.id===id); if(!p) return; document.querySelectorAll('.project-card').forEach(el=>el.classList.toggle('active', el.dataset.id===id)); const m=markers.get(id); if(m){ if(zoom) map.flyTo([p.lat,p.lng], Math.max(map.getZoom(),15),{duration:.75}); m.openPopup(); } const drawer=qs('#detailDrawer'); drawer.hidden=false; drawer.innerHTML=detailHtml(p); }
function filtered(){ const q=qs('#search').value.trim().toLowerCase(); const st=qs('#statusFilter').value; const ty=qs('#typeFilter').value; let arr=projects.filter(p=>{ const blob=[p.name,p.id,p.address,p.province,p.district,p.excerpt,p.price,p.area,p.sender,p.source_file].join(' ').toLowerCase(); return (!q||blob.includes(q)) && (!st||(p.status||'')===st) && (!ty||(p.type||'')===ty); }); arr.sort((a,b)=> sortMode==='name'? a.name.localeCompare(b.name,'vi') : sortMode==='date'? String(b.date||'').localeCompare(String(a.date||'')) : (+b.score||0)-(+a.score||0)); return arr; }
function renderList(){ const rows=filtered(); qs('#countLabel').textContent=`${rows.length}/${projects.length}`; const list=qs('#projectList'); list.innerHTML=rows.length? rows.map(p=>`<button class="project-card ${p.id===activeId?'active':''}" data-id="${esc(p.id)}" role="listitem"><div class="project-title"><strong>${esc(p.name)}</strong><span class="score-badge ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div><div class="meta"><span>${esc(p.date||'chưa ngày')}</span><span>·</span><span>${esc(p.status||'review')}</span><span>·</span><span>${short(p.area,40)}</span></div><div class="fact-row"><span>${short(p.price,68)}</span></div><p class="excerpt">${esc(p.excerpt||'')}</p></button>`).join('') : '<div class="empty">Không có dự án phù hợp bộ lọc.</div>'; list.querySelectorAll('.project-card').forEach(btn=>btn.addEventListener('click',()=>setActive(btn.dataset.id))); const ids=new Set(rows.map(x=>x.id)); markers.forEach((m,id)=> ids.has(id)?m.addTo(map):map.removeLayer(m)); }
function initFilters(){ for(const [id,key] of [['#statusFilter','status'],['#typeFilter','type']]){ const sel=qs(id); [...new Set(projects.map(p=>p[key]).filter(Boolean))].sort().forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; sel.appendChild(o); }); sel.addEventListener('change',renderList); } qs('#search').addEventListener('input',renderList); qs('#sortMode').addEventListener('change',e=>{sortMode=e.target.value; renderList();}); }
function initMetrics(){ const high=projects.filter(p=>(+p.score||0)>=75).length; const avg=Math.round(projects.reduce((a,p)=>a+(+p.score||0),0)/(projects.length||1)); qs('#metrics').innerHTML=`<div class="metric"><b>${projects.length}</b><span>Điểm map</span></div><div class="metric"><b>${high}</b><span>Score ≥75</span></div><div class="metric"><b>${avg}</b><span>Score TB</span></div>`; }
function initMap(){ const group=[]; projects.forEach(p=>{ const m=L.marker([+p.lat,+p.lng],{icon:markerIcon(p),title:p.name}).bindPopup(popupHtml(p),{maxWidth:460}); m.on('click',()=>setActive(p.id,false)); markers.set(p.id,m); group.push(m); m.addTo(map); }); if(group.length) map.fitBounds(L.featureGroup(group).getBounds().pad(.15)); }
initMetrics(); initFilters(); initMap(); renderList(); if(projects[0]) setActive(projects[0].id,false);
