const projects=(window.PROJECTS||[]).filter(p=>Number.isFinite(+p.lat)&&Number.isFinite(+p.lng));
const qs=s=>document.querySelector(s); const map=L.map('map',{zoomControl:false}).setView([10.82,106.72],10); L.control.zoom({position:'bottomright'}).addTo(map); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(map);
const markers=new Map(); let activeId=null; let sortMode='score'; let allBounds=null;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));} function clean(v){return String(v??'').trim();} function short(v,n=90){v=clean(v);return v.length>n?esc(v.slice(0,n-1))+'…':esc(v);} function scoreClass(s){s=+s||0;return s>=70?'score-good':s>=45?'score-mid':'score-low';} function prio(p){p=(p||'medium').toLowerCase();return p.includes('high')?'high':p.includes('low')?'low':'medium';}
function firstVal(p,keys){const r=p.popup||{};for(const k of keys){if(clean(r[k]))return r[k];}return '';} function markerIcon(p){return L.divIcon({className:'',iconSize:[30,30],iconAnchor:[15,30],popupAnchor:[0,-27],html:`<div class="marker-pin priority-${prio(p.priority)}"><span>${Math.round(+p.score||0)}</span></div>`});}
const GROUPS=[
 ['source','Nguồn',[['Tên dự án','project_name'],['Số tin đã gom','mention_count'],['Ngày đầu','first_report_date'],['Ngày mới nhất','latest_report_date'],['Người gửi','senders'],['Source files','source_files'],['Master ID','master_id']]],
 ['location','Vị trí',[['Vị trí/địa chỉ','location'],['Tỉnh/TP','province_city'],['Khu vực/quận','district_area'],['Map URLs','map_urls'],['Tọa độ','coordinates']]],
 ['scale','Quy mô',[['Diện tích đất','land_area'],['Loại dự án','project_type'],['Loại đất','land_type']]],
 ['planning','Quy hoạch',[['Tóm tắt quy hoạch','planning_summary'],['Tầng cao','max_floors'],['FAR / HSSDĐ','far'],['Mật độ xây dựng','building_density'],['Dân số','population']]],
 ['legal','Pháp lý',[['Tóm tắt pháp lý','legal_summary'],['Trạng thái pháp lý','legal_status']]],
 ['money','Giá & chi phí',[['Giá chào / giá mua','asking_price'],['Các số liệu giá','price_mentions'],['Giá bán sản phẩm','selling_price'],['Chi phí đất / TSDĐ / LUR','land_cost'],['Tổng mức đầu tư','total_investment']]],
 ['return','Hiệu quả',[['Doanh thu','revenue'],['Lợi nhuận','profit'],['IRR','irr'],['NPV','npv'],['Hoàn vốn','payback']]],
 ['risk','Rủi ro',[['Rủi ro / lưu ý','risks'],['Next actions','next_actions'],['Attachments','attachments']]],
];
function table(fields,r){const body=fields.filter(([_,k])=>clean(r[k])).map(([label,k])=>`<tr><th>${esc(label)}</th><td>${esc(r[k])}</td></tr>`).join('');return body?`<table class="info-table"><tbody>${body}</tbody></table>`:'';}
function detailGroups(p){const r=p.popup||{};return GROUPS.map(([id,title,fields])=>{const t=table(fields,r);return t?`<section class="info-group" data-group="${id}"><h4>${esc(title)}</h4>${t}</section>`:''}).join('')+`<section class="excerpt-box"><b>Excerpt tin nhắn gốc</b><p>${esc(r.source_excerpt||p.excerpt||'')}</p>${p.map_url?`<a class="map-link" href="${esc(p.map_url)}" target="_blank" rel="noreferrer">Mở Google Maps gốc</a>`:''}</section>`;}
function popupHtml(p){return `<div class="popup"><div class="popup-head"><h3>${esc(p.name)}</h3><span class="score-badge ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div><p>${esc(p.date||p.datetime_raw||'Chưa rõ ngày')} · ${esc(p.type||'raw')}</p><table class="popup-summary"><tr><th>Diện tích</th><td>${short(firstVal(p,['land_area','area']),70)||'—'}</td></tr><tr><th>Giá</th><td>${short(firstVal(p,['asking_price','price_mentions']),70)||'—'}</td></tr><tr><th>IRR/NPV</th><td>${short([firstVal(p,['irr']),firstVal(p,['npv'])].filter(Boolean).join(' / '),70)||'—'}</td></tr><tr><th>Pháp lý</th><td>${short(firstVal(p,['legal_status','legal_summary']),70)||'—'}</td></tr></table><a class="map-link" href="#" onclick="window.__selectProject('${esc(p.id)}');return false;">Xem chi tiết đầy đủ</a></div>`;}
function renderDetail(p){qs('#detailPanel').innerHTML=`<div class="detail-hero"><div class="detail-hero-head"><div><p class="eyebrow">Investment record</p><h2>${esc(p.name)}</h2><div class="hero-meta"><span>${esc(p.id)}</span><span>·</span><span>${esc(p.date||p.datetime_raw||'chưa rõ ngày')}</span><span>·</span><span>${esc(p.sender||'')}</span></div></div><span class="score-badge big ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div></div><nav class="tab-nav">${GROUPS.map(([id,title])=>`<button data-target="${id}">${esc(title)}</button>`).join('')}</nav>${detailGroups(p)}`; qs('#detailPanel').querySelectorAll('.tab-nav button').forEach(btn=>btn.addEventListener('click',()=>{const el=qs(`#detailPanel [data-group="${btn.dataset.target}"]`); if(el) el.scrollIntoView({behavior:'smooth',block:'start'}); qs('#detailPanel').querySelectorAll('.tab-nav button').forEach(b=>b.classList.toggle('active',b===btn));}));}
function setActive(id,zoom=true){activeId=id;const p=projects.find(x=>x.id===id);if(!p)return;document.querySelectorAll('.project-card').forEach(el=>el.classList.toggle('active',el.dataset.id===id));const m=markers.get(id);if(m){if(zoom)map.flyTo([p.lat,p.lng],Math.max(map.getZoom(),15),{duration:.75});m.openPopup();}renderDetail(p);} window.__selectProject=setActive;
function filtered(){const q=qs('#search').value.trim().toLowerCase(),st=qs('#statusFilter').value,ty=qs('#typeFilter').value,min=+qs('#minScore').value;let arr=projects.filter(p=>{const r=p.popup||{};const blob=Object.values(r).join(' ').toLowerCase();return(+p.score||0)>=min&&(!q||blob.includes(q))&&(!st||(p.status||'')===st)&&(!ty||(p.type||'')===ty);});arr.sort((a,b)=>sortMode==='name'?a.name.localeCompare(b.name,'vi'):sortMode==='date'?String(b.date||'').localeCompare(String(a.date||'')):(+b.score||0)-(+a.score||0));return arr;}
function renderList(){const rows=filtered();qs('#countLabel').textContent=`${rows.length}/${projects.length}`;const list=qs('#projectList');list.innerHTML=rows.length?rows.map(p=>`<button class="project-card ${p.id===activeId?'active':''}" data-id="${esc(p.id)}" role="listitem"><div class="project-top"><strong>${esc(p.name)}</strong><span class="score-badge ${scoreClass(p.score)}">${Math.round(+p.score||0)}</span></div><div class="meta"><span>${esc(p.date||'chưa ngày')}</span><span>·</span><span>${esc(p.type||'raw')}</span></div><div class="mini-facts"><div class="mini-fact"><span>Diện tích</span><b>${short(firstVal(p,['land_area','area']),34)||'—'}</b></div><div class="mini-fact"><span>IRR/NPV</span><b>${short([firstVal(p,['irr']),firstVal(p,['npv'])].filter(Boolean).join(' / '),34)||'—'}</b></div></div><p class="excerpt">${esc(p.excerpt||'')}</p></button>`).join(''):'<div class="empty">Không có dự án phù hợp bộ lọc.</div>';list.querySelectorAll('.project-card').forEach(btn=>btn.addEventListener('click',()=>setActive(btn.dataset.id)));const ids=new Set(rows.map(x=>x.id));markers.forEach((m,id)=>ids.has(id)?m.addTo(map):map.removeLayer(m));}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportFilteredCsv(){const rows=filtered();const fields=['id','name','score','date','type','lat','lng','area','price','far','population','irr','npv','map_url','source_file'];const csv=[fields.join(',')].concat(rows.map(p=>fields.map(f=>csvCell(p[f])).join(','))).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bds_dashboard_filtered.csv';a.click();URL.revokeObjectURL(a.href);}
function initFilters(){for(const [id,key]of[['#statusFilter','status'],['#typeFilter','type']]){const sel=qs(id);[...new Set(projects.map(p=>p[key]).filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;sel.appendChild(o);});sel.addEventListener('change',renderList);}qs('#search').addEventListener('input',renderList);qs('#sortMode').addEventListener('change',e=>{sortMode=e.target.value;renderList();});qs('#minScore').addEventListener('input',e=>{qs('#minScoreLabel').textContent=e.target.value;renderList();});qs('#resetFilters').addEventListener('click',()=>{qs('#search').value='';qs('#statusFilter').value='';qs('#typeFilter').value='';qs('#minScore').value=0;qs('#minScoreLabel').textContent='0';renderList();});qs('#fitMapBtn').addEventListener('click',()=>{if(allBounds)map.fitBounds(allBounds.pad(.15));});qs('#exportCsvBtn').addEventListener('click',exportFilteredCsv);}
function initMetrics(){const high=projects.filter(p=>(+p.score||0)>=70).length,avg=Math.round(projects.reduce((a,p)=>a+(+p.score||0),0)/(projects.length||1));qs('#metrics').innerHTML=`<div class="metric"><b>${projects.length}</b><span>Điểm map</span></div><div class="metric"><b>${high}</b><span>Score ≥70</span></div><div class="metric"><b>${avg}</b><span>Score TB</span></div>`;}
function initMap(){const group=[];projects.forEach(p=>{const m=L.marker([+p.lat,+p.lng],{icon:markerIcon(p),title:p.name}).bindPopup(popupHtml(p),{maxWidth:380});m.on('click',()=>setActive(p.id,false));markers.set(p.id,m);group.push(m);m.addTo(map);});if(group.length){allBounds=L.featureGroup(group).getBounds();map.fitBounds(allBounds.pad(.15));}}
initMetrics();initFilters();initMap();renderList();if(projects[0])setActive(projects[0].id,false);
