window.PROJECTS = [
  {
    "id": "CAND-0025",
    "name": "Lô đất Phú Thọ Hòa Tân Phú",
    "lat": 10.785522,
    "lng": 106.63147,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "907.5 m2; 052.1 m2; 8,739 m2; 1,313 m2; 48,901 m2; 82,557 m2; 7.276 m2; 276,8 m2; 824,3 m2; 452,5 m2; 6.800 m2; 450 m2; 3,22 ha; 55.730 m2; 31.933 m2; 3.22ha",
    "far": "",
    "population": "",
    "price": "1,500 tỷ; 53 Triệu/m2; 63 Triệu/m2; 1,094 tỷ; 657 tỷ; 13.4 triệu/m2; 400 tỷ; 24 tỷ; 12.4 tỷ; 225 tỷ; 119 tỷ; 79 tỷ; 2,751 tỷ; 1,917 tỷ; 1,127 tỷ; 13.7 triệu/m2; 337 tỷ; 53 tỷ; 413 tỷ; 316 tỷ; 13 tỷ; 300 tỷ; 360 tỷ; 16,5 tỷ; 1.409 tỷ; 321 tỷ; 756,8 tỷ; 42 tỷ; 288 tỷ; 1.698 tỷ; 98 tỷ; 309 tỷ; 200 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT xin báo cáo Sếp Admin 01 về khu đất phường Phú Thọ Hòa, Quận Tân Phú, TP HCM (Nguồn Sếp Tâm) như sau: 1. Pháp lý đất: Diện tích: 13,907.5 m2 Mục đích: Đất trồng cây lâu năm Thời hạn: 50 năm ( 07/2011 – 07/2061) Nguồn gốc sử dụng: Nhà nước công nhận quyền sử dụng đất Vị trí: https://maps.app.goo.gl/v8GdHbU3xb5G8JFs9 Ranh đất: Hạ tang giao thông nội bộ: có bề rộng mặt đường hẹp (7m) và vị trí khó khả thi phát triển thành khu thương mại dịch vụ. 2. Quy hoạch: 3. Đánh giá: Hiện trạng khu đất là đất trồng cây lâu năm có thời hạn sử dụng đến tháng 07/2061. Căn cứ theo Tra cứu Quy hoạch như trên, Khu đất có quy hoạch công viên cây xanh chiếm tỉ trọng lớn 56% và phần còn lại là đất TMDV, không có quy hoạch đất ở. Dựa trên vị trí khu đất và hạ tầng xung quanh, khu đất khó phát triển TMDV mà chỉ phù hợp phát triển dự án nhà ở. Tuy nhiên, qua trao đổi với phòng Quy hoạch, khu đất khó điều chỉnh quy hoạch sang đất ở và đã hết chỉ tiêu dân số cùng chưa duyệt quy hoạch phân khu. Vì vậy, đề xuất",
    "map_url": "https://maps.app.goo.gl/v8GdHbU3xb5G8JFs9"
  },
  {
    "id": "CAND-0042",
    "name": "Trần Đức 1 2.8ha Thuận Giao",
    "lat": 10.970034,
    "lng": 106.715651,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "2.8ha; 2.8 ha; 8.5ha; 1.46 ha; 6.572 m2; 90m2",
    "far": "",
    "population": "",
    "price": "52 tr/m2; 55 tr/m2; 49.4 tr/m2; 80 tr/m2; 58 tr/m2; 520 tỷ; 132 tỷ; 78 tỷ; 485 tỷ; 14.5 tr/m2; 7.5tr/m2; 347 tỷ; 278 tỷ; 40 tỷ; 440 tỷ; 56tr/m2; 360 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT báo cáo sếp Admin 01 dự án Trần Đức 1 (2.8ha) I. Thông tin dự án - Diện tích: 2.8 ha - Vị trí: Ngã tư Mỹ Phước Tân Vạn - Thủ Khoa Huân, P.Thuận Giao, Bình Dương (cũ) https://maps.app.goo.gl/t178LDzcrFtjxgEz9 II. PA quy hoạch: - Khu đất dự án thuộc ô khu phố có diện tích 8.5ha, hệ số 9/13 (9 ở, 4 TMDV), dân số 4.000, chức năng ở hỗn hợp. - Do dự án có quy mô 2.8ha nên không thể lấy được hết dân số 4000. P.TKQH đã binh phương án sơ bộ như sau: - Hệ số: 5.08 - Dân số: 2.700 - Quy mô: 2 phân khu + Cao tầng (30 tầng) : 1.46 ha - 1.275 căn hộ ở, 18 căn shop TM và 154 căn officetel. + Thấp tầng (nhà liên kế 1 trệt 2 lầu): 6.572 m2 (đất thương phẩm) - 73 nhà liên kế III. PA triển khai đầu tư: a) Giả định kinh doanh: + Giá bán căn hộ: 52 tr/m2 (chưa V tim tường) + Giá bán Shop TM: 55 tr/m2 (chưa V tim tường) + Officetel: 49.4 tr/m2 (chưa V tim tường) + Nhà phố: 80 tr/m2 (chưa V tính trên diện tích đất – 90m2/lô), tương đương giá bán đất khoảng 58 tr/m2 b) Giả định chi phí: + Giá mua dự án/",
    "map_url": "https://maps.app.goo.gl/t178LDzcrFtjxgEz9"
  },
  {
    "id": "CAND-0046",
    "name": "Lô mặt tiền Quốc Lộ 13 Hiệp Bình Phước",
    "lat": 10.8486272,
    "lng": 106.7188746,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "4.214m2",
    "far": "",
    "population": "",
    "price": "350 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "Phòng đầu tư xin báo cáo lại sếp Admin 01 về lô mặt tiền Quốc Lộ 13, Hiệp Bình Phước, TP Thủ Đức. 1. Vị trí dự án: https://maps.app.goo.gl/oHEYY6H9GGykdD9C6 2. Thông tin lô đất (nguồn anh Hùng): a. Diện tích: 42x100m (4.214m2) b. MĐSDĐ: Đất sản xuất phi nông nghiệp, thời hạn sử dung đất lâu dài c. Giá: 350 tỷ",
    "map_url": "https://maps.app.goo.gl/oHEYY6H9GGykdD9C6"
  },
  {
    "id": "CAND-0047",
    "name": "Urban Green / Bình Thái Thủ Đức",
    "lat": 10.8456644,
    "lng": 106.7620502,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "4.600 m2; 4,604 m2",
    "far": "",
    "population": "",
    "price": "108.5tr/m2; 234 tỷ; 51tr/m2; 276 tỷ; 60tr/m2",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P. ĐT báo cáo Sếp Admin 01 về khu đất 4... by Hoa D - CVDT, has attachments. 5/22 9:23 AM Edited Hoa D - CVDT P. ĐT báo cáo Sếp Admin 01 về khu đất 4.600 m2 tại 120 Đặng Văn Bi, phường Thủ Đức, HCM như sau: 1. Tóm tắt sơ bộ hiện trạng pháp lý dự án: a) Vị trí và ranh dự án: https://maps.app.goo.gl/dRnRPbNFPmCfsTHAA b) Đánh giá vị trí dự án: Dự án có lợi thế vị trí khi cách ga Metro Bình Thái khoảng 700m, nằm gần các trường đại học, KCNC và khu dân cư hiện hữu. Khu vực ghi nhận nhu cầu mua ở thực và thuê ổn định, trong khi nguồn cung căn hộ mới còn hạn chế; đặc biệt, loại hình căn hộ dịch vụ chuẩn còn thiếu, tạo dư địa phát triển tốt cho dự án. Tuy nhiên, cần lưu ý rủi ro từ phần đất mộ cần xử lý/di dời và tác động tâm lý đối với người mua do vị trí tiếp giáp khu mộ. b. Sơ bộ hiện trạng pháp lý: Tổng diện tích khu đất là: 4,604 m2, chưa xác định được loại đất nên Phòng Đầu tư tạm giả định là đất CLN Pháp lý đất: Có nguồn gốc đất cá nhân, phù hợp để phát triển dự án nhà ở (Dựa theo Nghị ",
    "map_url": "https://maps.app.goo.gl/dRnRPbNFPmCfsTHAA"
  },
  {
    "id": "CAND-0072",
    "name": "Urban Green",
    "lat": 10.840677,
    "lng": 106.719716,
    "date": "2023-12-18",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "5,1ha; 4,9ha; 0,2ha; 218,27m²; 783,23m²; 000,8m²; 19.803m²; 5.1ha",
    "far": "",
    "population": "",
    "price": "",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT gửi lại sếp Admin 01 báo cáo dự án 5,1ha Kinh Đô, mặt tiền Đường số 4, phường Hiệp Bình Phước, TP. Thủ Đức, TP. Hồ Chí Minh - Báo cáo vào ngày 18/12/2023 1/ Vị trí Tiếp giáp 2 mặt tiền Đường số 4, đường trải nhựa rộng khoảng 6-7m, quy hoạch lộ giới dự kiến 20m, cách trục đường Quốc lộ 13 khoảng 230m, cách khu đô thị Vạn Phúc khoảng 800m Cách sân bay Quốc tế Tân Sơn Nhất khoảng 8,2km Cách Chợ Bến Thành khoảng 9,6km 2/ Hiện trạng: Đất trống + nhà xưởng (hình ảnh vệ tinh) 3/ Pháp lý đất: - Tổng diện tích đất Công ty Kinh Đô sử dụng: 5,1ha. Chưa có đất ở + Có 4,9ha đã được cấp sổ: * Loại đất: Đất sản xuất; * Hình thức sử dụng đất: Giao đất có thu tiền sử dung đất; * Thời hạn sử dụng đất: Ổn định lâu dài (Căn cứ QĐ 2232/QĐ-UB ngày 16/6/2003 của UBND Thành phố, Sở Tài nguyên và Môi trường cập nhật) Cập nhật biến động trên GCN ngày 10/10/2006. + Chênh lệch phần diện tích 0,2ha, UBND phường Hiệp Bình Phước có ý kiến như sau: * Phần mương thoát nước, có diện tích 218,27m² do UBND Phường qu",
    "map_url": "https://maps.app.goo.gl/ioqJ9N2mKRyMdiAe6"
  },
  {
    "id": "CAND-0095",
    "name": "Hermes Power 1",
    "lat": 10.784153,
    "lng": 106.72569,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "",
    "far": "",
    "population": "",
    "price": "250 tr/m2; 300 tr/m2; 3.380 tỷ; 2.073 tỷ; 1.411 tỷ; 1.129 tỷ; 2.660 tỷ; 2.300 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT Báo cáo sếp Admin 01 tính toán fs sơ bộ dự án Hermes Power 1. Thông tin dự án - Diện tích: - Vị trí: KĐT Thủ Thiêm - https://maps.app.goo.gl/qDbb6mJHvwhXw4Az6 Vị trí căn cứ vào file chào của Công ty hải Hưng, chưa xác định được ranh đất cụ thể. 2. PA Quy hoạch: - Dựa vào định vị trong file giới thiệu của Công ty Hải Hưng, khu đất dự án thuộc ô quy hoạch K4.4HH, thông số quy hoạch như sau: + Hệ số: 7.31 + Dân số: 1.002 + Quy mô: 15 tầng – 438 căn hộ ở, 42 căn shop TM 3. PA triển khai đầu tư: a) Giả định kinh doanh: Thời điểm bán hàng dự kiến 2029 (mất 2 năm xử lý pháp lý do hiện trạng pháp lý chưa có gì, khu đất chưa có đường, đường Lương Định Của đang triển khai thi công) + Giá bán: 250 tr/m2 (chưa V, tim tường) + Giá bán căn shop: 300 tr/m2 (chưa V tim tường) b) Giả định chi phí: + Giá mua: 3.380 tỷ (~ 130tr USD) Do hồ sơ đối tác gửi chưa có thông tin GCN, chưa xác định được mục đích sdđ hiện trạng. P.ĐT giả định khu đất hiện là đất nông nghiệp. + LUR: 2.073 tỷ (tính theo PP Thặn",
    "map_url": "https://maps.app.goo.gl/qDbb6mJHvwhXw4Az6"
  },
  {
    "id": "CAND-0098",
    "name": "Thủ Đức Living",
    "lat": 10.8679394,
    "lng": 106.763008,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "4,661 m2; 1,471 m2; 3,190m2; 3,545 m2; 1,111m2",
    "far": "",
    "population": "",
    "price": "1,179 tỷ; 1,038 tỷ; 66tr/m2; 141 tỷ; 78tr/m2; 1,415 tỷ; 400 tỷ; 86tr/m2; 289 tỷ; 60 tỷ; 443 tỷ; 16tr/m2; 223 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT xin báo cáo sếp Admin 01 dự án Thủ Đức Living, Đường Phạm Văn Đồng, TP HCM 1. Tóm tắt sơ bộ hiện trạng pháp lý dự án: a) Vị trí và ranh dự án: https://maps.app.goo.gl/D8GuCY5LefTH8JVq9 b) Sơ bộ hiện trạng pháp lý: Tổng diện tích khu đất là: 4,661 m2 (1,471 m2 đất ở, 3,190m2 đất cây hằng năm) Pháp lý đất: được thực hiện dự án thí điểm Nhà Ở Thương Mại (Dựa theo nghị quyết 171). Pháp lý QH: Diện tích phù hợp QH còn 3,545 m2 (Dính lộ giới: 1,111m2). Tầng cao 25 tầng cao, 0 tầng hầm; Hệ số sử dụng đất 6 lần, dân số là 500 người (tương đương hệ số 5.31 ,chưa sử dụng hết được hệ số HS SDĐ) 2. Hiệu quả dự án: a) Doanh thu (Có VAT): 1,179 tỷ VNĐ Giá bán căn hộ chung cư: 1,038 tỷ (66tr/m2 tim tường) Giá bán Shophouse: 141 tỷ (78tr/m2 tim tường) b) Chi phí (có VAT): 1,415 tỷ VNĐ Chi phí đất: 400 tỷ (86tr/m2 đất) Chi phí Nghĩa vụ tài chính: 289 tỷ Chi phí pháp lý: 60 tỷ Chi phí xây dựng ALL in cost: 443 tỷ (16tr/m2 xây dựng) Chi phí bán hàng + thuế VAT + CP Khác = 223 tỷ (CPHB + QLDN = 17% D",
    "map_url": "https://maps.app.goo.gl/D8GuCY5LefTH8JVq9"
  },
  {
    "id": "CAND-0102",
    "name": "Diamond Garden Đào Trí Phú Thuận",
    "lat": 10.727928,
    "lng": 106.742496,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "10,471 m2; 5,718 m2; 676 m2; 3,217m2; 860m2",
    "far": "",
    "population": "",
    "price": "3,579 tỷ; 64 tr/m2; 83 tr/m2; 400 tỷ; 42tr/m2; 666 tỷ; 527 tỷ; 16tr/m2; 180 tỷ",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "Friday, June 12 P. Đầu tư xin báo cáo sếp Admin 01 dự á... by Hoa D - CVDT, has an attachment. 6/12 4:10 PM Edited Hoa D - CVDT P. Đầu tư xin báo cáo sếp Admin 01 dự án Diamond Garden ở đường Đào Trí, Phường Phú Thuận, TP Hồ Chí Minh 1. Tóm tắt sơ bộ hiện trạng pháp lý dự án: a) Vị trí và ranh dự án: https://maps.app.goo.gl/GdiSL1z7fBFtk3tr8 b) Dự án bị chia cắt bởi một con rạch, phát sinh rủi ro pháp lý xây dựng cầu để kết nối hai khu đất b. Sơ bộ hiện trạng pháp lý: Tổng diện tích khu đất là: 10,471 m2, gồm 5,718 m2 đất lúa, 676 m2 đất ở, đất chuyên dụng 3,217m2 và 860m2 lộ giới Pháp lý đất: đang đề xuất xin vào cơ chế thí điểm của Nghị quyết 171 (cần tốn ít nhất 2 năm để có thể triển khai xây dựng được) Pháp lý QH: theo QHPK 10/2009 thuộc ô D2 có chỉ tiêu như sau: MĐXD 40%, tầng cao không giới hạn, HS SDĐ 7, dân số 278 (nguồn anh Tài). Đối tác đang xin điều chỉnh lại thành: HS SDĐ = 7.5, dân số 2,068 người => Mức đề xuất cao hơn đáng kể và anh Tài đánh giá phương án này có tính khả ",
    "map_url": "https://maps.app.goo.gl/GdiSL1z7fBFtk3tr8"
  },
  {
    "id": "CAND-0118",
    "name": "Khách sạn 5 sao 12 Hùng Vương Đà Lạt",
    "lat": 11.941268,
    "lng": 108.463187,
    "date": "",
    "type": "candidate",
    "status": "review",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "",
    "far": "",
    "population": "",
    "price": "",
    "sell_price": "",
    "irr": "",
    "risks": "Auto candidate từ Teams mentions; cần review/gom trùng",
    "excerpt": "P.ĐT xin báo cáo Sếp Admin 01 về dự án Khách sạn 5 sao tại đường 12 Hùng Vương, TP Đà Lạt, Tỉnh Lâm Đồng như sau: I. SƠ BỘ VỀ DỰ ÁN Vị trí: 12 Hùng Vương, TP Đà Lạt, Tỉnh Lâm Đồng (Map: https://maps.app.goo.gl/6iyNdteYfVyyT9Xy9) Pháp lý: Đất ở, thời hạn sử dụng đất: lâu dài Quy hoạch: Được quy hoạch làm khách sạn 5 tầng + 2 hầm, tính theo phương án 159 phòng. II. ĐÁNH GIÁ HIỆU QUẢ DỰ ÁN GIẢ ĐỊNH: 1. Phương án kinh doanh (Theo anh David Cường) 2. Tổng Mức Đầu Tư Dự Án: Hiện chưa có TMĐT nên BP Đầu tư giả định gồm có CPXD và tiền đất Nhận xét: Do quỹ đất là đất TMDV có thời hạn sử dụng lâu dài, giá trị quyền sử dụng đất không bị giảm sau khi dự án khách sạn kết thúc vòng đời vận hành. Do đó Bộ phận đầu tư sẽ tính theo 2 phương án: Phương án có đất Phương án không có đất (đánh giá tỷ suất lợi nhuận dựa trên chi phí đầu tư xây dựng ban đầu) a) Hiệu quả 2 phương án b) Độ nhạy Độ nhạy TMĐT/Phòng (bao gồm VAT)/phòng và Giá thuê (bao gồm VAT) đối với PA bao gồm đất Độ nhạy TMĐT/Phòng (Bao gồm ",
    "map_url": "https://maps.app.goo.gl/6iyNdteYfVyyT9Xy9"
  },
  {
    "id": "BDS-TEAMS-0005",
    "name": "Link mở rộng đường LVV",
    "lat": 10.784153,
    "lng": 106.72569,
    "date": "",
    "type": "infrastructure",
    "status": "screening",
    "priority": "medium",
    "address": "",
    "province": "",
    "district": "",
    "area": "",
    "far": "",
    "population": "",
    "price": "",
    "sell_price": "",
    "irr": "",
    "risks": "2026-07-21",
    "excerpt": "Visible Teams link: Link mở rộng đường LVV; visible map link https://maps.app.goo.gl/qDbb6mJHvwhXw4Az6",
    "map_url": "https://maps.app.goo.gl/qDbb6mJHvwhXw4Az6"
  },
  {
    "id": "BDS-TEAMS-0017",
    "name": "Thủ Đức Living Phạm Văn Đồng",
    "lat": 10.8679394,
    "lng": 106.763008,
    "date": "2026-07-21",
    "type": "apartment",
    "status": "rejected",
    "priority": "high",
    "address": "Đường Phạm Văn Đồng",
    "province": "TP.HCM",
    "district": "Thủ Đức",
    "area": "4661",
    "far": "",
    "population": "",
    "price": "400000000000",
    "sell_price": "66000000",
    "irr": "",
    "risks": "Không hiệu quả do dân số thấp không dùng hết HSSDĐ, giá mua đất + nghĩa vụ tài chính + pháp lý cao; đề xuất không nghiên cứu sâu",
    "excerpt": "Chat: dự án Thủ Đức Living đường Phạm Văn Đồng",
    "map_url": "https://maps.app.goo.gl/D8GuCY5LefTH8JVq9"
  },
  {
    "id": "BDS-TEAMS-0031",
    "name": "120 Đặng Văn Bi Thủ Đức",
    "lat": 10.8456644,
    "lng": 106.7620502,
    "date": "",
    "type": "apartment_serviced_apartment",
    "status": "screening",
    "priority": "high",
    "address": "120 Đặng Văn Bi",
    "province": "TP.HCM",
    "district": "Thủ Đức",
    "area": "4604",
    "far": "6",
    "population": "252",
    "price": "234000000000",
    "sell_price": "108500000",
    "irr": "",
    "risks": "",
    "excerpt": "Chat + attachments: 120 Đặng Văn Bi Thủ Đức",
    "map_url": "https://maps.app.goo.gl/dRnRPbNFPmCfsTHAA"
  }
];
